### ISSUE TITLE
Should be able to override legend aesthetics

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#109]
Maybe something like:

```
test_data <- data.frame(
  x = rnorm(100), 
  y = rnorm(100), 
  cat1 = factor(rep(c(1, 2), times = c(50, 50))), 
  cat2 = rnorm(100))
ggplot(test_data, aes(x, y)) +
  geom_point(aes(colour = cat1, size = cat2), alpha = 1/2) + 
  scale_size(alpha = 1) + 
  scale_colour(alpha = 1)
```

**Comment by justacec** [comment]
What happened to this.  I have fallen into the same situation as above, my legends look blank because the alpha is set too low.  I tried the "maybe something like" example above but it does not work.  I also tried something like:

    rp = ggplot(pd) + theme_bw() +
      geom_segment(aes(x = typen - 0.2, xend = typen + 0.05, y = low, yend = low, color = 'low'), alpha = 0.3) +
      geom_segment(aes(x = typen - 0.05, xend = typen + 0.2, y = high, yend = high, color = 'high'), alpha = 0.3) +
      scale_color_manual(name = 'Interval Edge', breaks = c('low', 'high'), values = c('red', 'green'), alpha = 1)
    rp

However, this did not work as well.  How do we go about now having faint lines in the plot but bold enough legend entries to show the overall color?

**Comment by hadley** [comment]
@justacec if you have questions about how to use ggplot2, please use the mailing list.
