### ISSUE TITLE
Specify xlim and ylim for each facet separately

### ISSUE THREAD

**Issue by kohske** [tidyverse/ggplot2#187]
Maybe it is fine if xlim and ylim can be specified for each facet separately, at least, for facet_wrap.
Now, panel contains the information about ranges of each facet, so e.g.,

```
# lims like this:
  vs am xmin xmax ymin ymax
1  0  0    8    8 10.4 19.2
2  0  1    4    8 15.0 26.0
3  1  0    4    6 17.8 24.4
4  1  1    4    4 21.4 33.9
```

and specify by, e.g.,

```
+ facet_wrap(~vs+am, limits = lims)
```

**Comment by pengchy** [comment]
I think the simple way is to modify the original data, remove the unwanted values

**Comment by bshor** [comment]
+1

**Comment by nhamilton1980** [comment]
"I think the simple way is to modify the original data, remove the unwanted values". This doesn't work in many cases, such as the example Hadley mentioned earlier WRT maps. Sometimes you need the data to spool beyond the plot region (but be concealed/masked by the act of applying the limits), since by removing values, this may close and/or truncate paths and create ugly (and inaccurate) rendering of the data.

**Comment by nhamilton1980** [comment]
Frankly I think there should be a 'limiter' function (or rather the 'scales' argument to facet_wrap and/or facet_grid is able to accept a function), which is similar to the 'labeller' function. This limiter function could return 'fixed', 'free_x', 'free_y', 'free', or alternately return a list containing xlim, and ylim values for each facet given the input x and y indexes of the facet.

**Comment by mmrinconh** [comment]
This can be easily done using patchwork library, you just have to add the plots customized as you required: https://github.com/thomasp85/patchwork

**Comment by map2085** [comment]
+1

**Comment by andrewjpfeiffer** [comment]
+1. Any chance of this being reopened?
