### ISSUE TITLE
vjust not working in x  facets

### ISSUE THREAD

**Issue by Eluvias** [tidyverse/ggplot2#1892]
`ggplot2 dev version`

It looks that `vjust` is not working within `strip.text.x `

```r
df <- data.frame(x = c(1,2), z = c("a", "b"))

p <- ggplot(df, aes(x, z)) + geom_point()

fct_y <- p + facet_grid(z ~ .) +
  theme(strip.text.y = element_text( debug = TRUE))

# WORKS
fct_y + theme(strip.text.y = element_text(vjust = 1))
```
![gg_fy](https://cloud.githubusercontent.com/assets/22600883/20005985/3d4f8774-a28d-11e6-8756-dec725d8eebd.png)

```r
fct_x  <- p + facet_grid(.~z) +
  theme(strip.text.x = element_text( debug = TRUE))

# BROKEN
fct_x + theme(strip.text.x = element_text(vjust = 1))
```

![gg_fx](https://cloud.githubusercontent.com/assets/22600883/20006011/644131c0-a28d-11e6-9ab8-cefd61782b89.png)

**Comment by EmanuelContreras** [comment]
****Adding more info to this bug...****
 hjust not working in y facets

**Comment by karawoo** [comment]
This seems like a similar issue to #1435, and I'm not sure it's broken. If you compare `vjust = 0` and `vjust = 1`, you can see that the vertical justification of the text relative to the debugging point _does_ change.

``` r
library("ggplot2")
df <- data.frame(x = c(1, 2), z = c("a", "b"))
p <- ggplot(df, aes(x, z)) + geom_point()
fct_x <- p + facet_grid(. ~ z) + theme(strip.text.x = element_text(debug = TRUE))

## vjust = 0
fct_x + theme(strip.text.x = element_text(vjust = 0))
```

![](http://i.imgur.com/qHTFRHJ.png)

``` r
## vjust = 1
fct_x + theme(strip.text.x = element_text(vjust = 1))
```

![](http://i.imgur.com/sDPB1wz.png)

The actual placement of the strip label does not move, but this is consistent with text placement elsewhere, e.g. axis titles:

``` r
fct_x + theme(axis.title.x = element_text(vjust = 0, debug = TRUE))
```

![](http://i.imgur.com/MBierWJ.png)

``` r
fct_x + theme(axis.title.x = element_text(vjust = 1, debug = TRUE))
```

![](http://i.imgur.com/qoT8B8H.png)

What _is_ different for strip labels is that they interpret `hjust` and `vjust` in absolute terms rather than relative to the direction of the text. In contrast, axis titles can be adjusted with `hjust` no matter their direction:

``` r
fct_x + theme(axis.title = element_text(hjust = 0, debug = TRUE))
```

![](http://i.imgur.com/AwxzhGh.png)
