### ISSUE TITLE
change a value of an aesthetic that wasn't defined in the original layer/plot call

### ISSUE THREAD

**Issue by yonicd** [tidyverse/ggplot2#1894]
is there a way to disconnect a layer from a ggplot object?

i am trying to run this function to create a new ggobject that has a different shape than the original plot.

``` 
library(ggplot2)
library(dplyr)

p=iris%>%ggplot(aes(x=Sepal.Length,y=Sepal.Width,colour=Species))+geom_point()

change_shape=function(a){
  a$layers[[1]]$aes_params[['shape']]=5
  a$layers[[1]]$aes_params[['size']]=10
  return(a)
}

pnew=change_shape(p)
p
```

which changes the layer in p and pnew.

i also tried 

```
pnew=p
a=p1$layer[[1]]
p1$layer[[1]]=NULL
a[['size']]=3
```

which again changes the layer in p

also tried changing the environment

```
k=new.env()
k$a<-p$layers[[1]]
k$a$aes_params[['shape']]=5
```

Is there a way to disconnect a layer (ggproto) from the ggplot object environment? 

Is there a way to clone a plot so it has a new set of connections for the layers?

so is what i am trying to do possible? intended? a bug?

(I've tried on stackoverflow, but no one there knows)

**Comment by hadley** [comment]
It's not intended that you should make this sort of transformation, sorry.

**Comment by yonicd** [comment]
not intended but now possible

[cloneLayer](https://github.com/yonicd/ggedit/blob/master/ggedit/R/cloneLayer.R)

**Comment by baptiste** [comment]
Just for the sake of helping future developers though, could this be noted in a "writing ggplot2 extensions guide"?
It is *very* unexpected for R code to cause such non-local side-effects... 

As a side-note, I wonder if instead of capturing the environment at the layer level, which is what seems to be happening, it wouldn't make sense to capture the whole environment required for the entire ggplot object, and layers would inherit from that (a bit like a function within a function in R -- it can access its parent's frame).

**Comment by hadley** [comment]
If you're going to reach inside the internals of ggproto you can't expect anything. It's not recommended and I don't recommend messing with it unless you're already familiar with prototype based OO. 

The environment is captured at the plot level, which is suboptimal. Ideally it should be captured by each component of the aesthetic mapping.
