### ISSUE TITLE
scale_reverse() prevents expanded minor grid lines

### ISSUE THREAD

**Issue by tingtingben** [tidyverse/ggplot2#2081]
When using `scale_reverse()` while expanding the axis limit to a value close to the upper minor break necessary, this minor grid line is omitted.
Removing `scale_reverse()` produces all of the grid lines expected.
Using `expand_limits()` instead of `coord_cartesian()` only solves the problem for a few cases.

```r
library(ggplot2)

limit_ok <- c(8, 10, 12, 8.1, 8.2, 9.9) # a few limit values for which grid lines are ok 
limit_not_ok <- c(9, 11, 9.1, 10.9) # a few limit values for which the upper minor grid line after the data is omitted 

test_limit <- sample(limit_not_ok, 1) # sample one value among the few examples

ggplot(
  data = iris,
  aes(x = Sepal.Length, y = Petal.Length)
) +
  geom_point() +
  coord_cartesian(
    xlim = c(0, test_limit) 
  ) +
  scale_x_reverse() +
  annotate("text", x = 7.5, y = 2, label = test_limit )
```

**Comment by karawoo** [comment]
Indeed it seems the minor breaks are not getting calculated correctly for reversed scales some of the time, for example:

``` r
library("ggplot2")
library("scales")
scale_x_continuous(limits = c(0, 9))$get_breaks_minor()
#> [1] 0.00 1.25 2.50 3.75 5.00 6.25 7.50 8.75
scale_x_continuous(limits = c(9, 0), trans = reverse_trans())$get_breaks_minor()
#> [1]  0.00 -1.25 -2.50 -3.75 -5.00 -6.25 -7.50
```

The reversed scale is missing a break at -8.75. I believe the problem is in this part of the [`get_breaks_minor`](https://github.com/tidyverse/ggplot2/blob/2fea616463a2e73494ca7219f2cf348c06184eaf/R/scale-.r#L275-L282) function where the minor breaks get calculated:

```r
        if (min(limits) < min(b)) b <- c(b[1] - bd, b)
        if (max(limits) > max(b)) b <- c(b, b[length(b)] + bd)
```

I think to get the correct behavior for `scale_(x|y)_reverse`, those should be:

```r
        if (min(abs(limits)) < min(abs(b))) b <- c(b[1] - bd, b)
        if (max(abs(limits)) > max(abs(b))) b <- c(b, b[length(b)] + bd)
```

For reversed scales, the limits get inverted to become e.g. `c(-9, 0)`, so using `abs()` ensures that the second line gets called, which creates the break at -8.75. Then all the minor breaks appear as they should.

``` r
ggplot(data = iris, aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point() +
  coord_cartesian(xlim = c(0, 9)) +
  scale_x_reverse()
```

![](http://i.imgur.com/3VsdLcY.png)

@hadley does this seem right to you? If so I'll PR this change and add some tests to make sure that the minor breaks match for regular and reversed scales.

**Comment by hadley** [comment]
I think it would be safer to put `limits` in the expected order, i.e. `limits <- range(limits)`. And I suspect `bd <- diff(b)[1]` should be `bd <- abs(diff(b)[1])`. And it might be more clearer to make that `abs(b[2] - b[1])`.

Maybe this method is sufficiently complicated that it's worthwhile to pull out into its own function so we can test it more easily?

**Comment by karawoo** [comment]
I don't think `range(limits)` will fix this because at the point where this is happening in the example `limits` is `c(-9.45, 0.45)`, and `range()` doesn't change that order. I'll work on getting this into a separate function though.

**Comment by karawoo** [comment]
Thinking about this more, I think using `abs()` to calculate `bd` causes other problems, because for a reversed scale it really should be negative to ensure that breaks get added in the correct direction. Compare the two functions below:

``` r
## Break & limit values from the example
b <- c(0.0, -2.5, -5.0, -7.5)
limits <- c(-9.45, 0.45)
n <- 2

calculate_minor_breaks <- function(b, limits, n) {   
  b <- b[!is.na(b)]
  if (length(b) < 2) return()

  bd <- b[2] - b[1]
  if (min(abs(limits)) < min(abs(b))) b <- c(b[1] - bd, b)
  if (max(abs(limits)) > max(abs(b))) b <- c(b, b[length(b)] + bd)
  unique(unlist(mapply(seq, b[-length(b)], b[-1], length.out = n + 1,
                       SIMPLIFY = FALSE)))
}

## Correct break values
calculate_minor_breaks(b, limits, n)
#> [1]   0.00  -1.25  -2.50  -3.75  -5.00  -6.25  -7.50  -8.75 -10.00

calculate_minor_breaks <- function(b, limits, n) {   
  b <- b[!is.na(b)]
  if (length(b) < 2) return()

  ## Use abs() to calculate bd
  bd <- abs(b[2] - b[1])
  if (min(abs(limits)) < min(abs(b))) b <- c(b[1] - bd, b)
  if (max(abs(limits)) > max(abs(b))) b <- c(b, b[length(b)] + bd)
  unique(unlist(mapply(seq, b[-length(b)], b[-1], length.out = n + 1,
                       SIMPLIFY = FALSE)))
}

## bd is positive, so it doesn't get added in the correct direction when scale
## is reversed
calculate_minor_breaks(b, limits, n)
#> [1]  0.00 -1.25 -2.50 -3.75 -5.00 -6.25 -7.50
```

Here is a version that reorders the limits and relies on that order, but I still don't see a way to get around using `abs()` in the comparison.

```r
calculate_minor_breaks <- function(b, limits, n) {  
  b <- b[!is.na(b)]
  if (length(b) < 2) return()

  ## Make sure limits are in order -- this results in c(0.45, -9.45)
  limits <- limits[order(abs(limits))]

  bd <- b[2] - b[1]
  if (abs(limits[1]) < abs(b[1])) b <- c(b[1] - bd, b)
  if (abs(limits[2]) > abs(b[length(b)])) b <- c(b, b[length(b)] + bd)
  unique(unlist(mapply(seq, b[-length(b)], b[-1], length.out = n + 1,
                       SIMPLIFY = FALSE)))
}

calculate_minor_breaks(b, limits, n)
#> [1]   0.00  -1.25  -2.50  -3.75  -5.00  -6.25  -7.50  -8.75 -10.00
```
