### ISSUE TITLE
Boxplot and violin plot disagree on quantiles 

### ISSUE THREAD

**Issue by DarwinAwardWinner** [tidyverse/ggplot2#2088]
I was experimeting with presenting my data using either a boxplot or a violin plot, and at some point I tried both at the same time so I could compare them, and I realized that they were giving slightly different values for the median and IQR. The amount by which they differ varies by data set, but I can easliy reproduce the issue like this:

``` r
library(ggplot2)
ggplot(data.frame(y=rnorm(10000))) + 
    aes(x=1, y=y) + geom_violin(draw_quantiles = c(.25,.5,.75)) + 
    geom_boxplot(fill=NA) + 
    coord_cartesian(ylim=c(-1,1))
```

![](http://i.imgur.com/PDmQsO7.png)

**Comment by hadley** [comment]
Can you please follow the instructions at the top of this issue?

**Comment by DarwinAwardWinner** [comment]
Sorry, I didn't sleep enough last night. I think I've fixed it now.

**Comment by huftis** [comment]
I’m not sure if this is a bug. In `geom_violin()`, the quantiles are calculated based on the *density estimate*:

```r
  dens <- cumsum(data$density) / sum(data$density)
  ecdf <- stats::approxfun(dens, data$y)
  ys <- ecdf(draw_quantiles) # these are all the y-values for quantiles

  # Get the violin bounds for the requested quantiles.
  violin.xminvs <- (stats::approxfun(data$y, data$xminv))(ys)
  violin.xmaxvs <- (stats::approxfun(data$y, data$xmaxv))(ys)
```

I guess this is intentional, to be consistent with the density estimate used in rest of the violin plot (but *not* with the sample quantiles, used by the box plot). This also means that changing the bandwidth used to estimate the density will change the quantile estimates. Here’s a simple example:

```r
ggplot(data.frame(y=rnorm(10000))) + 
    aes(x=1, y=y) +
  geom_violin(draw_quantiles = c(.25,.5,.75), colour="red", bg=NA) + 
    geom_violin(draw_quantiles = c(.25,.5,.75), bw=.5, colour="green", bg=NA) + 
    geom_boxplot(fill=NA) + 
    coord_cartesian(ylim=c(-1,1))
```

![geom_violin-quantiles](https://cloud.githubusercontent.com/assets/100251/24589729/bbe4c758-17df-11e7-8cdc-1a96e28c7d95.png)

**Comment by DarwinAwardWinner** [comment]
I guess that makes sense. Part of the reason I was confused was that on my data, the quantiles all appeared offset by some fixed amount (i.e. all the violin quantiles were below the corresponding boxplot quantiles), which seemed like a graphical misalignment rather than a real difference.

**Comment by hadley** [comment]
Yeah, that sounds right to me.
