### ISSUE TITLE
Request: multiple colours for facet strip.background

### ISSUE THREAD

**Issue by alexconingham** [tidyverse/ggplot2#2096]
This code generates the plot, and changes the strip backgrounds to red:

```
p <- ggplot(mpg, aes(displ, cty)) + geom_point() + facet_grid(. ~ cyl) +
theme(strip.background = element_rect(fill="red"))
```

It would be useful to be able to have each strip a different colour, something like the below seemed intuitive though just makes them red (first colour in the call is used)

```
p <- ggplot(mpg, aes(displ, cty)) + geom_point() + facet_grid(. ~ cyl) +
theme(strip.background = element_rect(fill=c("red","green","blue","yellow")))

```

**Comment by stefanedwards** [comment]
AFAIK it is entirely doable, but introducing vectorized theme elements as you propose raises the question of what users will expect when they are applied to other aspects.

In the meanwhile, here is a solution that modifies the resulting grob. The plot is one of the first examples from `facet_grid`.

```
p <- ggplot(mpg, aes(displ, cty)) + geom_point() + facet_grid(drv ~ cyl)
```
![image](https://cloud.githubusercontent.com/assets/3592346/24867127/2750918c-1e04-11e7-893e-158189a90d40.png)

```
g <- ggplot_gtable(ggplot_build(p))
stripr <- which(grepl('strip-r', g$layout$name))
fills <- c("red","green","blue","yellow")
k <- 1
for (i in stripr) {
  j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}
grid.draw(g)
```
![image](https://cloud.githubusercontent.com/assets/3592346/24867179/4841878e-1e04-11e7-8aa8-15aac9d5b966.png)

Might be pretty with some other colour choices...

**Comment by dickie-roper** [comment]
Sorry, I'm not particularly great in R, but would it be possible to map the fill of the facet strip background to the variable that is being used for the facet (or some other variable)?

Something like...
`... + facet_grid(. ~ cyl, aes(fill=cyl))`

I know it may seem a bit redundant to also colour by the facetting variable but there are cases where it can add some clarity.

**Comment by ondrejhavlicek** [comment]
I second that, it would be super great if facet properties, like the background color, could be mapped to aesthetics! It would help with situations in which the faceting variable is hierarchical/nested (e.g. countries inside continents). Because there doesn't seem to be a simple way to create nested facets yet (https://stackoverflow.com/questions/40316169/nested-facets-in-ggplot2-spanning-groups) coloring would help a lot (facet by country and color by continent).

**Comment by hadley** [comment]
This would require fundamental changes to ggplot2, so is unfortunately not possible.

**Comment by CharlotteWoolley** [comment]
To follow up on this (in case anyone else is looking for the answer), the reason why the code has stopped working is due to changes in g$layout$name. 

It appears that the top rectangles and righthand rectangles now have separate 'names' within this variable. Therefore, they need to be obtained separately.

To colour in just the TOP rectangles, use...
strip_t <- which(grepl('strip-t', g$layout$name))

To colour in just the RIGHT rectangles, use...
strip_r <- which(grepl('strip-r', g$layout$name))

To colour in BOTH the top and right rectangles, use...
strip_both <-  which(grepl('strip-', g$layout$name))

AND make sure that you have enough colours in 'fills' to give a value to every vector in 'strip_both'. There are 7 vectors in 'strip_both' so you need 7 colours...
fills <- c("red","green","blue","yellow","red", "green", "blue")

Finally, the full example:

p <- ggplot(mpg, aes(displ, cty)) + geom_point() + facet_grid(drv ~ cyl)
p
g <- ggplot_gtable(ggplot_build(p))
strip_both <-  which(grepl('strip-', g$layout$name))
fills <- c("red","green","blue","yellow","red","green","blue","yellow")
k <- 1
for (i in strip_both) {
        j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
        g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
        k <- k+1
}
grid.draw(g)

![image](https://user-images.githubusercontent.com/22373502/40172882-e55c26be-59c7-11e8-95ef-3bd3e9cc6cb7.png)
