### ISSUE TITLE
geom_segment: x-axis limits of a plot are changed by the creation of a later plot

### ISSUE THREAD

**Issue by joacorapela** [tidyverse/ggplot2#2102]
---

I created two ggplots with geom_segment and save them to a list. I found that the x-axis limits of the first plot are changed by the creation of the second plot.

To demonstrate this bug the code below creates "Plot 1" and "Plot 2." It prints these plots immediately after creating them and once again after both plots have been created. Compare the two printouts of "Plot 1" and you will see that their x-axis limits are changed. This should not happen because 

Please contact me if this description is not clear.

```r
    plots <- list()
    for(i in 1:2) {
        p <- ggplot()
        anX <- pi/6*i
        p <- p + geom_segment(aes(x=anX, y=0, xend=anX, yend=10))
        p <- p + ggtitle(sprintf("Plot %d", i))
        plots[[i]] <- p
        X11(); print(plots[[i]])
    }
    for(i in 1:2) {
        X11(); print(plots[[i]])
    }

```

**Comment by stefanedwards** [comment]
It is not the creation of the secondary plot that changes the x-axis limits; it is that the variable `anX` is changed.

In your code, `geom_segment(aes(x=anX, y=0, xend=anX, yend=10))`, the value of `anX` appears to be evaluated to the global variable `anX`. See here:
```R
p <- ggplot()
anX <- pi/6 * 1
(p <- p + geom_segment(aes(x=anX, y=0, xend=anX, yend=10)))
anX <- pi/6 * 2
p
anX <- 3 # the special pi.
p
```
So your x-axis is changing due to data used by the plot is changed.

To avoid it, you can do:
```r
plots <- list()
for(i in 1:2) {
     p <- ggplot()
     anX <- pi/6*i
     p <- p + geom_segment(data=data.frame(anX), aes(x=anX, y=0, xend=anX, yend=10))
     p <- p + ggtitle(sprintf("Plot %d", i))
     plots[[i]] <- p
     X11(); print(plots[[i]])
 }
 for(i in 1:2) {
     X11(); print(plots[[i]])
 }
```
whereby the values are saved in a data frame, saved in the actual plot such that it is not altered when the global variabel `anX` is changed.

**Comment by hadley** [comment]
Thanks for the diagnosis @stefanedwards!
