### ISSUE TITLE
overlapping boxes with geom_boxplot(varwidth=TRUE)

### ISSUE THREAD

**Issue by mcol** [tidyverse/ggplot2#2143]
When I try to produce boxplots with colours depending on a categorical variable, these appear overlapping if varwidth is set to TRUE (which is what I'd like to use). 

Here's an example:
```r
ggplot(data=iris, aes(Species, Sepal.Length)) + 
   geom_boxplot(aes(colour=Sepal.Width < 3.2), varwidth=TRUE)
```
This raises the following warning: "position_dodge requires non-overlapping x intervals"

However, the boxes don't overlap (and no warning is raised) if varwidth is not specified.
```r
ggplot(data=iris, aes(Species, Sepal.Length)) + 
   geom_boxplot(aes(colour=Sepal.Width < 3.2))
```

**Comment by hadley** [comment]
Can you please produce a reprex using the reprex package?

**Comment by mcol** [comment]
``` r
require(ggplot2)
#> Loading required package: ggplot2
ggplot(data = iris, aes(Species, Sepal.Length)) + geom_boxplot(aes(colour = Sepal.Width < 
  3.2), varwidth = TRUE)
#> Warning: position_dodge requires non-overlapping x intervals
```

![](http://i.imgur.com/OdBeksl.png)

**Comment by karawoo** [comment]
The main problem is [here](https://github.com/tidyverse/ggplot2/blob/04a707ed6cd3b3e19a07bd5226a2fa44a8e8be91/R/position-collide.r#L49) — within each species the variable-width boxes have different `xmin` values, so `pos_dodge()` gets called on each box separately when it should be getting called on each pair of boxes.

I think [this line](https://github.com/tidyverse/ggplot2/blob/04a707ed6cd3b3e19a07bd5226a2fa44a8e8be91/R/position-collide.r#L26) will also be a problem because only the width of the first box will be used. `pos_dodge()` probably needs to be changed to handle multiple widths.
