### ISSUE TITLE
Double coordinate transformations for geoms that draw with other geoms

### ISSUE THREAD

**Issue by has2k1** [tidyverse/ggplot2#2149]
When a `geom` queries the coordinate range and uses the result to create data that is then plotted by another `geom`, there is potentially a double transformation. i.e. `coord.range()` yields results in coordinate space and if followed by `coord.transform()`, the data may get transformed two times. Affects `coords` that transform the limits in `coord$setup_panel_params` and also do transforms in `coord$transform`. This includes `coord_trans` and `coord_sf`.

Affected geoms include `geom_abline`, `geom_hline` and `geom_hline`.

**reprex**
``` r
library(ggplot2)

df <- data.frame(x=1:6, y=10^(1:6))
ggplot(df, aes(x, y)) +
  geom_point() +
  geom_vline(xintercept=3, color='red') +
  coord_trans(y='log10')
```
![](http://i.imgur.com/XAf6Y4t.png)

The red line (at x=3) should be top to bottom.

**Comment by hadley** [comment]
I don't see any obvious way to fix this. It'll have to wait until someone is deeper into coordinate systems.

**Comment by clauswilke** [comment]
I think the correct way to fix this is to copy the line-drawing code from `geom_segment()`:
https://github.com/tidyverse/ggplot2/blob/4d2ca992dc37fee598d83d3d3f524dbba38f4187/R/geom-segment.r#L106-L141
and modify appropriately for `geom_abline()` etc. It's the geom's responsibility to draw correctly given the data and the coord, and if a geom can't guarantee correct drawing when using another geom's drawing code then it needs to provide its own.

**Comment by hadley** [comment]
I think they have to be straight in the data coordinate system, otherwise I can’t imagine how you’d interpret the parameters in (eg) polar coordinates.

**Comment by clauswilke** [comment]
Actually, I was too quick in blaming `geom_abline()` etc. The problem is with the coords, and specifically with the `range()` function. It looks like the code is inconsistent with respect to whether it returns the range in the original data coordinates or in transformed coordinates. In several places in the code, it is assumed that `range()` returns original data coordinates. One is `geom_abline()` etc., and another location is `coord_munch()`: 
https://github.com/tidyverse/ggplot2/blob/8778b48b37d8b7e41c0f4f213031fb47810e70aa/R/coord-munch.r#L14-L35

Thus, I can trigger a similar problem with `geom_line()`:
``` r
library(ggplot2)
df <- data.frame(x = c(-Inf, Inf), y = c(1, 2))
p <- ggplot(df, aes(x, y)) + geom_line() + xlim(1, 2)
p
```

![](https://i.imgur.com/UFnZfJg.png)

``` r
p + coord_flip()
```

![](https://i.imgur.com/05bxujw.png)

``` r
p + coord_polar()
```

![](https://i.imgur.com/qdzh2Ns.png)

``` r
p + coord_trans(y = "log10")
```

![](https://i.imgur.com/Bph2Bqo.png)

``` r
p + coord_trans(x = "log10")
#> Warning in self$trans$x$transform(x): NaNs produced
#> Warning in trans$transform(value): NaNs produced
#> Warning: Transformation introduced infinite values in x-axis
```

![](https://i.imgur.com/f2UGbMy.png)

Created on 2018-08-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Notice how `coord_flip()` and `coord_polar()` return the correct values but `coord_trans()` does not for x coordinates (it doesn't matter for y). One way to fix this would be to make sure that the `range()` function always returns the range in the original data coordinates. However, I'm not yet clear on whether there are other parts of the code that expect `range()` to return transformed coordinates. An alternative way to fix this would be to provide a second range function that always returns untransformed coordinates.
