### ISSUE TITLE
Retina option for ggsave

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2156]
It would be useful to have an option to `ggsave()` that made it easy to produce retina quality graphics. This might be as simple as supporting `dpi = "retina"`.

**Comment by hadley** [comment]
Perhaps it would be best to generalise to support "print", "screen", and "retina" ?

**Comment by foo-bar-baz-qux** [comment]
Sounds good to me, I had to experiment with this figure when I first started with ggplot to find a DPI I was satisfied with. This option would help save some time. I could have a go at implementing this.

I'm thinking `print` is 300 DPI/PPI and `screen` is 72 DPI/PPI per standard? 

Retina is a little trickier though since it's supposed to be a resolution at which the eye cannot distinguish the individual pixels, which is dependent on viewing distance and physical screen size. The [wiki article](https://en.wikipedia.org/wiki/Retina_Display) suggests 300 PPI was the initial figure for a handheld device, with the latest iPhones having 401 PPI (the highest on the list) and larger displays ~220 PPI. Would it make sense to go with the highest PPI (401)?

**Comment by hadley** [comment]
I think just doubling the dpi is standard.

**Comment by dylan-stark** [comment]
I agree with Hadley: the practical answer for retina is to double the available PPI (`dpi` for `ggsave()`). This is what's done in knitr and in [this gist](https://gist.github.com/jcheng5/452a25c32d67d52d68c0529e1c08f59f). It's also the advice in the graphic design community (ex. [here](https://www.smashingmagazine.com/2015/05/retina-design-in-photoshop/)).

One thing to consider is that some phones are at triple the pixel density (e.g., iPhone 6 Plus). Not sure if that warrants having "retina-2" and "retina-3". Maybe an extra "retina-plus" option? (Though the 8 is rumored to be at 3x, too.)

**Comment by foo-bar-baz-qux** [comment]
Thanks for the links, @dylan-stark they were helpful. If I'm understanding it correctly, it seems there should be 2 changes to implement this feature then:
1. Support special dpi arguments, like `screen (= 72 or 96)`, `print (= 300)`, maybe `mdpi (= 160)` for mobile developers.
2. A `retina` argument that is either FALSE (no scaling), TRUE (2x DPI). And perhaps `retina-2`, `retina-3` for 3x and 4x DPI scaling respectively.

Compared to the gist linked, `ggsave()` doesn't support `px` inputs, so I would assume this means the user has to do the arithmetic to get the correct DP units at MDPI (160 DPI, or whichever baseline they are using) specified in inches/mm/cm. The retina scaling should then only apply to the DPI, since that will propagate to the output dimensions in pixels.

**Comment by hadley** [comment]
I think we just need more string options for dpi: screen, retina, and print.
