### ISSUE TITLE
theme arguments axis.text and strip.text don't inherit from text

### ISSUE THREAD

**Issue by jzadra** [tidyverse/ggplot2#2175]
In the help file for `theme()`,  it states that the arguments `axis.text` and `strip.text` inherit from `text`.  However, this doesn't seem to be true:

`ggplot(diamonds, aes(x = cut, y = price)) + geom_boxplot() + facet_wrap(~color) + theme(text = element_text(color = "red"))`
![image](https://user-images.githubusercontent.com/25590353/27408880-f432d5e6-569b-11e7-9ff2-8b7ba0cd885d.png)

Note that setting them manually does work:
`ggplot(diamonds, aes(x = cut, y = price)) + geom_boxplot() + facet_wrap(~color) + theme(text = element_text(color = "red"), axis.text = element_text(color = "red"), strip.text = element_text(color = "red"))`
![image](https://user-images.githubusercontent.com/25590353/27408912-0ea43ac8-569c-11e7-8b76-c7774d917e16.png)

**Comment by karawoo** [comment]
Odd, [these](https://github.com/tidyverse/ggplot2/blob/04a707ed6cd3b3e19a07bd5226a2fa44a8e8be91/R/theme-elements.r#L269) [elements](https://github.com/tidyverse/ggplot2/blob/04a707ed6cd3b3e19a07bd5226a2fa44a8e8be91/R/theme-elements.r#L276) certainly seem like they _should_ be inheriting from `text`, but I can reproduce this problem.

**Comment by foo-bar-baz-qux** [comment]
The issue is that the default theme `theme_gray()` (and most other default themes I could see, aside from `theme_void()`)  sets default colors for `axis.text` and `strip.text`. So while `axis.text` and `strip.text` do inherit colors from `text`, most of the default themes actually specify those colors directly so the inheritance doesn't actually do any work. You can see the inheritance working if you manually set the color elements for `axis.text` and `strip.text` to `NULL`.

```r
ggplot(diamonds, aes(x = cut, y = price)) + 
  geom_boxplot() + 
  facet_wrap(~color) +
  theme(text = element_text(color = "red"), 
        strip.text = NULL, 
        axis.text = NULL)
```

It seems even `theme_minimal()` sets the colors for these elements so would probably need to setup a new blank theme (probably based on `theme_void()`) to consistently get this inheritance.

**Comment by hadley** [comment]
I don't think it's worth messing with the theme hierarchy in order to support this rarely needed behaviour.
