### ISSUE TITLE
Width changes in geom_col may render the plot invisible

### ISSUE THREAD

**Issue by arthur-st** [tidyverse/ggplot2#2187]
If two time series are plotted as overlapping bar charts, with timeline in the `datetime` format, any changes to width (incl. `width = 0.9`) will render the data invisible. Please find a reproducible example, and plot examples from it, below. RStudio 1.0.143, R 3.4.0. (64-bit), ggplot2 2.2.1.

With date as `double` (as seen in `date` column of `txhousing` dataset) the code works as intended.

```r
library(ggplot2)
library(lubridate)

txhm <- add_column(txhousing, dttm = date_decimal(txhousing$date, tz = "UTC"))

normal.plot <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings")) +
  geom_col(aes(y = sales, fill = "sales"))
normal.plot

blank.plot <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings"), width=1) +
  geom_col(aes(y = sales, fill = "sales"), width=1)
blank.plot
```

normal.plot:
![image](https://user-images.githubusercontent.com/29796606/27735391-02a44e1c-5da8-11e7-88d3-afd502f153c3.png)

blank.plot:
![image](https://user-images.githubusercontent.com/29796606/27735408-0fe87cce-5da8-11e7-8e49-4a37d83f166f.png)

**Comment by karawoo** [comment]
This happens with a single time series too. A slightly more minimal example:

``` r
library("tidyverse")

txhm <- add_column(txhousing, dttm = date_decimal(txhousing$date, tz = "UTC"))

p1 <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings"))
p1
#> Warning: Removed 1424 rows containing missing values (position_stack).
```

![](http://i.imgur.com/OmQvPY4.png)

``` r

p2 <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings"), width=1)
p2
#> Warning: Removed 1424 rows containing missing values (position_stack).
```

![](http://i.imgur.com/fKHc4EF.png)

Looking at the plot data reveals the problem: in the second plot `xmin` and `xmax` are the same, so the bars have width 0.

``` r
head(ggplot_build(p2)$data[[1]])
#> Warning: Removed 1424 rows containing missing values (position_stack).
#>      fill    y         x PANEL group ymin ymax      xmin      xmax colour
#> 1 #F8766D  701 946684800     1     1    0  701 946684800 946684800     NA
#> 2 #F8766D 1673 946684800     1     1  701 1673 946684800 946684800     NA
#> 3 #F8766D 3090 946684800     1     1 1673 3090 946684800 946684800     NA
#> 4 #F8766D 6174 946684800     1     1 3090 6174 946684800 946684800     NA
#> 5 #F8766D 7940 946684800     1     1 6174 7940 946684800 946684800     NA
#> 6 #F8766D 8816 946684800     1     1 7940 8816 946684800 946684800     NA
#>   size linetype alpha
#> 1  0.5        1    NA
#> 2  0.5        1    NA
#> 3  0.5        1    NA
#> 4  0.5        1    NA
#> 5  0.5        1    NA
#> 6  0.5        1    NA
```

**Comment by foo-bar-baz-qux** [comment]
So it looks like `width` is [specified in absolute values](https://github.com/tidyverse/ggplot2/blob/c9fccfddcc650fe03901922c01ff7db3c2da4c14/R/geom-col.r#L36) rather than relative units. Normally this would probably be fine since data tends to be sequential along the x-axis, but when the x-values are defined over huge ranges, there's probably insufficient resolution to display a bar of width 1. Specifically, `xmin` and `xmax` will be -+ 1/2 compared to the value of `x` (respectively) when width is 1. Sometimes this doesn't show up due to some automatic rounding when R prints large numbers, but you can see the exact precision using `sprintf()`. Following from @karawoo's example:

```r
> ggplot_build(p2)$data[[1]]$xmin[1]
[1] 946684800
# Warning message:
# Removed 1424 rows containing missing values (position_stack). 
> sprintf('%.4f', ggplot_build(p2)$data[[1]]$xmin[1])
[1] "946684799.5000"
```

The datetime values appear to be stored as unix timestamps (e.g. `946684800` for 1 January 2000), which means even between a month, the distances can be large since the value differences would correspond to the number of seconds. Here, the `dttm` column has a granularity of a month, so the `width` between bars is approximately `2635200` (30 or so days).

By default, `geom_col` sets the width to be 90% of the minimum distance between the x-value of the bars. This probably corresponds to the number of seconds in February since it's the shortest month. 
```r
resolution(ggplot_build(p2)$data[[1]]$x, FALSE) * 0.9  # 2365200
```
If we use this result in a new plot, we can see that the original plot with no specified width is re-created:
```r
p_manual <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings"), width=2365200)
p_manual
```

One way to set the width to some proportion `K` of the minimum distance between x values is to evaluate manually:
```r
K <- 0.5  # 50% of minimum
p_manual <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings"), width=resolution(as.double(txhm$dttm), FALSE) * K)
p_manual
```

![image](https://user-images.githubusercontent.com/7685769/28001124-47f5cd90-64f8-11e7-829f-6231f87ef7d7.png)

**Comment by hadley** [comment]
The fundamental problem with bars is that they all need to be the same width - you could either use `geom_rect()` (which would be a lot fiddlier) or just use a continuous approximation with `geom_area()`.

Thanks for the careful analysis @foo-bar-baz-qux !
