### ISSUE TITLE
stat_bin2d with drop=FALSE still drops some 0-count cells

### ISSUE THREAD

**Issue by alchenist** [tidyverse/ggplot2#2202]
The `drop` parameter in stat_bin2d does not appear to work as advertised: docs state that "if [drop is] TRUE removes all cells with 0 counts." Given this, my expected behavior when `drop = FALSE` was something akin to the bottom plot. Instead, `drop = FALSE` results in the second plot, which does keep 0-count cells in x- or y-bins with some values but omits them in bins with no values.

Is this expected behavior? Or should bin indices that don't appear at all in the data be added back into the output of [`ulevels`](https://github.com/tidyverse/ggplot2/blob/8778b48b37d8b7e41c0f4f213031fb47810e70aa/R/facet-grid-.r#L402) applied to bin indices in [`tapply_df`](https://github.com/tidyverse/ggplot2/blob/b05c6c1f61a52311809ffda775eb258b07518dab/R/stat-summary-2d.r#L119)?

``` r
library(dplyr)
library(tidyr)
library(ggplot2)

data(iris)

iris %>%
  ggplot(aes(Petal.Length, Petal.Width)) + stat_bin2d(aes(fill=..count..), drop=TRUE)
```

![](http://i.imgur.com/KrMmVtC.png)

``` r

iris %>%
  ggplot(aes(Petal.Length, Petal.Width)) + stat_bin2d(aes(fill=..count..), drop=FALSE)
```

![](http://i.imgur.com/akcg9rh.png)

``` r

iris %>% 
  mutate(
    bin_x = cut(Petal.Length, breaks = 30),
    bin_y = cut(Petal.Width, breaks = 30)
  ) %>% 
  count(bin_x, bin_y) %>% 
  tidyr::complete(bin_x, bin_y, fill = list(n = 0)) %>% 
  ggplot(aes(bin_x, bin_y, fill = n)) + geom_tile()
```

![](http://i.imgur.com/spe89q6.png)

**Comment by rpruim** [comment]
I believe the same issue occurs in `stat_summary_2d()`.

### stat_bin2d() version

``` r
library(ggplot2)
ggplot(data = diamonds, aes(y = carat, x = cut)) + stat_bin2d(drop = FALSE)
```

![](http://i.imgur.com/vUCyz4G.png)
### stat_summary_2d() version

``` r
library(ggplot2)
ggplot(data = diamonds, aes(y = carat, x = cut, z = carat)) + 
  stat_summary_2d(drop = FALSE, fun = length)
```

![](http://i.imgur.com/BovCzfT.png)

**Comment by hadley** [comment]
It's not easy to do this in general because you have to impute a complete grid from partial contents (and this is particularly hard to do in floating point). Therefore I think this is outside the scope of ggplot2, and you should fill in the implicit missing values elsewhere in your data manipulation pipeline.

**Comment by rpruim** [comment]
I'm not sure I completely follow.  It seems like you have already essentially imputed a grid to make the plot, and the plot will be the same no matter how you subdivide the "empty" portions of the plot since the count will be 0 in each of those regions no matter how they are subdivided.

In any case, it seems like the documentation should make it clearer just what `drop = FALSE` does, since it doesn't do the obvious thing.
