### ISSUE TITLE
geom_bar under ggplot2 - how does it treat NAs if the X variable is a factor?

### ISSUE THREAD

**Issue by dl7631** [tidyverse/ggplot2#2222]
---

Very sorry, I am not posting it in reprex, but it's super-simple.
I am looking at geom_bar help:
library(ggplot2)
?geom_bar
na.rm: If FALSE, the default, missing values are removed with a warning. If TRUE, missing values are silently removed.

Here is my data set with one variable that is an unordered factor:
md <- data.frame(a = c(letters[1:5], letters[1:4], letters[1:3], rep(NA, 3)))

Neither of the 2 commands below removes NAs:
ggplot(data = md, mapping = aes(x = a)) + geom_bar(na.rm = F)
ggplot(data = md, mapping = aes(x = a)) + geom_bar(na.rm = TRUE)

Is this a bug? Because it works as described in 'help' when the X variable is an integer or an ordered factor, but not with an unordered factor

**Comment by karawoo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

For this example it'd be helpful to see an example of an ordered factor as well where the NA values are dropped as well.

**Comment by dl7631** [comment]
Sorry, I just don't have time. The repeatable example is right there: 
md <- data.frame(a = c(letters[1:5], letters[1:4], letters[1:3], rep(NA, 3)))
# Neither of the 2 commands below removes NAs (contrary to Help):
ggplot(data = md, mapping = aes(x = a)) + geom_bar(na.rm = F)
ggplot(data = md, mapping = aes(x = a)) + geom_bar(na.rm = TRUE)

**Comment by hadley** [comment]
Given that you've asked elsewhere and don't seem interested in helping us help you, I'm going to close this issue.
