### ISSUE TITLE
geom_bar bins vanish with small differences between x values

### ISSUE THREAD

**Issue by patr1ckm** [tidyverse/ggplot2#2250]
The bins on `geom_bar` and `geom_col` vanish when x contains distinct values that are distinct, but close:

```r
x <- c(.01, .01001, .2, .2002)
df <- data.frame(x = x, y = 1:length(x))
ggplot(df) + geom_bar(aes(y = y, x = x), stat = "identity")
```
![image](https://user-images.githubusercontent.com/427445/29730056-52c395c4-89a4-11e7-8d8a-d188b3d98e73.png)

While rounding `x` successfully produces a plot:

```r
x <- round(c(.01, .01001, .2, .2002), 2)
df <- data.frame(x = x, y = 1:length(x))
ggplot(df) + geom_bar(aes(y = y, x = x), stat = "identity")
```
![image](https://user-images.githubusercontent.com/427445/29730047-48564456-89a4-11e7-960b-b19ac18c69f8.png)

**Comment by mcol** [comment]
This seems due to how the width of the bars are computed:
* in the first case (the buggy one), the resolution() function returns 1e-05 (0.01001 - 0.01000), width is 1e-05 * 0.9 = 9e-06
* in the second case, resolution() returns 0.19 (0.2 - 0.01), width amounts to 0.171

In the first case, the bars have virtually zero width. If I override it to a larger value (by hacking geom-bar.r), they do appear.

**Comment by hadley** [comment]
You can either set the `width` manually, or set the border `colour`.
