### ISSUE TITLE
Plotting and saving slow with geom_label

### ISSUE THREAD

**Issue by pscheid92** [tidyverse/ggplot2#2266]
### Description

We use ggplot2 in an internal application.
Therefore multiple lines and labels are needed in one plot.
The application allows to save the plot as png.
The addition of one label with `geom_label()` is increasing the needed time to plot and save the graphic.

### Expected Behavior

There should be an small time difference between processing a plot with and without `geom_label()`.

### Actual Behavior

`geom_label()` slows down the plotting process significantly.
Even with only one label.

### Minimal Example

```r

library(ggplot2)

s <- seq(0, 300, 0.25)

df <- data.frame(
    x = s,
    y = sin(s)
)

time_plot_without_label <- system.time({
    plot_without_label <- ggplot(df, aes(x = x, y = y)) + geom_line()
    print(plot_without_label)
    ggsave(filename = "plot_without_label.png", plot = plot_without_label)
})

time_plot_with_label <- system.time({
    plot_with_label <- ggplot(df, aes(x, y)) + geom_line() + geom_label(x = 1, y = 0, label = "test")
    print(plot_with_label)
    ggsave(filename = "plot_with_label.png", plot = plot_with_label)
})

print("Used time without label")
print(time_plot_without_label)

print("Used time with label")
print(time_plot_with_label)


```

**Comment by pscheid92** [comment]
Result of the minimal example on my notebook:

```
[1] "Used time without label"
       User      System verstrichen 
      2.739       0.011       2.758 

[1] "Used time with label"
       User      System verstrichen 
     15.407       0.011      15.485 
```

**Comment by aosmith16** [comment]
This is likely due to `geom_label` repeating every value of the label for every row in the dataset.  See the answer to this [Stack Overflow question](https://stackoverflow.com/questions/10952832/ggplot2-is-there-a-fix-for-jagged-poor-quality-text-produced-by-geom-text) for some details.

You can use `annotate` for adding labels.

`annotate(geom = "label", x = 1, y = 0, label = "test")`

Or you can put your labels into a new `data.frame` for the `geom_label` layer.

`geom_label(data = data.frame(x = 1, y = 0, label = "test"), aes(x = x, y = y, label = label))`

Both of these options speed things up considerably for me.

**Comment by pscheid92** [comment]
Thank you very much for your help!
Those tricks solve the problem.

I'm currently at a different notebook leading to the following results (last two are your hints):

```
Used time without label
       User      System verstrichen 
      0.953       0.001       0.956 


Used time with label
       User      System verstrichen 
     15.230       0.005      15.300 


Used time with trick
       User      System verstrichen 
      0.999       0.003       1.003 


Used time with trick 2
       User      System verstrichen 
      0.974       0.001       0.977 

```
