### ISSUE TITLE
Any new line added after plot is drawn erases the plot

### ISSUE THREAD

**Issue by ozgen92** [tidyverse/ggplot2#2270]
I am using a violin plot with the following code, which works perfectly fine on its own:
```
CoefficientPlotter <- function(...){
  ...
  quartz("CV Plot", 4, 3, bg="white");
  violinPlot <- ggplot( totalError, aes(x=Type, y=AvgError)) + geom_violin(size=1.25, colour="darkred") + #geom_boxplot(width=0.1) +
    ylim(0, 100) + ylab("Coeff. Variation [%]") + xlab("") +
    theme_bw() + 
    theme(plot.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank() ) +
    theme(panel.border= element_blank()) +
    theme(axis.line.x = element_line(color="black", size = 0.25), axis.line.y = element_line(color="black", size = 0.25));
  violinPlot;
}
```

However adding any line after the last line of violinPlot; erases the plot on quartz window. Even a simple statement like newVariable<-5; ruins the graph. (Line I wanted to add is just quartz.save(...) )

PS: As a workaround I just save from the main script where the function is called, therefore it is not really necessary to fix it. I just thought it could be a bug.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
Actually, it's most likely that you're just missing an explicit `print()`
