### ISSUE TITLE
Specifying a function for the graphics device in ggsave only works for pdf

### ISSUE THREAD

**Issue by patr1ckm** [tidyverse/ggplot2#2276]
Specifying the graphics device as a function doesn't appear to work correctly in `ggsave`:

```r
library(ggplot2)
p <- ggplot(data.frame(x = 1:5, y = 1:5), aes(x, y)) + geom_point()
p
ggsave("plot.png", device = png)
```
![plot_small](https://user-images.githubusercontent.com/427445/30944489-e09d0208-a3bd-11e7-90cc-62e9de873aad.png)

Specifying the units doesn't help:
```r
ggsave("plot.png", device = png, width = 5, height = 5, units = "in")
```
![plot_small_2](https://user-images.githubusercontent.com/427445/30944499-fb63c900-a3bd-11e7-9c1c-4dee9a97f6d9.png)

This is also true for the `jpeg` and `tiff` devices.

```r
ggsave("plot.jpg", device = jpeg)
ggsave("plot.tiff", device = tiff)
```
![plot](https://user-images.githubusercontent.com/427445/30944586-8a2eb1a4-a3be-11e7-8291-e19c6ae8c227.jpg)

However, the `pdf` device works:

```r
ggsave("plot.pdf", device = pdf)
ggsave("plot.pdf", device = pdf, width = 5, height = 5, units = "in")
```
[plot.pdf](https://github.com/tidyverse/ggplot2/files/1339104/plot.pdf)

And in all cases, it works to specify the device as a string.
```r
ggsave("plot.pdf", device = "png")
```
![plot](https://user-images.githubusercontent.com/427445/30944656-f213ad38-a3be-11e7-845a-fad60a688cad.png)

**Comment by foo-bar-baz-qux** [comment]
Confirmed. I believe the problem is that using the string form will set some default parameters for the device. Notably, it will wrap the device function and set the correct units and dpi for devices that support it, returning this wrapped function (otherwise, `png` and other devices will operate in pixels rather than inches). Finally, it will pass the filename, height and width. [Relevant portion of the code here](https://github.com/tidyverse/ggplot2/blob/a5e2dd49dd0b7465adac68994ce487234573f128/R/save.r#L123).

So if you wanted to pass your own device, you *may* have to set the units and resolution if the defaults are not going to work properly. E.g. for `png`:
```r
ggsave("plot.png", device = function(...) png(..., units="in", res=300))
```

I think it is worth clarifying in the `ggsave()` documentation that only filename, height and width will be supplied to the user-provided device function.

**Comment by hadley** [comment]
This an esoteric problem, the fix is non-obvious (since not all graphics devices take `unit` and `res` arguments), and there's an existing work around (use the filename, or use the graphics device directly). Unfortunately this means I don't have the time to invest in fixing this bug.
