### ISSUE TITLE
theme_classic() facets outline (element_rect()) not aligned with axis

### ISSUE THREAD

**Issue by ekatko1** [tidyverse/ggplot2#2325]
---

When exporting a ggplot, the lack of alignment between the element_rect() around facet text and the axis, such as in theme_classic() is not aesthetically pleasing. See http://ggplot2.tidyverse.org/reference/ggtheme.html for an example. The effect is amplified as the plot area decreases and the number of facets increases. 

```r
library(ggplot2)
p <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg,
                                     colour = factor(gear))) + facet_wrap(~am, nrow=2)
p + theme_classic() + theme(strip.background=element_rect(size=3), axis.line = element_line(size=1.5))
```
![image](https://user-images.githubusercontent.com/26992969/32408626-a37bc072-c171-11e7-9921-d6352d9c4217.png)
```r
ggsave(file="bob.png", width=3, height=4)
openfile(file="bob.png")
#> Error in openfile(file = "bob.png"): could not find function "openfile"```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by ptoche** [comment]
your code doesn't run, as far as I know ``import`` is used with ``Python`` not ``R``. Are you having these problems in Python?

    library(ggplot2)
    ggplot(mtcars) + 
        geom_point(aes(x = wt, y = mpg,
                       colour = factor(gear))) + 
        facet_wrap(~am, ncol=2) +
        theme_classic()

![rplot](https://user-images.githubusercontent.com/6339274/32403608-6c80e52c-c179-11e7-8395-3ac4ab067dcc.png)

I don't see anything visually problematic.

**Comment by ekatko1** [comment]
Sorry about, that, I switched import() to library(). The problem is that the facet 0 border is not aligned with the y-axis. This may not be the best example how this is visually unappealing, but it shows my point.
Here is what I mean, emphasized using larger line widths. This would be ok for most purposes, but looks kind of awkward in a publication plot with multiple facets even with a line width of just 1, for example.
 
![bob](https://user-images.githubusercontent.com/26992969/32408296-18c17a6c-c16c-11e7-8a47-e62423f9c259.png)

**Comment by ptoche** [comment]
I understand. If you replace ``theme_classic()`` by ``theme_bw()`` you'll see (from your example, I have not tested at all) that the facets are correctly aligned with the grid. What happens, I think, is that the vertical axis is aligned to the outside of the grid. Thus the misalignment at the top between the y-axis and the facet is caused by the same placement of the y-axis which causes a misalignment at the origin. If the y axis were aligned on the inside, the misalignment would disappear. However, at the same time the y axis would start "eating" into the data area (positive orthant), so I imagine that is why there was a design decision not to do that. A fix that would satisfy you as well as leaving the whole x>0 and y>0 quadrant free of ink would therefore involve extending the x-axis to the left as well as extending the facet to the left. 

As someone who is very partial to thin axes and ``theme(strip.background = element_blank())`` I'm afraid I have no great tips to give you. I'm not sure that it's worth fixing. But do look at this page for ideas: https://github.com/baptiste/gridextra/wiki/arranging-ggplot

**Comment by ptoche** [comment]
You can edit the title of your issue and remove __"on export"__  because the problem can clearly be seen in the ``RStudio`` console.

**Comment by hadley** [comment]
Improving this behaviour seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.

**Comment by ekatko1** [comment]
Thanks hadley, I'll try my best to fix it.

**Comment by ekatko1** [comment]
Any pointers as to what files I should start looking at to fix the problem?
