### ISSUE TITLE
Error in installing dev version of ggplot2

### ISSUE THREAD

**Issue by monikav** [tidyverse/ggplot2#2393]
**Brief description of the problem**
When trying to install the development version of ggplot2 using devtools package in RStudio, an error occurs like below
    _Error : 'enexprs' is not an exported object from 'namespace:rlang'
          Error : unable to load R code in package ‘ggplot2’
          ERROR: lazy loading failed for package ‘ggplot2’_

It used to get installed successfully with the earlier versions but recently started having problems in the installation. To recreate the problem, remove the existing version of ggplot2 from RStudio and download the latest release using the reprex below.

```r
devtools::install_github("tidyverse/ggplot2")
```

**Comment by batpigandme** [comment]
Hi @monikav,

Yes, I ran into the same issue this morning as well.

Right now, you'll have to install the dev version of [rlang](https://github.com/tidyverse/rlang) in order to install the dev version of ggplot2. We're aware of the issue, though, and working on a fix. (See #2392).

```r
devtools::install_github("tidyverse/rlang", build_vignettes = TRUE)
```
After that, the dev version of ggplot2 installs fine.

**Comment by monikav** [comment]
@batpigandme It worked. Thanks.
