### ISSUE TITLE
geom_path(linejoin = "mitre")

### ISSUE THREAD

**Issue by behrman** [tidyverse/ggplot2#2399]
The code below does not mitre the path segments as in [geom_path() documentation](http://ggplot2.tidyverse.org/reference/geom_path.html).

Bill

``` r
suppressMessages(library(tidyverse))

tibble(x = 0:2, y = c(0, 1, 0), size = c(8, 4, 4)) %>% 
  ggplot(aes(x, y, size = size)) +
  geom_path(linejoin = "mitre") +
  scale_size(range = c(4, 8)) +
  coord_fixed()
```

![](https://i.imgur.com/qUmAmwF.png)

**Comment by batpigandme** [comment]
Thanks, Bill. Just adding my snippets from [the community thread](https://community.rstudio.com/t/geom-path-linejoin-mitre/4185/2?u=mara) since I have them, so it'll (hopefully) be easier to navigate sources when we troubleshoot.

Exact replication of the example using linejoin = "mitre" from the doc example
``` r
# Control line join parameters
library(ggplot2)
df <- data.frame(x = 1:3, y = c(4, 1, 9))
base <- ggplot(df, aes(x, y))
base + geom_path(size = 10, linejoin = "mitre", lineend = "butt")
```

![](https://i.imgur.com/WAB0Msz.png)

Created on 2018-01-13 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

And the example with the same code from the [docs](http://ggplot2.tidyverse.org/reference/geom_path.html#examples):
![Example of linejoin mitre from ggplot2 docs](http://ggplot2.tidyverse.org/reference/geom_path-24.png)

Bonus forensic investigation 🔎: I checked out the ggplot2 repo, and looked for issues mentioning [`mitre` or linejoin](https://github.com/tidyverse/ggplot2/issues?utf8=%E2%9C%93&q=is%3Aissue+mitre+). The [most recent](https://github.com/tidyverse/ggplot2/issues/774) was 2014, however, the [pull request that closed it](https://github.com/tidyverse/ggplot2/pull/2132) wasn't long ago. Then I looked for the most recent mention of [linejoin in NEWS.md](https://github.com/tidyverse/ggplot2/blame/bf9255e50cb8333e26133cc81927e5baff986d2a/NEWS#L964) (4 years ago),  [searched for "linejoin"](https://github.com/tidyverse/ggplot2/search?utf8=%E2%9C%93&q=linejoin&type=), found somewhat recent changes for [linejoin in `geom_segment.R`](https://github.com/tidyverse/ggplot2/commit/1f25e57ef84303294b902d4ca4c7e5edb4b9abf6), but, this was in `geom_path()`.

**Comment by Ax3man** [comment]
The documented example works as expected for me on 2.2.1. Using differently sized segments (as in OPs example) never works, as the segments get connected by size and therefore respond to the `lineend` parameter, not the `linejoin`.

**Comment by batpigandme** [comment]
Interesting, the CRAN version (2.2.1) works as expected (see reprex below), but the dev version does not (shown in https://github.com/tidyverse/ggplot2/issues/2399#issuecomment-357469425, above, `tidyverse/ggplot2@3fb3fb0`)
``` r
# Control line join parameters
library(ggplot2)
df <- data.frame(x = 1:3, y = c(4, 1, 9))
base <- ggplot(df, aes(x, y))
base + geom_path(size = 10, linejoin = "mitre", lineend = "butt")
```

![](https://i.imgur.com/GzLhkS5.png)

**Comment by Ax3man** [comment]
Possibly related to 3553f31f03209610150ba07bbe0ae89dc69f358e?

**Comment by batpigandme** [comment]
@Ax3man good call. 👍  Works as it should when `linemitre = 1` is passed as an argument. @behrman, your example doesn't work, but, as mentioned, I think that has to do with the change in size at the line joins.

``` r
library(ggplot2)
df <- data.frame(x = 1:3, y = c(4, 1, 9))
base <- ggplot(df, aes(x, y))
base + geom_path(size = 10, linejoin = "mitre", linemitre = 1)
```

![](https://i.imgur.com/S7dVozi.png)

Created on 2018-01-15 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

_n.b._ When passed `linemitre = 10`, it appears un-mitred. (@hadley, not sure if this is what's meant by better matching base R, per the comment in 3553f31f03209610150ba07bbe0ae89dc69f358e).

``` r
library(ggplot2)
df <- data.frame(x = 1:3, y = c(4, 1, 9))
base <- ggplot(df, aes(x, y))
base + geom_path(size = 10, linejoin = "mitre", linemitre = 10)
```

![](https://i.imgur.com/qmu88di.png)

Created on 2018-01-15 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by behrman** [comment]
Yes, mitering works when the line segments are the same size, but doesn't work when the segments are of different sizes. Is there any way to get this to work for segments of different sizes?

I'm using ggplot2 2.2.1.9000.

Thanks

**Comment by hadley** [comment]
I don't think so - the underlying grid grob doesn't support varying widths.

**Comment by batpigandme** [comment]
Since it sounds like this isn't possible, I'm gonna go ahead and close the issue.
