### ISSUE TITLE
Inconsistency between generated pdf and png files

### ISSUE THREAD

**Issue by henrikmidtiby** [tidyverse/ggplot2#2407]
I have observed an inconsistency between the generated pdf and png files in the plot below.
In the plot I insert an annotate object with the type 'label'; where the width of the black line around the label is set to zero.
This works fine when exporting to a png file.
But when I export the plot to a pdf file, the black line is still present.

```
library(tidyverse)
#> ── Attaching packages ──────────────────────────────────────────────────── tidyverse 1.2.1 ──
#> ✔ ggplot2 2.2.1     ✔ purrr   0.2.4
#> ✔ tibble  1.4.1     ✔ dplyr   0.7.4
#> ✔ tidyr   0.7.2     ✔ stringr 1.2.0
#> ✔ readr   1.1.1     ✔ forcats 0.2.0
#> ── Conflicts ─────────────────────────────────────────────────────── tidyverse_conflicts() ──
#> ✖ dplyr::filter() masks stats::filter()
#> ✖ dplyr::lag()    masks stats::lag()
p <- tibble() %>%
  ggplot() + 
  annotate('label', x = 1, y = 0, 
           label='is there a border around this label?', 
           label.size=0)

# In the generated pdf file, there is a black border around the inserted label.
# I don't think that this is the intended behaviour.
ggsave('failure.pdf', p, 
       height = 3, width=7)

# In the generated png file, there is no border around the inserted label.
# I think that this is the intended behaviour.
ggsave('failure.png', p, 
       height = 3, width=7)
```

**Comment by henrikmidtiby** [comment]
Generated png file
![failure](https://user-images.githubusercontent.com/46341/35095999-dc5283f4-fc4a-11e7-96e5-0f5c06824fc7.png)

Genrated pdf file
[failure.pdf](https://github.com/tidyverse/ggplot2/files/1642639/failure.pdf)

**Comment by batpigandme** [comment]
That is strange. For convenience/browsability, here's a picture of what the pdf generates. 

[png of pdf](https://i.imgur.com/NE62SX2.png)

**Comment by hadley** [comment]
Any difference in rendering between graphics devices is unfortunately outside the scope of ggplot2

**Comment by wch** [comment]
This is probably due to a bug in grid's `roundrectGrob`. Here's an example that has a similar problem:

```R
png("test.png")
grid.newpage()
l <- grid.roundrect(width=.5, height=.5,
  gp = gpar(col = "black", fill = "grey90", lwd = 0)
)
grid.draw(l)
dev.off()

pdf("test.pdf")
grid.newpage()
l <- grid.roundrect(width=.5, height=.5,
  gp = gpar(col = "black", fill = "grey90", lwd = 0)
)
grid.draw(l)
dev.off()
```

**Comment by wch** [comment]
Actually, now that I look at this some more, I believe the problem is that PDF renderers often display a hairline for zero-width lines. For example, this has a visible line:

```R
pdf("test.pdf")
plot(cars, type = "l", lwd = 0)
dev.off()
```

The reason that this hasn't been a problem with other geoms is because many of them have a default color of `NA`, which results in no line at all. Here's [GeomRect](https://github.com/tidyverse/ggplot2/blob/bf9255e50cb8333e26133cc81927e5baff986d2a/R/geom-rect.r#L29), and here's [GeomLabel](https://github.com/tidyverse/ggplot2/blob/bf9255e50cb8333e26133cc81927e5baff986d2a/R/geom-label.R#L54).

I suggest changing `GeomLabel` to set the `col` to `NA` when `label.size` is 0.
