### ISSUE TITLE
Passing a function instead of a data frame as data creates a confusing error message

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2417]
Reproducible example:
```r
ggplot(function() {}, aes(x, y)) + geom_point()
#  Error in if (empty(data)) return(cbind(data, PANEL = factor())) : 
#  missing value where TRUE/FALSE needed 
```

This problem can arise, for example, if somebody assigns data to `df` and then mistypes it as `pf`, or if they use `df` without assigning any data to it in the first place.

**Comment by hadley** [comment]
@thomasp85 can you suggest where we should be checking the output of a data function? I've forgotten

**Comment by thomasp85** [comment]
Let me have a look tomorrow and make a PR. My guess is that we should check the return value when getting data from each layer

**Comment by thomasp85** [comment]
Ah - I actually thought it was when passing a function into a geom, but this is when using a function as the global data which was never intended.

Anyway my first assumption led me to think that we should wrap https://github.com/tidyverse/ggplot2/blob/401511e76578e7a35e4a8f9eb9fb68b6d79c95a3/R/layer.r#L184

in a `tryCatch` and give a reasonable error message if it fails...

For the actual reported issue I think it would be best to add a `ggplot.function` method that fails with the relevant error message in order to avoid the `fortify` call in `ggplot.default`

I can make a PR, but you might want to be in control of the wording of the errors, so ping me if you want me to do it...

**Comment by hadley** [comment]
The downside of wrapping in a `tryCatch()` is that you'll lose the full traceback from the original error.

Do you want to have a go a `ggplot.function()`? You can use http://style.tidyverse.org/error-messages.html

**Comment by thomasp85** [comment]
Sure - I’ll give it a go

**Comment by clauswilke** [comment]
I think the most important element for this particular error message will be a good hint, something like: "Did you misspell the name of your data frame?"

**Comment by thomasp85** [comment]
Agreed
