### ISSUE TITLE
Improve fortify error message

### ISSUE THREAD

**Issue by CharlesCara** [tidyverse/ggplot2#2422]
Great campaign on error messages. 

If you run 
`fortify(xtsObject)`
when the xts Package is not loaded you get the error message
`Error: ggplot2 doesn't know how to deal with data of class xts/zoo`
Could you change this to:
`Error: ggplot2 doesn't know how to deal with data of class xts/zoo.  Either the package xts or zoo needs to be loaded.`

**Comment by hadley** [comment]
I think this is out of scope because there's no way in general to know that an object of class "x" is derived from package "y" (and in general simply loading the package won't help). We could add a special case for xts/zoo but this will create a lot of extra work in the long run as other package authors will want similar handling for their package. Finally, this seems like a relatively rare problem because generally it's hard to create zoo/xts objects without loading the relevant package.

**Comment by CharlesCara** [comment]
Yes, see that.  But maybe instead a more generic message such as:
`Error: ggplot2 doesn't know how to deal with data of class XXXXX. Have you loaded the package that defines the class?`

**Comment by hadley** [comment]
That's often not the source of the problem - I think it's typically because there is no ggplot method for that class.
