### ISSUE TITLE
Better drawing of arrows in `geom_path` with `linetype` aesthetic

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/ggplot2#2442]
[Relevant SO post](https://stackoverflow.com/q/48650464/2375551)

Currently, drawing "open" `arrow`s on `path` geometries that use non-solid `linetype`s has poor results, because the open arrow also gets drawn with that linetype specification. It would be great to be able to override the arrow linetype in the call to `arrow`.

Reprex:

```
# data
test = data.frame(x = c(9500, 25500, 47500), y = c(10.03, 7.81, 0.27))
# looks good with solid line
ggplot(test) + aes(x = x, y = y) + geom_path(size = 1, 
  arrow = arrow(type = "open", angle = 30, length = unit(0.1, "inches")))
# not so good with dashed line
ggplot(test) + aes(x = x, y = y) + geom_path(size = 1, linetype ="dashed",
    arrow = arrow(type = "open", angle = 30, length = unit(0.1, "inches")))
```

**Comment by batpigandme** [comment]
Hi @mkoohafkan,

For future reference, using the actual [reprex](http://reprex.tidyverse.org/) package to render a reprex is especially helpful for ggplot2, since it generates and automatically uploads the figures rendered.  I've run your code above through reprex, and, as you can see, it has syntax highlighting and figures.

The tidyverse.org [help page](https://www.tidyverse.org/help/), and the [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful guides.

``` r
library(ggplot2)
# data
test <- data.frame(x = c(9500, 25500, 47500), y = c(10.03, 7.81, 0.27))
# looks good with solid line
ggplot(test) + aes(x = x, y = y) + geom_path(
  size = 1,
  arrow = arrow(type = "open", angle = 30, length = unit(0.1, "inches"))
)
```

![](https://i.imgur.com/7LL8qYf.png)

``` r
# not so good with dashed line
ggplot(test) + aes(x = x, y = y) + geom_path(
  size = 1, linetype = "dashed",
  arrow = arrow(type = "open", angle = 30, length = unit(0.1, "inches"))
)
```

![](https://i.imgur.com/ssQ4qOt.png)

Created on 2018-02-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by karawoo** [comment]
As @joranE commented on the SO question, this behavior is controlled by the grid package. I don't think there's an easy way to fix it in ggplot2 without writing it as a separate geom, unfortunately.

**Comment by mkoohafkan** [comment]
I'm wondering if maybe an arrow glyph can be added for use as with the `lineend` option for `geom_path`. I guess the tricky part is figuring out the angle of the arrow.

**Comment by thomasp85** [comment]
While what you propose is not impossible (I’ve been considering this for some time for ggraph) the lineend parallel doesn’t hold as this is yet another grid feature and not something controlled by ggplot2
