### ISSUE TITLE
ggtitle overwrites subtitle

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#2446]
Not a big deal: ``ggtitle()`` overwrites ``subtitle``

    ggplot(data=mtcars, aes(x=mpg, y=cyl)) + geom_point() + labs(title="title", subtitle="subtitle")
    p = last_plot()
    p + ggtitle("title2")  # overwrites subtitle
    p + labs(title="title2")  # does not overwrite subtitle

Below I tried to use ``reprex(clipr::read_clip())``, but it doesn't seem to work too well...

#> [1] "library(ggplot2)"                                                                                    
#> [2] "ggplot(data=mtcars, aes(x=mpg, y=cyl)) + geom_point() + labs(title=\"title\", subtitle=\"subtitle\")"
#> [3] "p = last_plot()"                                                                                     
#> [4] "p + ggtitle(\"title2\")  # overwrites subtitle"                                                      
#> [5] "p + labs(title=\"title2\")  # does not overwrite subtitle"

**Comment by DarioBoh** [comment]
`ggtitle` default for the argument `subtitle` is `NULL`

**Comment by batpigandme** [comment]
As @DarioBoh mentioned, the default arg in ggtitle for subtitle is NULL (it's even in bold [in the docs](http://ggplot2.tidyverse.org/reference/labs.html) for it 😉). So, you're basically overwriting the whole "title" entity (subtitle absence and all) in the second plot.

``` r
library(ggplot2)
ggplot(data=mtcars, aes(x=mpg, y=cyl)) + geom_point() + labs(title="title", subtitle="subtitle")
```

![](https://i.imgur.com/gVlvL7k.png)

``` r
p <- last_plot()
p + ggtitle("title2")  # overwrites subtitle
```

![](https://i.imgur.com/60eXzhS.png)

``` r
p + ggtitle("title2", subtitle = "subtitle")  # overwrites subtitle
```

![](https://i.imgur.com/RBGbJYT.png)

``` r
p + labs(title="title2")  # does not overwrite subtitle
```
![](https://i.imgur.com/BvdWCe5.png)

Created on 2018-02-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ptoche** [comment]
I may have been misunderstood. I understand the reasons why ``ggtitle()`` overwrites ``subtitle``. I just don't think it's a natural state of affairs and would find it more logical if it didn't. Either ``ggtitle()`` is retired in favour of ``labs()`` or a ``ggsubtitle()`` is added, ensuring that ``ggtitle`` ceases to overwrite the ``subtitle``. 

If the function was named ``ggtitles()`` with an **s**, it wouldn't bother me. 

    ggsubtitle <- function(x) {
        return(labs(subtitle = x))
    }

**Comment by batpigandme** [comment]
I guess the order of operations of having a title and subtitle written using `labs()` and then subsequently adding a `ggtitle()` with _just_ a title (no subtitle) seems like an edge case to me. But, as always n = 1. Changing it to `ggtitles()` would involve deprecating `ggtitle()`, so that's also a downside. 

An easier option would be to clarify what will happen in the docs— though it does already say that the subtitle defaults to NULL.

As you can see below, the layered nature of things means that if you add a subtitle using `labs()` _after_ using `ggtitle()` nothing is overwritten, but, again, that's definitely not how my workflow would go.

``` r
library(ggplot2)
p <- ggplot(data = mtcars, aes(x = mpg, y = cyl)) +
  geom_point()


p + 
  ggtitle("title") + 
  labs(subtitle = "subtitle")
```

![](https://i.imgur.com/y8pcE1o.png)

Created on 2018-02-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
