### ISSUE TITLE
aes_string fails with space in column name

### ISSUE THREAD

**Issue by kent37** [tidyverse/ggplot2#2447]
`aes_string` gives an error when the specified column name contains a space. Here is a simple example with toy data, using ggplot2 2,2.1.900 built 2018-02-02:
```
library(tidyverse)
x=data_frame('Fiscal Year'=2010:2018)

# This is fine
ggplot(x, aes(x=`Fiscal Year`)) + geom_histogram()

# This give an error
ggplot(x, aes_string(x='Fiscal Year')) + geom_histogram()

# Error in parse(text = x) : <text>:1:8: unexpected symbol
# 1: Fiscal Year
#            ^

# aes_string is fine if no space in column name:
x=data_frame('FiscalYear'=2010:2018)
ggplot(x, aes_string(x='FiscalYear')) + geom_histogram()
```

**Comment by batpigandme** [comment]
I'm adding a reprex here so it's easier to see what you're describing. For future reference, using [reprex](http://reprex.tidyverse.org/) to create minimal **rep**roducible **ex**amples is _especially_ helpful with ggplot2, since it generates and includes the figures for you. 

``` r
library(tidyverse)
x=data_frame('Fiscal Year'=2010:2018)
ggplot(x, aes(x=`Fiscal Year`)) + geom_histogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/OrY87Wr.png)

``` r

x=data_frame('FiscalYear'=2010:2018)
ggplot(x, aes_string(x='FiscalYear')) + geom_histogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/HJXLACe.png)

``` r

ggplot(x, aes_string('Fiscal Year') + geom_histogram())
#> Error in parse(text = x): <text>:1:8: unexpected symbol
#> 1: Fiscal Year
#>            ^
```

Created on 2018-02-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by PKI-Kent** [comment]
OK. I actually left the plots out on purpose, the interesting case is the one which fails.

**Comment by hadley** [comment]
This will be fixed by the shift to tidyeval - in the dev version you can do:

```R
var <- sym("Fiscal year")
ggplot(x, aes(!!var) + geom_histogram())
```

**Comment by FAIRLADY111** [comment]
What information can I get from this bar plot..

**Comment by PKI-Kent** [comment]
@FAIRLADY111 none it is a toy example to show a problem.
