### ISSUE TITLE
scale_y_log10 Fails with a Very Large Range

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2454]
The second figure should not fail; log axes should be possible.

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.4.3
ggplot(data.frame(y = c(9.88131291682493e-324, 1000), x = 1:2), aes(x = x, y = y)) + 
  geom_line()
```

![](https://i.imgur.com/ODu0Mu3.png)

``` r
ggplot(data.frame(y = c(9.88131291682493e-324, 1000), x = 1:2), aes(x = x, y = y)) + 
  geom_line() + scale_y_log10()
#> Error in seq.default(min, max, by = by): 'from' must be a finite number
```

![](https://i.imgur.com/x8Yqksh.png)

**Comment by mcol** [comment]
Most of what's going on is within the ScaleContinuous section of scale-.r.

When `transform()` is called on the original example,  the points are 9.881313e-324  1.000000e+03 at entry, and their log10 is computed, turning them into -323.0052    3.0000.

Axis limits are a bit larger than this, becoming (-339.30544, 19.30026), and the call to `self$trans$inverse(limits)` changes it to 0.000000e+00 1.996454e+19. With these values, the call to `self$trans$breaks(limits)` fails because `self$trans$breaks()` needs to compute a log, which produces `-Inf` for 0.

**Comment by thomasp85** [comment]
@Hadley, since this is a matter of `log10_trans()` not handling input gracefully I suggest we move this issue to scales.

There is a larger discussion to be had around scale expansions extending beyond what is meaningful for a scale, but that is slightly orthogonal to this I think (and a huge change)

**Comment by hadley** [comment]
@thomasp85 sounds good to me.
