### ISSUE TITLE
geom_boxplot(outlier.size = NA) doesn't remove outliers after non-ggplot2 updates

### ISSUE THREAD

**Issue by mfoos** [tidyverse/ggplot2#2505]
Hi there, I have a Shiny server on an Amazon Linux EC2 (but this is also happening with slightly different specs on a Mac) and a coworker updated a smattering of R packages, and now ggplots that have worked (in Shiny) for years are no longer giving the expected output.

I usually overlay geom_point() with a jitter over geom_boxplot() and then hide the outliers so those points do not appear twice (the jitter means you can see both). Setting outlier.size = NA used to make them invisible, but since the update of doom, they still appear (and, oddly, larger than the points from geom_point). If I switch to outlier.size = NULL, they become very small but remain.

Unfortunately, and I apologize for nonetheless posting it here, it does not seem linked to an update of ggplot2 - I can run v2.2.1 under R 3.3.0 and not have this problem. I am posting it under ggplot2 because I can't locate the source.

``` r
library(tidyr)                                                                  
library(ggplot2)                                                                
                                                                                
set.seed(5)                                                                     
sample <- data.frame("id" = 1:100,                                              
"x" = runif(100, 5, 10),                                                        
"y" = rnorm(100, mean = 7),                                                     
"group" = sample(c("A", "B"), 100, replace = TRUE)) %>% gather(key, value, x, y)
                                                                                
ggplot(sample, aes(x = key, y = value)) +                                       
geom_boxplot(outlier.size = NA) +                                               
geom_point()                                                                    
```

![](https://i.imgur.com/2nUo4F7.png)

``` r
                                                                                
sessionInfo()                                                                   
#> R version 3.4.1 (2017-06-30)
#> Platform: x86_64-redhat-linux-gnu (64-bit)
#> Running under: Amazon Linux AMI 2017.09
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ggplot2_2.2.1 tidyr_0.8.0  
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.15     knitr_1.20       magrittr_1.5     tidyselect_0.2.4
#>  [5] munsell_0.4.3    colorspace_1.3-2 rlang_0.2.0      stringr_1.2.0   
#>  [9] plyr_1.8.4       tools_3.4.1      grid_3.4.1       gtable_0.2.0    
#> [13] htmltools_0.3.6  lazyeval_0.2.0   yaml_2.1.14      rprojroot_1.2   
#> [17] digest_0.6.12    tibble_1.4.2     purrr_0.2.4      glue_1.2.0      
#> [21] evaluate_0.10    rmarkdown_1.9    labeling_0.3     stringi_1.1.3   
#> [25] compiler_3.4.1   pillar_1.2.1     scales_0.4.1     backports_1.1.0
```

**Comment by batpigandme** [comment]
Hi Marianna,

Do you have a pic of how this comes out for you on 3.3.0, or is that gone? If the latter, nbd, but thought I'd ask.

**Comment by mfoos** [comment]
![Sorry no reprex, Pandoc drama](https://user-images.githubusercontent.com/3073958/38102207-956b1cac-3350-11e8-9aa0-7c1942726ee5.png)

**Comment by ptoche** [comment]
Here's the reprex of the OP, in case it's needed:

``` r
library(tidyr)                                                                  
library(ggplot2)                                                                

set.seed(5)                                                                     
sample <- data.frame("id" = 1:100,                                              
                     "x" = runif(100, 5, 10),                                                        
                     "y" = rnorm(100, mean = 7),                                                     
                     "group" = sample(c("A", "B"), 100, replace = TRUE)) %>% gather(key, value, x, y)

ggplot(sample, aes(x = key, y = value)) +                                       
    geom_boxplot(outlier.size = NA) +                                               
    geom_point() 
```

![](https://i.imgur.com/3o9aYO6.png)

Created on 2018-04-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ptoche** [comment]
The point sizes I observe can ranked from lowest to highest as follows:

    'outlier.size = 0'   < 'outlier.size = NULL'  <  'outlier.size = NA' 

You can get rid of them (in this example at least for me) with 

    'outlier.size=-1' 

or some other negative number. Looking at the code now, if I see something I'll post back.

**Comment by ptoche** [comment]
An example of ``outlier.size = 0`` in the ``position-jitterdodge.r`` code, **lines 15-17**, suggests to me that the problem is a regression bug (assuming the example was tested and had the expected output at the time). Below a reprex() using that example.

``` r
library(ggplot2)
set.seed(3)
dsub <- diamonds[ sample(nrow(diamonds), 1000), ]
ggplot(dsub, aes(x = cut, y = carat, fill = clarity)) +
    geom_boxplot(outlier.size=0) 
```

![](https://i.imgur.com/opAkD9M.png)

``` r
set.seed(3)
dsub <- diamonds[ sample(nrow(diamonds), 1000), ]
ggplot(dsub, aes(x = cut, y = carat, fill = clarity)) +
    geom_boxplot(outlier.size=-1) 
```

![](https://i.imgur.com/ng2tKlb.png)

Created on 2018-04-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


Two different ``fill = `` statements are repeated on lines 225 and 229 of ``geom-boxplot.r``, which I imagine is not intended, but this does not appear to be related to the current issue. 

My progress was hindered by my inability to understand how to hack the ``geom_boxplot()`` function (I was able to stick several ``ggplot2:::`` here and there to make the functions available, but couldn't get the pipe operator ``%||%`` to be understood, after trying to load ``tidyverse``, ``magrittr`` and ``dplyr``, so I gave up rather early in my quest).

**Comment by ptoche** [comment]
Inspecting the screenshot from [this question](https://stackoverflow.com/questions/25124895/no-outliers-in-ggplot-boxplot-with-facet-wrap) and comparing it to the plots below confirms beyond a reasonable doubt that this is a regression bug.

**WAS:**
![](https://i.stack.imgur.com/vGzZB.png)

**HAS BECOME:**

``` r
library(ggplot2)
ggplot(diamonds, aes(x=cut, y=price, fill=cut)) +
    geom_boxplot(outlier.size=NA) + facet_wrap(~clarity, scales="free")
```

![](https://i.imgur.com/WnWpVR5.png)

Created on 2018-04-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ptoche** [comment]
Problem exists as far back as version ``2.0.0.`` I didn't manage to install earlier version to check.

**Comment by karawoo** [comment]
Thanks for looking into this @ptoche. The `NA` behavior is being controlled by grid. Outliers in ggplot2 are created with `geom_point()`, which creates a `pointsGrob()`. Here is how `pointsGrob()` appears with settings that match what's being used for the outliers if `outlier.size = NA`:

``` r
library(grid)

grid.newpage()

pt <- pointsGrob(
  x = unit(0.5, "npc"), # place a point in the center of the viewport
  y = unit(0.5, "npc"),
  pch = 19,             # default pch for geom_point()
  gp = gpar(fontsize = NA)
)

grid.draw(pt)
```

![](https://i.imgur.com/hKxGbMO.png)

Created on 2018-04-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

So to work around this would require 1) writing some special logic to handle NAs specifically, and 2) overriding the standard behavior of grid.

This also led me to wonder why `outlier.size = 0` does not remove outliers. Turns out the default value for `stroke` (0.5) is getting factored into the [size calculation](https://github.com/tidyverse/ggplot2/blob/master/R/geom-point.r#L138), even though `pch = 19` has no stroke.

**Comment by ptoche** [comment]
Thanks Kara. I see it now. Incidentally, do you have tips (a url will be enough) on how to hack a function like ``geom_boxplot()`` for the purpose of testing. It used to be enough to copy the code and prefix functions with their package names (such as ``scales:::``), but it seems harder now. For instance, how do I get this pipe operator ``%||%`` to be understood after I copy the function code? Thanks!

**Comment by hadley** [comment]
I think this is probably a bug in grid.

**Comment by karawoo** [comment]
@ptoche I clone the project locally and run `devtools::load_all()`

**Comment by hadley** [comment]
Equally, it might be worth having an `outliers = FALSE` argument to provide an official way to suppress outliers, since it does seem to be a common need.

**Comment by hadley** [comment]
I checked with Paul - this is not a great feature, but it is by design, so ggplot2 probably should work around it.

**Comment by clauswilke** [comment]
I agree that having an `outliers = FALSE` argument might be useful, simply for its visibility, though I'd like to point out that `outlier.colour = "transparent"` does the same trick. Maybe it would be sufficient to just add that to the docs somewhere? See also https://github.com/tidyverse/ggplot2/issues/2583#issuecomment-391214863.

**Comment by ptoche** [comment]
One would expect ``outliers = FALSE`` to discard the data and recompute the axis limits, something that ``outlier.colour = "transparent"`` wouldn't be expected to do, right?

**Comment by karawoo** [comment]
I think a lot of people would expect that, yeah, and that behavior was decided against in #2026. Maybe `hide_outliers = TRUE`?

**Comment by ptoche** [comment]
``outlier.shape = NA``, ``outlier.colour = NA``, ``outlier.colour = "transparent"``, ``outlier.shape = ""``, ``outlier.size = -1`` appear to give similar output. Something like the output below.

Could an ``outliers = FALSE`` be part of the ``scales`` package instead of ``ggplot2``, since  it would involve a recomputation of the scales?

``` r
library(ggplot2)
mtcars$mpg[1] <- 100
ggplot(mtcars, aes(factor(cyl), mpg)) + 
        geom_boxplot(outlier.shape = NA)
```

![](https://i.imgur.com/xZAWYuC.png)

Created on 2018-05-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
`outlier.shape = ""` will not work in ggplot2 2.3.0. (But `outlier.shape = " "` does work.) This may be an unintended consequence of this merge: https://github.com/tidyverse/ggplot2/pull/2338

``` r
library(ggplot2)
ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot(outlier.shape = "")
#> Error: Shape names must be unambiguous:
#> * '' partially matches 27 shape names
```
Created on 2018-05-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
