### ISSUE TITLE
Resolve raster::calc + ggplot2::calc clash

### ISSUE THREAD

**Issue by karawoo** [tidyverse/ggplot2#2614]
Decide how to proceed based on responses to [Hadley's tweet](https://twitter.com/hadleywickham/status/996430251499536385)

**Comment by clauswilke** [comment]
I'd be in favor of renaming if a good alternative can be found, because I find `calc()` not that informative. What is it calculating? From where? I like things to be more explicit, such as `calc_from_stat()`, but that's long. The best thing I could think of is `stat()`, which I don't think conflicts with anything.

So something like this:
```{r}
ggplot(iris, aes(Sepal.Length, y = 1, fill = calc(density))) + geom_tile(stat = "density")
```
would become this:
```{r}
ggplot(iris, aes(Sepal.Length, y = 1, fill = stat(density))) + geom_tile(stat = "density")
```
The downside is that "stat" is not a verb.

**Comment by hadley** [comment]
Ooh I like `stat()` a lot better.  I'll work on this STAT 😉

**Comment by hadley** [comment]
Or if someone else had time, this should be a fairly simple PR. (I'm teaching a workshop Thursday & Friday)

**Comment by karawoo** [comment]
@hadley I can do it this evening, is that too late?

**Comment by hadley** [comment]
That would be perfect
