### ISSUE TITLE
Error: `data` must be uniquely named but has duplicate elements

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2641]
We need a simple reprex for this just to double check it's revealing real problems. Looks like ggforce might be simplest?

**Comment by hadley** [comment]
I thought it might be related to using same facet name as aesthetic, but that doesn't appear to be the case:

``` r
library(ggplot2)
df <- data.frame(x = 1:3, colour = c("red", "blue", "red"))

ggplot(df, aes(x, x, colour = colour)) + 
  geom_point() + 
  facet_wrap(~ colour)
```

![](https://i.imgur.com/Uozy8kq.png)

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by karawoo** [comment]
Whatever it is it's already fixed in the dev version of ggforce. I looked at svdvis and there they're passing a data frame that has two different columns called `group` to `geom_point()`. Here's a reprex:

``` r

library("ggplot2")
df <- data.frame(x = 1:3, group = 1:3, group = 1:3)
names(df) <- c("x", "group", "group")

ggplot(df, aes(x, x)) +
  geom_point()
#> Error: `data` must be uniquely named but has duplicate columns
```

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

In preparing data for plotting sometimes ggplot creates a `group` column. I have some suspicion that two columns called `group` got created somehow in the ggforce example, but I haven't been able to reprexify.

**Comment by Sultan91** [comment]
The problem still persist, is there any solution?
