### ISSUE TITLE
propose new ggplot version be released as 3.0 rather than 2.3.0

### ISSUE THREAD

**Issue by dpastoor** [tidyverse/ggplot2#2648]
I'd like to propose incrementing the ggplot2 version number to 3.0 rather than 2.3.0. Though semantic versioning is not "officially" followed, it does provide a helpful facility for communication, especially after the 1.0 release. 

Given the extent of the internal refactor to rlang+other changes, it is clear that there are breaking changes. I applaud the team for such diligent engagement with the community, however it still provides a breakdown with respect to the objective of semantic versioning.

As an acedote on where this has an effect, in working with a number of pharmaceutical companies, many SOP's revolve around identifying risks associated with package upgrades. While semantic versioning is not relied on in isolation, the more it is followed, the easier it is to demonstrate that strategies around risk identification (eg assessing if it was a major vs minor change as noted by semantic versioning is one criteria) are robust.

I appreciate these problems are not yours/the OS community directly, however getting buy-in for R as a production-ready language has been an uphill battle, and small differences like this make a world of difference towards the adoption of R in enterprise settings. 

In addition, I see the Rstudio team as championing "best practices", with most developers try to emulate the processes established. In this case, following semantic versioning, especially past 1.0 provides a helpful mechanism of communication that spans many languages.

**Comment by clauswilke** [comment]
It depends on whether we allow breaking changes with minor version increases or not. If any breaking changes are allowed at all with a minor version increases, then I think this is 2.3.0, because the vast majority of code will work just fine. Most breaking changes in this release relate to things that were already bad practice, such as having two data columns with the same name. While there are a ton of new features, they don't actually introduce API changes, just an expanded API.

The reasons why I'd be hesitant to call this 3.0 is that at some point much of the core code related to layers might have to be changed or refactored to introduce more flexibility, and that would certainly create many more breaking changes (similar to the move from 1.X to 2.0), and which version number would we change then? ggplot2 -> ggplot3?

My proposal would be:

- new patch number: absolutely no breaking changes, only bug fixes and new features that don't break anything
- new minor version number: breaking changes are kept to a minimum, the vast majority of code will work without problems
- new major version number: more substantial changes, including obvious user-facing changes

**Comment by dpastoor** [comment]
The problem with "kept at a minimum" is ambiguous. Likewise patch versions are really for just that - fixes or refactoring. Additions still warrant minor bumps. There's nothing stopping versions at single digits.

Again this is based around following semantic versioning. If there is no interest in following that then the discussion is somewhat moot. To me version number should be seen as a form if concise communication that follows a pattern as unambiguous as possible. There is no reason not to have ggplot v20.0, if there were enough situations that brought on those api breakages. In user land it might feel safer thinking oh an upgrade to 2.3 sounds simpler than going to 3.0, but that is a false sense of security. The edge cases will break whether this is called 2.3 or 3.0 or 99.0, the difference is how simply it can be interpretted. 

This is something that a lot of other communities are pushing ahead with, you're seeing version 15+ of packages over time. Did those communities just start breaking everything all of a sudden? No, they just started more strictly following semantic versioning conventions.

**Comment by hadley** [comment]
I don't find semantic versioning particularly useful because it doesn't precisely define what a breaking change is, or even exactly what an API is (this is particularly tricky for ggplot2 which does not have a clear specification of behaviour independent on the current independent). Additionally, the way in which versions are specified in R packages are very different to other programming languages, and R users tend to be very different to programmers of other languages. Overall, I think that means that burden of proof lies on you to show that semantic versioning is useful for R.

Additionally, as @clauswilke mentions, this version of ggplot2 breaks developer code, but shouldn't affect (much) user code (there are inevitably some changes because people previously depended on things that we consider to be bugs. 

That said, bumping a major version instead of a minor version is not hard, and the use of tidy eval is a major change.

**Comment by dpastoor** [comment]
Thanks. To your question about breaking change - my understanding, per https://semver.org/ is that the public api denotes the interface at which the communication hinges upon, so to me this is any exported function, method, etc.

 I also agree that R sits in an interesting space with the combination of interactive utilization + more and more software engineering making it harder to reason about what makes the most sense. 

All said, I look forward to the release and will follow along and (personally) cross my fingers that a bump to 3.0 stays in discussion.

**Comment by hadley** [comment]
I have decided to make it a 3.0.0 release. While the introduction of tidy eval should affect very little user code, it does affect quite a few package developers.
