### ISSUE TITLE
Unexpected behavior in element_text() horizontal justification

### ISSUE THREAD

**Issue by zlskidmore** [tidyverse/ggplot2#2653]
In the upcoming release of ggplot2 (2.3.0) the behavior of element_text() has changed. Specifically it looks like the justification anchors have changed in relation to the text. For Example:

In the current release:
![ggplot_2 2 1](https://user-images.githubusercontent.com/6145692/40440459-bdd8d95a-5e83-11e8-8ea7-0c9cb3b00cfb.png)

In the development version:
![ggplot2_2 3 0](https://user-images.githubusercontent.com/6145692/40440467-c8ecf876-5e83-11e8-9b1b-91ccbeabdb53.png)

```r
mtcars$name <- rownames(mtcars)

ggplot(mtcars, aes(x=name, y=carb)) + geom_bar(stat="identity") + theme(axis.text.x=element_text(angle=60, hjust=1))
```

**Comment by karawoo** [comment]
Thanks for reporting this. I believe this bug is due to the change in how `xp` and `yp` are calculated in #2577.

**Comment by karawoo** [comment]
@hadley @clauswilke I think we should revert [this change](https://github.com/tidyverse/ggplot2/pull/2577/commits/963b551a3d23198163a910ca8a9b169dbf0a2a36), it's going to break a lot of users' plots.

**Comment by clauswilke** [comment]
@karawoo I'll look into it. However, I'm not yet convinced about the cause of this problem, because I checked for this particular issue when I made the patch, if I remember correctly. I think this has actually to do with changed grob heights due to fixed descenders.

A workaround exists, but I agree it's not intuitive (why `vjust = 0.65`?)
``` r
library(ggplot2)
mtcars$name <- rownames(mtcars)

ggplot(mtcars, aes(x=name, y=carb)) + 
  geom_bar(stat="identity") + theme(axis.text.x=element_text(angle=60, hjust=1, vjust = 0.65))
```

![](https://i.imgur.com/cp3dRcC.png)

Created on 2018-05-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
When looking at this in debug mode, we see that for axis tick labels along the x axis the reference point travels vertically for different `vjust` values rather than orthogonally to the direction of the text. As far as I recall, this behavior is identical to the currently released ggplot2 version, but it's different from the behavior for `hjust` (which is along the text direction) and it's also different from `hjust` and `vjust` for axis titles, legend text and titles, and so on.

``` r
library(ggplot2)
mtcars$name <- rownames(mtcars)

ggplot(mtcars, aes(x=name, y=carb)) + 
  geom_bar(stat="identity") + 
  theme(axis.text.x=element_text(angle=60, hjust=1, vjust = 0, debug = TRUE))
```

![](https://i.imgur.com/v2CDa9v.png)

``` r

ggplot(mtcars, aes(x=name, y=carb)) + 
  geom_bar(stat="identity") + 
  theme(axis.text.x=element_text(angle=60, hjust=1, vjust = 0.5, debug = TRUE))
```

![](https://i.imgur.com/ewa3zgR.png)

``` r

ggplot(mtcars, aes(x=name, y=carb)) + 
  geom_bar(stat="identity") + 
  theme(axis.text.x=element_text(angle=60, hjust=1, vjust = 1, debug = TRUE))
```

![](https://i.imgur.com/z3sODyl.png)

There are two possible alternative ways to fix this:

- Make the reference point travel inside the range indicated by the colored square, so that `vjust = 0` indicates the bottom of the square and `vjust = 1` indicates the top.

- Make the reference point travel orthogonally to the text direction at all times.

**Comment by clauswilke** [comment]
I've been pondering this issue the whole afternoon and I'm not sure how to fix this. (We can revert, of course.) The bigger problem I'm seeing is that we are using two different justification systems throughout ggplot, and things break one way or another when we mix them (as is the case for axis tick labels): One system uses a fixed reference point and moves the text relative to that point. E.g., `hjust = 0` means the entire string is to the left of that point, and `hjust = 1` means the entire string is to the right. The other system uses a fixed extent and moves the string inside that extent. E.g., `hjust = 0` means the string is at the left boundary of that extent, and `hjust = 1` means it's on the right boundary. For x axis tick labels, we want the first justification system along the x axis and the second orthogonal to the x axis. But we also want to use `hjust` and `vjust` in the internal coordinate system of the text label, so that `hjust = 1` right-justifies all the text labels regardless of angle. I haven't yet found a way bring all these conflicting constraints into one consistent framework that makes sense at all angles.

I just created a PR that reverts to the previous model specifically when the justification model is mixed: https://github.com/tidyverse/ggplot2/pull/2654

With this PR:
``` r
library(ggplot2)
mtcars$name <- rownames(mtcars)

ggplot(mtcars, aes(x=name, y=carb)) + 
  geom_bar(stat="identity") + theme(axis.text.x=element_text(angle=60, hjust=1))
```

![](https://i.imgur.com/2zYJuct.png)

Created on 2018-05-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
