### ISSUE TITLE
Facet + axis labels

### ISSUE THREAD

**Issue by ldecicco-USGS** [tidyverse/ggplot2#2656]
This could easily be "won't fix" and I totally understand, but I was wondering if this is the expected behavior:

```r
library(ggplot2)
library(dplyr)

starwars <- starwars %>%
  filter(homeworld %in% c("Tatooine","Naboo","Alderaan"),
         eye_color %in% c("blue","brown","hazel")) %>%
  mutate(skin_color = factor(skin_color))

colors <- ifelse(levels(starwars$skin_color) == "fair","red","black")

ggplot(data=starwars) +
  geom_tile(aes(x=name, y=skin_color, fill = mass)) +
  theme_bw() +
  facet_grid(eye_color ~ homeworld, 
             scales="free", space="free") +
  theme(axis.text.x = element_text( angle = 90,vjust=0.5,hjust = 1),
        axis.text.y = element_text(color = colors)) 
```
![image](https://user-images.githubusercontent.com/1105215/40515485-9f35d7c4-5f72-11e8-83ef-803c2d500033.png)

I would like to see the `skin_color` "fair" label red and the rest black. I see what's happening: for each `eye_color`, it uses the vector c("black","red","black","black").

But...I have not figured out a way to say for "brown" `eye_color`, use c("black","red","black","black"), but for "blue" `eye_color`, use c("red","black").

**Comment by clauswilke** [comment]
This trick of coloring axis tick labels is floating around on stackoverflow, and I've used it myself, but it's an accident that it works I think. Technically, the reason that it works is that all the axis tick labels are generated as one single grob. If instead each were its separate grob this wouldn't work. In fact, if you try the same on a legend generated with `guide_legend()` (not `guide_colorbar()`) you'll see that it doesn't work there, because there all the labels are generated as individual grobs.

I think there should be an API to color individual tick labels, but it'll require significant rethinking of how text is rendered and styled in ggplot2. This won't be a simple fix.

**Comment by ldecicco-USGS** [comment]
Thanks for the explanation! I did see the stackoverflow post:
https://stackoverflow.com/questions/45843759/ggplot2-coloring-axis-text-on-a-faceted-plot
(very schnazzy!)
So as near as I can tell, this is the current solution:
```r
starwars <- starwars %>%
  filter(homeworld %in% c("Tatooine","Naboo","Alderaan"),
         eye_color %in% c("blue","brown","hazel")) %>%
  mutate(skin_color = factor(skin_color))

color_df <- data.frame(skin_color = c("dark","fair","light","tan","fair","light"),
                       homeworld = rep("Alderaan",6),
                       eye_color = c(rep("brown",4),rep("blue",2)),
                       color = c("black","red","black","black","red","black"))

ggplot(data=starwars) +
  geom_tile(aes(x=name, y=skin_color, fill = mass)) +
  theme_bw() +
  facet_grid(eye_color ~ homeworld, 
             scales="free", space="free") +
  theme(axis.text.x = element_text( angle = 90,vjust=0.5,hjust = 1)) +
  expand_limits(x = -1, data = data.frame(homeworld = "Alderaan")) +
  geom_rect(data = data.frame(homeworld = "Alderaan") ,
            ymin = 0, ymax = length(unique(starwars$skin_color))+1, 
            xmin = -1, xmax = 0, fill = "white") +
  # # # fake axis layer, aligned below y = 0
  geom_text(data = color_df, 
            aes(color = color, label = skin_color, y=skin_color), x = 0, 
            hjust = 1, vjust = 0.25) +
  # # # # specify the font colours for fake axis
  scale_colour_manual(values = c("black", "red"), guide = F) +
  # # # hide the actual x-axis text / ticks
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
``` 
which gives:
![image](https://user-images.githubusercontent.com/1105215/40526038-760ce158-5fa9-11e8-833a-9293253c97a7.png)

Not terrible, but it would be nice if Alderaan wasn't stretched out. 

Anyway, I agree that it would be cool if there was individual color label API...maybe someday.

**Comment by clauswilke** [comment]
The about-to-be-released ggplot 2.3.0 allows you to draw outside the plot area by switching off clipping. So the following might be a viable workaround for now. It requires a bit of fiddling with the `x` coordinate of the text relative to the overall width of the plot, but otherwise it works.

```{r}
library(ggplot2)
library(dplyr)

starwars <- starwars %>%
  filter(homeworld %in% c("Tatooine","Naboo","Alderaan"),
         eye_color %in% c("blue","brown","hazel")) %>%
  mutate(skin_color = factor(skin_color))

color_df <- data.frame(skin_color = c("dark","fair","light","tan","fair","light"),
                       homeworld = rep("Alderaan",6),
                       eye_color = c(rep("brown",4),rep("blue",2)),
                       color = c("black","red","black","black","red","black"))

ggplot(data=starwars) +
  geom_tile(aes(x=name, y=skin_color, fill = mass)) +
  theme_bw() +
  facet_grid(eye_color ~ homeworld, 
             scales="free", space="free") +
  theme(axis.text.x = element_text( angle = 90,vjust=0.5,hjust = 1)) +
  geom_rect(data = data.frame(homeworld = "Alderaan") ,
            ymin = 0, ymax = length(unique(starwars$skin_color))+1, 
            xmin = -1, xmax = 0, fill = "white") +
  # # # fake axis layer, aligned below y = 0
  geom_text(data = color_df, 
            aes(color = color, label = skin_color, y=skin_color), x = 0.2,
            size = 0.8*11/.pt, # match font size to theme
            hjust = 1, vjust = 0.5) +
  # switch off clipping
  coord_cartesian(clip = "off") +
  # # # # specify the font colours for fake axis
  scale_colour_manual(values = c("black", "red"), guide = F) +
  # # # hide the actual x-axis text
  theme(axis.text.y = element_blank(),
        axis.title.y = element_text(margin = margin(r = 25)))
```

<img width="845" alt="screen shot 2018-05-24 at 11 55 16 pm" src="https://user-images.githubusercontent.com/4210929/40526750-2a604d62-5fae-11e8-9464-85b258dd282c.png">

**Comment by clauswilke** [comment]
I'm going to close the issue because I don't think there's any concrete action to be taken at this time.

**Comment by ldecicco-USGS** [comment]
Gah, how could I forget my favorite new upgrade! Thanks so much for the help.

**Comment by hadley** [comment]
I can now image how this _might_ work: you could provide a data frame to `labels`, where the columns were aesthetics.

**Comment by clauswilke** [comment]
@hadley I'd like to propose a completely different perspective: What if formatting code could travel with the text labels, so we could specify in the label itself what color (for example) it should have? This would solve all sorts of formatting problems that people run into all the time.

I think the correct framework is to think of html/css, and to implement some subset of these languages that covers the most common formatting needs. Over time, support could be expanded, and eventually most of the theming could be handled via style sheets rather than via arguments to `element_text()`, `element_rect()`, etc.

I've played around with this idea for a few days now, and I think it's viable. I'm only at the proof-of-concept stage, but I see now major stumbling blocks. My current code is [here](https://github.com/clauswilke/gridtext) and an example follows.

``` r
library(grid)
library(gridtext)
text1 <- "<span style='font-family:\"Comic Sans MS\"; font-size:20; color:orange'>Comic Sans! Yay!</span>"
text2 <- "Some <span style='color:red'>red</span> text <b>in bold.</b><br>And <i>more</i> text.<br>And some <span style='font-size:18'>large</span> text."
text3 <- "5<i>x</i><sup>2</sup><span style='color:blue'> + 7<i>x</i></span> - <i>α<sub>i</sub></i>"

grid.newpage()
grid.draw(rich_text_grob(text1, x = 0.25, y = 0.9))
grid.draw(rich_text_grob(text2, x = 0.3, y = 0.3, hjust = 0, angle = 45))
grid.draw(rich_text_grob(text2, x = 0.8, y = 0.7, hjust = 1, angle = -90))
grid.draw(rich_text_grob(text3, x = 0.1, y = 0.1))
```

![](https://i.imgur.com/n3FLmG7.png)

Created on 2018-05-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Hmmm, interesting idea. My approach feels more “tidy” but is obviously limited compared to inline styles. I don’t any strong objections to your approach except for a vague feeling that ggplot2 might be nicer on the whole if it exposed/required more tidy data frames for internals (dplyr is also moving in this direction)

**Comment by clauswilke** [comment]
Most importantly, these ideas are not mutually exclusive. I'd like to have the option for inline styling, but the default styling for a given element could be generated in all sorts of ways.

Also, I agree with your perspective of using tidy data frames. I found for this project that assembling all the individual pieces [in a table](https://github.com/clauswilke/gridtext/blob/master/R/make-.R) that then gets [rendered at once](https://github.com/clauswilke/gridtext/blob/master/R/render-lines.R) makes the most sense and keeps the code complexity low.
