### ISSUE TITLE
Not all items in the list aes() produces are quosures

### ISSUE THREAD

**Issue by rpruim** [tidyverse/ggplot2#2676]
https://github.com/tidyverse/ggplot2/blob/master/NEWS.md#ggplot2-2219000 claims 

> The primary developer facing change is that aes() is now a list of quosures (expression + environment pairs) rather than a list of symbols, and you'll need to take a different approach to extracting the information you need.

But not all elements are quosures:

```r
aes(x = foo, y = 0) %>% str()
## List of 2
##  $ x: language ~foo
##   ..- attr(*, ".Environment")=<environment: R_GlobalEnv> 
##  $ y: num 0
##  - attr(*, "class")= chr "uneval"
aes(x = foo, y = 0) %>% lapply(class)
## $x
## [1] "quosure" "formula"
## 
## $y
## [1] "numeric"
## 
aes(x = foo, y = 0) %>% lapply(function(x) inherits(x, "quosure"))
## $x
## [1] TRUE
## 
## $y
## [1] FALSE
```

**Comment by yutannihilation** [comment]
It seems this is the intended behaviour as the code introduced by https://github.com/tidyverse/ggplot2/commit/1f39e138391259ebef95e35e39fa1d3579f1984c says:

https://github.com/tidyverse/ggplot2/blob/0c7eda0af0723b3d0856fe012c393515a51c51bf/R/aes.r#L100-L101

This seems somehow consistent with the behaviour of the CRAN version where constants are not quoted (because simply they cannot be quoted (e.g. `quote(1)` returns `1`)):

``` r
aes(x = foo, y = 0) %>% str()
#> List of 2
#>  $ x: symbol foo
#>  $ y: num 0
```

That said, I too feel the NEWS may be misleading a bit...
