### ISSUE TITLE
Match error formatting to style guide?

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/ggplot2#2717]
Moving from https://github.com/tidyverse/style/issues/80#issuecomment-388809007

(@hadley I think the new error message is actually more informative, but maybe a reordering of statements is in order?)

```r
ggplot2::ggplot(ggplot2::aes())
#> Error: Can't plot data with class "uneval". 
#> Did you accidentally provide the results of aes() to the `data` argument?
```

``` r
ggplot2::ggplot(ggplot2::aes())
#> Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class uneval
#> Did you accidentally pass `aes()` to the `data` argument?
```
Created on 2018-05-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by dpseidel** [comment]
@batpigandme So I’m admit I’m still bit puzzled 🤔 — is the desired solution to this issue to match the current error to the example in the style guide or to *conform* to the style guide? 

If matching the examples in the style guide is the goal, I think it’s best to make the change there, because the old error message is inferior according to style guide best practices. 

Assuming we want to improve the current error to better conform to the style guide, although I could trivially switch the statement order, IMO giving the hint before the error is inconsistent with other tidyverse error styling.  The real issue is that this is a fairly long error message, at least in part because the object specification is long. At least aspirationally, the style guide specifies that error messages be less than 80 characters wide and manual line breaks are discouraged. 

The simplest thing to do is to drop the object specification:
```r
fortify(aes())
#> Error: `data` must be a data frame, or other object coercible by `fortify()`.
#> Did you accidentally pass `aes()` to the `data` argument?
```

Slightly less informative but still “tidy”. If you agree I’ll create a PR right away.  If we don’t want to lose info, I could also consider adding a second complete line,  

```r
fortify(aes())
#> Error: `data` must be a data frame, or other object coercible by `fortify()`.
#> Can’t fortify an S3 object with class uneval.
#> Did you accidentally pass `aes()` to the `data` argument?
```

Or, using a bullet, albeit slightly unconventionally:

```r
fortify(aes())
#> Error: `data` must be a data frame, or other object coercible by `fortify()`.
#> * `data` given is an S3 object with class uneval.
#> Did you accidentally pass `aes()` to the `data` argument?
```

Preference?

**Comment by batpigandme** [comment]
I like the first one best, but (IIRC) this issue was the result of Hadley having me go through the error section of the style guide and making sure they matched. So, if as is is better, we can definitely just mod the style guide.

**Comment by dpseidel** [comment]
I think the first is most in line with current best practices anyhow. I'll make the PR and then you or I can submit a separate change to the style guide.

**Comment by dpseidel** [comment]
Alright I'm going to close this, since we opted to stay with the current error message. The style guide will need to be updated to match -- let me know if you want me to open a new issue or PR in tidyverse/style.

**Comment by batpigandme** [comment]
Word. I did a PR in the style guide. The only thing I added manually was a period at the end of the statement

**Comment by dpseidel** [comment]
Oh yeah, it is missing that.  I've been making notes of error messages that need some help when I have encountered them (e.g. the hint along with `ggplot.default` is missing a question mark), so I'll make a PR with some of these minor changes eventually.
