### ISSUE TITLE
Strip placement default should be at left and outside of axis

### ISSUE THREAD

**Issue by bpbraun** [tidyverse/ggplot2#2762]
As we read English/other European languages from left to right, it makes more intuitive sense for the strip placements on the y axis of a facet grid/wrap to be placed on the left side.  Furthermore, this should automatically be placed outside the axis. 

Right now, this is what you have to do to achieve what I believe should be the default:

```r
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
 geom_point() +
 facet_Grid(Species ~ ., switch = "y") +
 theme(strip.placement = "outside")
```

**Comment by batpigandme** [comment]
I think having the numbers between the strip labels and the actual chart seems quite unnatural left-to-right, give the 90° switch in orientation. Personally, I wouldn't gravitate toward the second figure either, since (again) our heads aren't oriented that way.

The design decision not being mine, others will of course weigh in. But, I wanted to show you a few other options that might suit your needs with more parsimonious code (if that's your concern).

``` r
library(ggplot2)
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  facet_grid(Species ~ ., switch = "y") +
  theme(strip.placement = "outside")
```

![](https://i.imgur.com/hwWJzH4.png)

``` r

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  facet_grid(vars(Species))
```

![](https://i.imgur.com/veyGQeP.png)

``` r

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  facet_wrap(vars(Species), nrow = 3)
```

![](https://i.imgur.com/bbeYF6R.png)

``` r

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  facet_grid(cols = vars(Species))
```

![](https://i.imgur.com/ZCpKhBN.png)

Created on 2018-07-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by baptiste** [comment]
There might be an argument for `switch` to become part of the theme definition? This way it would be easy for anyone to define their preferred theme.

**Comment by ptoche** [comment]
Related: https://github.com/tidyverse/ggplot2/issues/2513

**Comment by Eluvias** [comment]
The answer on `strip.placement` position was given by @thomasp85 in #1818 .

>  I don't think the theme should depend on plot settings. The rationale for putting it in theme is that for solid strips (e.g. theme_grey) it looks best with the strip in between the axis and panel, while for strips with no background the reverse is true...

**Comment by hadley** [comment]
Regardless of the arguments, it's too late to change this default.

**Comment by baptiste** [comment]
Not sure I understand - the work in progress idea of having default geom
aes in the theme would seem a good opportunity to consider adding this
setting as well in future theme defs. The default behaviour wouldn't have
to change.
