### ISSUE TITLE
preserve = "single" breaks violin plots

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#2801]
I'm trying to use preserve = "single" as you would with boxplots to maintain the sizes of the boxes when there are unused factors. While I figured it would work just the same way for violin plots, it appears to completely break them.

```r
p <- ggplot(mtcars, aes(factor(cyl), mpg))
#works fine
p + geom_violin(aes(fill = factor(vs)))
#works fine
p + geom_violin(aes(fill = factor(vs)), position = "dodge")
#this doesn't work
p + geom_violin(aes(fill = factor(vs)), position = position_dodge(preserve = "single"))
```

The latter attempt above produces this:

![image](https://user-images.githubusercontent.com/7232514/43668056-cbd28d00-972f-11e8-88ef-357fa18df14e.png)

**Comment by clauswilke** [comment]
The problem is that `position_dodge()` tries to find the maximum number of groups by counting the maximum number of rows in the data with the same `xmin` value:
https://github.com/tidyverse/ggplot2/blob/4d2ca992dc37fee598d83d3d3f524dbba38f4187/R/position-dodge.r#L100-L101
This works for boxplots, because each boxplot is one line in the processed data. But it doesn't work for violin plots, because each violin plot consists of many lines (512 by default). I suspect the solution would be to count the number of identical `xmin` values with distinct `group` values.
