### ISSUE TITLE
Visual tests fail with scales 1.0

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2824]
I updated to scales 1.0 and now numerous visual tests fail. I could just accept them but I think it would be good if somebody who has worked on scales could look them over to make sure it's all good. Most noticeable are substantial changes in default data ranges for data sets with only a single x or y value (see screenshots).

Before:
<img width="509" alt="screen shot 2018-08-10 at 9 01 39 pm" src="https://user-images.githubusercontent.com/4210929/43986566-a8f5c0b6-9ce0-11e8-9bf1-206d640ba539.png">

After:
<img width="509" alt="screen shot 2018-08-10 at 9 01 46 pm" src="https://user-images.githubusercontent.com/4210929/43986569-b50f21da-9ce0-11e8-9734-4c9870111872.png">

Before:
<img width="506" alt="screen shot 2018-08-10 at 8 59 03 pm" src="https://user-images.githubusercontent.com/4210929/43986553-8017acf4-9ce0-11e8-9706-1a3822835cb2.png">

After:
<img width="510" alt="screen shot 2018-08-10 at 8 58 47 pm" src="https://user-images.githubusercontent.com/4210929/43986555-871f57b8-9ce0-11e8-9fc8-4ceb1942ce81.png">

**Comment by dpseidel** [comment]
So I expect both the failures above come from our fix to #2281 in r-lib/scales#161 -- the behavior is as expected for zero range discrete scales and a little surprising for the continuous scale, I'll look into both to confirm.  Presumably because of the same or similar reason why visual tests weren't running on travis, tests on my system weren't showing any failures at all until I updated my version of vdiffr this morning. Now that I can actually see the failures, I'll look them over and get a sense of what are expected changes and if there is anything to be concerned about.

**Comment by clauswilke** [comment]
It seems to me that the result for continuous scales is as expected given the change in 
https://github.com/r-lib/scales/pull/161: You set the zero range to 1 and then expand by 5% in either direction, yielding a range of 0.95 to 1.05.

**Comment by hadley** [comment]
Yeah, I think it makes a lot of sense - the previous values were pure magic, and now they arise from the scale expansion parameters.
