### ISSUE TITLE
Inconsistent Scale Management

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2851]
I recently upgraded to ggplot2 version 3.0.0, and I was surprised by the change to discrete scales where I was now getting a yellow value (near-invisible on a white background).  As I was looking into how to change the default back to the prior behavior, I noticed inconsistent handling of colour scale types with ggplot2 version 3.

* In `scale_colour_continuous()` a new `type` argument along with an option managed by `getOption("ggplot2.continuous.colour", default="gradient")` determines how the scale is determined.
* `scale_colour_ordinal()` is assigned to `scale_colour_viridis_d()`, but it is not mentioned in the manual.

If global options will be the way that default scales are managed in the future, could a new help page be added for all the options that control ggplot2?  (My preference is that this will be moved away from.)

Can the default function used to control each scale be defined in a single help page to assist with finding  how to change the default behavior?

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by clauswilke** [comment]
Related: #2691

**Comment by teunbrand** [comment]
In #5946 we moved away from the `type` argument in favour of theme-able default palettes.
The type argument is still there for backward compatibility, but the 'preferred path' to setting default colours is now consistent.
As such, I think we can mark this issue as completed.
