### ISSUE TITLE
aes and aes_string return different plots

### ISSUE THREAD

**Issue by mojaveazure** [tidyverse/ggplot2#2896]
I'm working with a [custom geom for split violin plots](https://stackoverflow.com/questions/35717353/split-violin-plot-with-ggplot2) and have noticed that using `aes_string` returns a different plot than `aes`. Given that `aes_string` is supposed to be used when programming with ggplot2, I'm wondering if there's something wrong with the custom geom or if `aes` and `aes_string` are supposed to do different things.

```r
library(grid)
library(scales)
library(ggplot2)
GeomSplitViolin <- ggproto(
  "GeomSplitViolin",
  GeomViolin,
  draw_group = function(self, data, ..., draw_quantiles = NULL) {
    data$xminv <- data$x - data$violinwidth * (data$x - data$xmin)
    data$xmaxv <- data$x + data$violinwidth * (data$xmax - data$x)
    grp <- data[1, 'group']
    print(grp)
    if (grp %% 2 == 1) {
      data$x <- data$xminv
      data.order <- data$y
    } else {
      data$x <- data$xmaxv
      data.order <- -data$y
    }
    newdata <- data[order(data.order), , drop = FALSE]
    newdata <- rbind(
      newdata[1, ],
      newdata,
      newdata[nrow(x = newdata), ],
      newdata[1, ]
    )
    newdata[c(1, nrow(x = newdata) - 1, nrow(x = newdata)), 'x'] <- round(x = newdata[1, 'x'])
    grob <- if (length(x = draw_quantiles) > 0 & !zero_range(x = range(data$y))) {
      stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <= 1))
      quantiles <- ggplot2:::create_quantile_segment_frame(data = data, draw_quantiles = draw_quantiles)
      aesthetics <- data[rep.int(x = 1, times = nrow(x = quantiles)), setdiff(x = names(x = data), y = c("x", "y")), drop = FALSE]
      aesthetics$alpha <- rep.int(x = 1, nrow(x = quantiles))
      both <- cbind(quantiles, aesthetics)
      quantile.grob <- GeomPath$draw_panel(both, ...)
      grobTree(GeomPolygon$draw_panel(newdata, ...), name = quantile.grob)
    }
    else {
      GeomPolygon$draw_panel(newdata, ...)
    }
    grob$name <- grobName(grob = grob, prefix = 'geom_split_violin')
    return(grob)
  }
)
geom_split_violin <- function(
  mapping = NULL,
  data = NULL,
  stat = "ydensity",
  position = "identity",
  ...,
  draw_quantiles = NULL,
  trim = TRUE,
  scale = "area",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE
) {
  return(layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomSplitViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      draw_quantiles = draw_quantiles,
      na.rm = na.rm,
      ...
    )
  ))
}
my_data = data.frame(
    y=c(rnorm(1000), rnorm(1000, 0.5), rnorm(1000, 1), rnorm(1000, 1.5)),
    x=c(rep('a', 2000), rep('b', 2000)),
    m=c(rep('i', 1000), rep('j', 2000), rep('i', 1000))
)
ggplot(data = my_data, mapping = aes(x = x, y = y, fill = m)) + geom_split_violin() + labs(title = 'aes')
ggplot(data = my_data, mapping = aes_string(x = 'x', y = 'y', fill = 'm')) + geom_split_violin() + labs(title = 'aes_string')
```
![image](https://user-images.githubusercontent.com/11035068/45652271-12579c80-baa2-11e8-9126-58dde78bde3a.png)
![image](https://user-images.githubusercontent.com/11035068/45652278-1d123180-baa2-11e8-93ec-3af6e0effcd5.png)

**Comment by clauswilke** [comment]
The only difference I can see is that the two functions return the aesthetic mapping in different orders:
``` r
library(ggplot2)
aes(x = x, y = y, fill = m)
#> Aesthetic mapping: 
#> * `x`    -> `x`
#> * `y`    -> `y`
#> * `fill` -> `m`
aes_string(x = 'x', y = 'y', fill = 'm')
#> Aesthetic mapping: 
#> * `fill` -> `m`
#> * `x`    -> `x`
#> * `y`    -> `y`
```

Created on 2018-09-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

And in fact, if I change the order after the fact I can recover the correct plot with your custom geom. Not quite sure yet what exactly differs when the aesthetics are in a different order, but from a quick glance at your code I suspect it isn't sufficiently robust in how it detects which part of the violin to draw on the left and which on the right. Something for you to ponder: what happens if you have more than two groups?

``` r
library(grid)
library(scales)
library(ggplot2)
GeomSplitViolin <- ggproto(
  "GeomSplitViolin",
  GeomViolin,
  draw_group = function(self, data, ..., draw_quantiles = NULL) {
    data$xminv <- data$x - data$violinwidth * (data$x - data$xmin)
    data$xmaxv <- data$x + data$violinwidth * (data$xmax - data$x)
    grp <- data[1, 'group']
    print(grp)
    if (grp %% 2 == 1) {
      data$x <- data$xminv
      data.order <- data$y
    } else {
      data$x <- data$xmaxv
      data.order <- -data$y
    }
    newdata <- data[order(data.order), , drop = FALSE]
    newdata <- rbind(
      newdata[1, ],
      newdata,
      newdata[nrow(x = newdata), ],
      newdata[1, ]
    )
    newdata[c(1, nrow(x = newdata) - 1, nrow(x = newdata)), 'x'] <- round(x = newdata[1, 'x'])
    grob <- if (length(x = draw_quantiles) > 0 & !zero_range(x = range(data$y))) {
      stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <= 1))
      quantiles <- ggplot2:::create_quantile_segment_frame(data = data, draw_quantiles = draw_quantiles)
      aesthetics <- data[rep.int(x = 1, times = nrow(x = quantiles)), setdiff(x = names(x = data), y = c("x", "y")), drop = FALSE]
      aesthetics$alpha <- rep.int(x = 1, nrow(x = quantiles))
      both <- cbind(quantiles, aesthetics)
      quantile.grob <- GeomPath$draw_panel(both, ...)
      grobTree(GeomPolygon$draw_panel(newdata, ...), name = quantile.grob)
    }
    else {
      GeomPolygon$draw_panel(newdata, ...)
    }
    grob$name <- grobName(grob = grob, prefix = 'geom_split_violin')
    return(grob)
  }
)
geom_split_violin <- function(
  mapping = NULL,
  data = NULL,
  stat = "ydensity",
  position = "identity",
  ...,
  draw_quantiles = NULL,
  trim = TRUE,
  scale = "area",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE
) {
  return(layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomSplitViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      draw_quantiles = draw_quantiles,
      na.rm = na.rm,
      ...
    )
  ))
}
my_data = data.frame(
  y=c(rnorm(1000), rnorm(1000, 0.5), rnorm(1000, 1), rnorm(1000, 1.5)),
  x=c(rep('a', 2000), rep('b', 2000)),
  m=c(rep('i', 1000), rep('j', 2000), rep('i', 1000))
)
ggplot(data = my_data, mapping = aes_string(x = 'x', y = 'y', fill = 'm')[c(2, 3, 1)]) + geom_split_violin() + labs(title = 'aes_string')
```

![](https://i.imgur.com/4KHqKZF.png)

    #> [1] 1
    #> [1] 2
    #> [1] 3
    #> [1] 4

Created on 2018-09-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by smouksassi** [comment]
#response_container_BBPPID{font-family: Calibri, sans-serif; font-size:initial; color: initial;}                                                                                                                                                                          Sent from my BlackBerry - the most secure mobile device - via the TELUS Network                                                                                                                                                                           From: notifications@github.comSent: September 17, 2018 18:20To: ggplot2@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [tidyverse/ggplot2] aes and aes_string return different plots (#2896)  The only difference I can see is that the two functions return the aesthetic mapping in different orders:
library(ggplot2)
aes(x = x, y = y, fill = m)
#> Aesthetic mapping: 
#> * `x`    -> `x`
#> * `y`    -> `y`
#> * `fill` -> `m`
aes_string(x = 'x', y = 'y', fill = 'm')
#> Aesthetic mapping: 
#> * `fill` -> `m`
#> * `x`    -> `x`
#> * `y`    -> `y`
Created on 2018-09-17 by the reprex package (v0.2.0).
And in fact, if I change the order after the fact I can recover the correct plot with your custom geom. Not quite sure yet what exactly differs when the aesthetics are in a different order, but from a quick glance at your code I suspect it isn't sufficiently robust in how it detects which part of the violin to draw on the left and which on the right. Something for you to ponder: what happens if you have more than two groups?
library(grid)
library(scales)
library(ggplot2)
GeomSplitViolin <- ggproto(
  "GeomSplitViolin",
  GeomViolin,
  draw_group = function(self, data, ..., draw_quantiles = NULL) {
    data$xminv <- data$x - data$violinwidth * (data$x - data$xmin)
    data$xmaxv <- data$x + data$violinwidth * (data$xmax - data$x)
    grp <- data[1, 'group']
    print(grp)
    if (grp %% 2 == 1) {
      data$x <- data$xminv
      data.order <- data$y
    } else {
      data$x <- data$xmaxv
      data.order <- -data$y
    }
    newdata <- data[order(data.order), , drop = FALSE]
    newdata <- rbind(
      newdata[1, ],
      newdata,
      newdata[nrow(x = newdata), ],
      newdata[1, ]
    )
    newdata[c(1, nrow(x = newdata) - 1, nrow(x = newdata)), 'x'] <- round(x = newdata[1, 'x'])
    grob <- if (length(x = draw_quantiles) > 0 & !zero_range(x = range(data$y))) {
      stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <= 1))
      quantiles <- ggplot2:::create_quantile_segment_frame(data = data, draw_quantiles = draw_quantiles)
      aesthetics <- data[rep.int(x = 1, times = nrow(x = quantiles)), setdiff(x = names(x = data), y = c("x", "y")), drop = FALSE]
      aesthetics$alpha <-  rep.int(x = 1, nrow(x = quantiles))
      both <- cbind(quantiles, aesthetics)
      quantile.grob <- GeomPath$draw_panel(both, ...)
      grobTree(GeomPolygon$draw_panel(newdata, ...), name = quantile.grob)
    }
    else {
      GeomPolygon$draw_panel(newdata, ...)
    }
    grob$name <- grobName(grob = grob, prefix = 'geom_split_violin')
    return(grob)
  }
)
geom_split_violin <- function(
  mapping = NULL,
  data = NULL,
  stat = "ydensity",
  position = "identity",
  ...,
  draw_quantiles = NULL,
  trim = TRUE,
  scale = "area",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE
) {
  return(layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomSplitViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      draw_quantiles = draw_quantiles,
      na.rm = na.rm,
      ...
    )
  ))
}
my_data = data.frame(
  y=c(rnorm(1000), rnorm(1000, 0.5), rnorm(1000, 1), rnorm(1000, 1.5)),
  x=c(rep('a', 2000), rep('b', 2000)),
  m=c(rep('i', 1000), rep('j', 2000), rep('i', 1000))
)
ggplot(data = my_data, mapping = aes_string(x = 'x', y = 'y', fill = 'm')[c(2, 3, 1)]) + geom_split_violin() + labs(title = 'aes_string')

#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4

Created on 2018-09-17 by the reprex package (v0.2.0).

**Comment by mojaveazure** [comment]
Hi Claus,

Okay, so why would the order of aesthetics matter? I modified the `setup_data` function to add the data frame that gets passed to `draw_group` to the global environment, and I've noticed that the data is misordered before the geom gets it (unless I'm looking in completely the wrong place)

```R
GeomSplitViolin <- ggproto(
  "GeomSplitViolin",
  GeomViolin,
  setup_data = function(data, params) {
    data$width <- data$width %||% params$width %||% (resolution(data$x, FALSE) * 0.9)
    data <- plyr::ddply(data, "group", transform, xmin = x - width/2, xmax = x + width/2)
    e <- globalenv()
    name <- paste(sample(x = letters, size = 5), collapse = '')
    message("Saving initial data to ", name)
    e[[name]] <- data
    return(data)
  },
  draw_group = function(self, data, ..., draw_quantiles = NULL) {
    # browser()
    data$xminv <- data$x - data$violinwidth * (data$x - data$xmin)
    data$xmaxv <- data$x + data$violinwidth * (data$xmax - data$x)
    grp <- data[1, 'group']
    print(grp)
    if (grp %% 2 == 1) {
      data$x <- data$xminv
      data.order <- data$y
    } else {
      data$x <- data$xmaxv
      data.order <- -data$y
    }
    newdata <- data[order(data.order), , drop = FALSE]
    newdata <- rbind(
      newdata[1, ],
      newdata,
      newdata[nrow(x = newdata), ],
      newdata[1, ]
    )
    newdata[c(1, nrow(x = newdata) - 1, nrow(x = newdata)), 'x'] <- round(x = newdata[1, 'x'])
    grob <- if (length(x = draw_quantiles) > 0 & !zero_range(x = range(data$y))) {
      stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <= 1))
      quantiles <- QuantileSegments(data = data, draw.quantiles = draw_quantiles)
      aesthetics <- data[rep.int(x = 1, times = nrow(x = quantiles)), setdiff(x = names(x = data), y = c("x", "y")), drop = FALSE]
      aesthetics$alpha <- rep.int(x = 1, nrow(x = quantiles))
      both <- cbind(quantiles, aesthetics)
      quantile.grob <- GeomPath$draw_panel(both, ...)
      grobTree(GeomPolygon$draw_panel(newdata, ...), name = quantile.grob)
    }
    else {
      GeomPolygon$draw_panel(newdata, ...)
    }
    grob$name <- grobName(grob = grob, prefix = 'geom_split_violin')
    return(grob)
  }
)
```

```r
ggplot(data = my_data, mapping = aes_string(x = 'x', y = 'y', fill = 'm')) + geom_split_violin()
```
```
#> Saving initial data to vmiwd
#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4
```
```R
ggplot(data = my_data, mapping = aes(x = x, y = y, fill = m)) + geom_split_violin()
```
```
#> Saving initial data to zyxpa
#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4
```
```R
unique(x = subset(x = vmiwd, subset = x == 1, select = 'group'))
```
```
#>      group
#> 1        1
#> 1025     3
```
```r
unique(x = subset(x = zyxpa, subset = x == 1, select = 'group'))
```
```
#>     group
#> 1       1
#> 513     2
```

The `x` and `group` values, which are the only identifiers of where the data belongs and what side it should be on passed to `draw_groups`, aren't the same between `aes` and `aes_string`. Is there another place within the geom that I should be looking and controlling for this modification?

As for more than two groups, this geom supports more than two `x` groups, but not more than two `fill` groups. I'm not sure why one would have a split violin plot with multiple splits.

**Comment by yutannihilation** [comment]
`group` is calculated here. Since the order of variable does matter and you don't have control over this, I too feel it's not a good idea to rely on the group IDs.

https://github.com/tidyverse/ggplot2/blob/fa3cd8fbd4c904b7cd63687c8f7149e3abba0a4e/R/grouping.r#L5-L28

Maybe you can calculate another group ID for this purpose in `draw_panel()` and pass it to `draw_group()`?

**Comment by clauswilke** [comment]
I think there needs to be an explicit way of specifying which parts of the data should be drawn to the left and which to the right, maybe with an additional aesthetic mapping, or by having a `yleft` and `yright` aesthetic.

**Comment by hadley** [comment]
This doesn't seem like a ggplot2 bug, so I'm going to close the issue.
