### ISSUE TITLE
Changing the `panel_params` in `ggextension`

### ISSUE THREAD

**Issue by amirmasoudabdol** [tidyverse/ggplot2#2899]
This is not an issue but a question. I've asked it on RStudio community, and [StackOverflow](https://stackoverflow.com/questions/52321280/how-to-manipulate-set-theme-related-options-in-a-ggplot2-extension) and I didn't get any answers. So, I hope someone here could point me in the right direction.

This is a follow up to [this question](https://community.rstudio.com/t/manipulating-the-theme-in-ggextension/14225/5?u=mrmsdbdl). Although I think I've figured out most of the things that I would like to do, I still cannot modify the `layout` and `panel_params` parameters. I can technically assign new values to them, but `ggplot` doesn't use them in the `draw_panel`. This suggests that I'm not changing them at the right place.

Here is the code 2 for `geom_sand`. And here is an example:

```
df <- data.frame(
    x = runif(10, -10, 10),
    y = runif(10, -10, 10)
)

ggplot(df, aes(x = x, y = y)) +
    geom_sand(size = 2, hl = 5, vl = 5)
```

What I'd like to happen is for me to be able to change the `x.range` and `y.range` and later on maybe change the `x.labels` and `y.labels`. You can find my attempts on line 105 to 108, as:

```
panel_params$x.range <- c(-15, 15)
panel_params$y.range <- c(-15, 15)

panel_params$y.labels <- c("10", "15")
```

I'd appreciate any help or a document that I can refer too. Unfortunately, the official documentation on extending `ggplot` are not very elaborate compared to the capabilities of `ggplot`.

**Comment by clauswilke** [comment]
A couple of comments:

1. I think you'll have to read the ggplot2 source code to see how the parts that you want to modify work. Even if we had better developer documentation it's unlikely that all special cases would be covered adequately.

2. Another good approach is to look at extensions or parts of ggplot2 that do something similar to what you want and see how they are implemented.

3. In your case, it sounds to me you may want to implement a coord rather than a geom, or maybe a geom/coord combo. For sure, what you describe would not work with every possible coord out there.

4. You may want to look at `geom_sf()`/`coord_sf()` for an example of an integrated geom/coord combo, and also to see how a geom can set its own coord.

I'm going to close this issue because there isn't an actionable item for ggplot2 developers.
