### ISSUE TITLE
`NA` limits in coords

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#2907]
Setting `NA` in limits of `coords` in a similar fashion to `scales` ends up in an error. 

``` r
library(ggplot2)

ggplot(cars, aes(speed, dist)) +
   geom_point() +
   coord_cartesian(ylim = c(25, NA))  # emulating scale_y_continuous(limits = c(25, NA))
#> Error in if (zero_range(range)) zero_width else diff(range): missing value where TRUE/FALSE needed
```

Created on 2018-09-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I've tinker a bit and found that the error is in this line:
 https://github.com/tidyverse/ggplot2/blob/01155ba2e9394e17066668eace50c13354e03b3a/R/coord-cartesian-.r#L121

Adding this:
`limits <- ifelse(is.na(limits), scale$get_limits(), limits)`
solves the issue in this case. 

``` r
library(ggplot2)

scale_range <- function(scale, limits = NULL, expand = TRUE) {
   expansion <- if (expand) ggplot2:::expand_default(scale) else c(0, 0)
   
   if (is.null(limits)) {
      scale$dimension(expansion)
   } else {
      limits <- ifelse(is.na(limits), scale$get_limits(), limits)
      range <- range(scale$transform(limits))
      scales::expand_range(range, expansion[1], expansion[2])
   } 
}

assignInNamespace("scale_range", scale_range, ns = "ggplot2")

ggplot(cars, aes(speed, dist)) +
   geom_point() +
   coord_cartesian(ylim = c(25, NA))  
```

![](https://i.imgur.com/vsgK4lu.png)

Created on 2018-09-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I'm not versed enough on how `ggplot2` handles coords to know if it's a robust fix across different coords, though.

**Comment by atusy** [comment]
There's another inconsistency among `coord_cartesian()` and `scale_*_continuous1()`.
Limits for coord_cartesian can be length larger than 3 due to `range()` in `scale_range()` unlike limits for `scale_*_continuous()`.

Thus, in `ifelse(is.na(limits), scale$get_limits(), limits)` by @eliocamp, `scale$get_limits()` will be re-cycled to have same length with `limits`.
It may result in unexpected behavior.

```r
library(ggplot2)

scale_range <- function(scale, limits = NULL, expand = TRUE) {
   expansion <- if (expand) ggplot2:::expand_default(scale) else c(0, 0)
   
   if (is.null(limits)) {
      scale$dimension(expansion)
   } else {
      limits <- ifelse(is.na(limits), scale$get_limits(), limits)
      range <- range(scale$transform(limits))
      scales::expand_range(range, expansion[1], expansion[2])
   } 
}

assignInNamespace("scale_range", scale_range, ns = "ggplot2")

ggplot(cars, aes(speed, dist)) +
   geom_point() +
   coord_cartesian(ylim = c(25, NA, NA))
```

![image](https://user-images.githubusercontent.com/30277794/48924612-8c226100-eefd-11e8-83a0-0eab635fe244.png)

Created on 2018-11-23 by the reprex package (v0.2.1)


I think `limits` argument should only accept

    - a finite value
    - a numeric vector of length 2 with or without NA

Is there any reason that `coord_cartesian` needs to accept `limits` with length larger than 2?

**Comment by hadley** [comment]
I just tried to do this too!
