### ISSUE TITLE
ggplot2 Elegant Graphics.. text code error

### ISSUE THREAD

**Issue by edmundesterbauer** [tidyverse/ggplot2#2911]
p57 of text.
USAboundaries does not have groups hence aes(group=group) does not work as per code p57 of text.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks

**Comment by batpigandme** [comment]
If you're talking about the mapping section that uses USAboundaries, _that_ package has changed since the book was published, and no longer returns fortified data frames (see [NEWS from USAboundaries](https://github.com/ropensci/USAboundaries/blob/master/NEWS.md#usaboundaries-020)).

If you really wanted to, you could install the old version of USAboundaries (before the 0.2.0 release), which would have the fortified option (see [USAboundaries package archive](https://cran.r-project.org/src/contrib/Archive/USAboundaries/)).

Either way, this repo is for the ggplot2 package, and not that book, so I'm going to close the issue. @hadley, is there a repo for the book?
