### ISSUE TITLE
Multiple nudge arguments results in warning

### ISSUE THREAD

**Issue by steffilazerte** [tidyverse/ggplot2#2977]
The documentation for 'position_nudge' implies that you should only give one value for nudge, but isn't explicit. I often give different nudge values for each label so I can nudge them in different directions.

This works, but results in a warning. I would suggest fixing the if() statement to check multiple values, or make it explicit that we shouldn't be using more than one nudge value.

Thanks!

``` r
library(ggplot2)

df <- data.frame(
  x = c(1,3,2,5),
  y = c("a","c","d","c")
)

ggplot(df, aes(x, y)) +
  geom_point() +
  geom_text(aes(label = y), nudge_y = c(-0.1, 0.1, -0.1, -0.1))

#> Warning in if (params$y != 0) {: the condition has length > 1 and only the
#> first element will be used
```

![](https://i.imgur.com/xs9MrQF.png)

<sup>Created on 2018-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by willemvdb42** [comment]
I'm experiencing the same issue, and would like to add that this warning has only been showing up for me since the latest version of `ggplot2`, i.e. version 3.1.0. Before that, I used version 2.2.1.9000, which did not produce this warning. 

I tested it using the following reprex. The warning only occured in the newer version of ggplot2.
`
library(tidyverse)

cars2 <-
  mtcars %>%
  group_by(gear) %>%
  summarize(
    mpg = mean(mpg)
  ) %>%
  ungroup()

ggplot(data = cars2) +
  geom_bar(
    mapping = aes(x = gear, y = mpg), 
    stat = "identity"
  ) +
  geom_text(
    mapping = aes(x = gear, y = mpg, label = round(mpg, 1)),
    nudge_y = ifelse(cars2$mpg > 20, -1, 1)
  )
`

A quick fix would be much appreciated!

**Comment by clauswilke** [comment]
I see what the problem is now. It's in these lines, which indeed were introduced with 3.1.0:
https://github.com/tidyverse/ggplot2/blob/a8e9668a598c607ba398c0a20b090a67eac3ff21/R/position-nudge.R#L50-L51

I should have put an `all()` around the comparison:
``` r
nudge_y <- c(1, -1, 1)
if (nudge_y == 0) print("no nudging in y direction")
#> Warning in if (nudge_y == 0) print("no nudging in y direction"): the
#> condition has length > 1 and only the first element will be used
if (all(nudge_y == 0)) print("no nudging in y direction")

nudge_y <- c(0, 0, 0)
if (nudge_y == 0) print("no nudging in y direction")
#> Warning in if (nudge_y == 0) print("no nudging in y direction"): the
#> condition has length > 1 and only the first element will be used
#> [1] "no nudging in y direction"
if (all(nudge_y == 0)) print("no nudging in y direction")
#> [1] "no nudging in y direction"
```

I agree this needs to be fixed, but for now the warning can be ignored. The only scenario in which this would cause a problem is a nudging vector whose first element is zero but that has other non-zero elements. And the workaround in that case would be use a very small non-zero value as the first element.

**Comment by clauswilke** [comment]
This is fixed now in the development version. It will probably be a while until it makes it onto CRAN, though.
