### ISSUE TITLE
backticks on non-ascii labels

### ISSUE THREAD

**Issue by gagnagaman** [tidyverse/ggplot2#3017]
Upgrading to version 3.10 of ggplot2 I encountered a strange behaviour 
with regards to non-ascii (utf-8) characters in labels.
In some cases ggplot will wrap the labels with backticks. In other cases
(with the same character) it will not. I have been examining this and it 
seems that the strange behaviour only occurs when the non-ascii character 
isn't the first one in the string. Thus in the example below when mán is the variable on 
the x axis it gets wrapped but ár does not.

```r
# pseudo data with the same non-ascii letter in two different locations.
> df=data.frame(ár=rep(1991:2000,each=12),mán=rep(1:12,10))
> df$hiti=with(df,ár/2000 + 10* sin(mán/12*2*pi) + rnorm(120))
> library(ggplot2)
> ggplot(data=df,aes(mán,hiti)) + geom_point()
> ggplot(data=df,aes(ár,hiti)) + geom_point()
```

**Comment by yutannihilation** [comment]
Thanks for reporting, this is already fixed in the dev version by #2981. You can try the dev version by `devtools::install_github("tidyverse/ggplot2")`, or set labels manually (e.g. `xlab()`).

```r
ggplot(data=df,aes(mán,hiti)) + geom_point() + xlab("mán")
```

(By the way, it's curious why `expr_text()` adds backticks to `mán`, which seems to ok to use without backticks...)

``` r
library(rlang)

expr_text(sym("mán"))
#> [1] "`mán`"
expr_text(sym("ár"))
#> [1] "ár"

mán <- 1
mán
#> [1] 1
```

<sup>Created on 2018-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
