### ISSUE TITLE
`inherit` must be a R6ClassGenerator in winbuilder for ggplot code

### ISSUE THREAD

**Issue by peterhurford** [tidyverse/ggplot2#3063]
I'm trying to build an R package vignette with a very simple call to ggplot2 (plotting an ROC curve):

`ggplot(ValidationRocPoints, aes(x = falsePositiveRate, y = truePositiveRate)) + geom_line()`

(`ValidationRocPoints` is a list containing ROC curve data.)

I can run this fine from my Mac, but when I use the [CRAN Win-Builder](https://win-builder.r-project.org), I get the following error:

```
* checking re-building of vignette outputs ... [32s] WARNING
Error(s) in re-building vignettes:
--- re-building 'AdvancedVignette.Rmd' using rmarkdown
Quitting from lines 173-184 (AdvancedVignette.Rmd) 
Error: processing vignette 'AdvancedVignette.Rmd' failed with diagnostics:
`inherit` must be a R6ClassGenerator.
--- failed re-building 'AdvancedVignette.Rmd'
```

Sorry in advance if this issue doesn't belong here - feel free to close. Thanks!

**Comment by ptoche** [comment]
something to do with package ``R6``? Have you contacted @wch ? he might know.

**Comment by peterhurford** [comment]
@ptoche Thanks! It looks to involve R6 in some way, maybe within ggplot2 internals. My code does not use R6 directly.

**Comment by clauswilke** [comment]
ggplot2 doesn't use R6. I doubt this is a ggplot2 issue. In any case, it's difficult to debug without a reproducible example.

**Comment by peterhurford** [comment]
@clauswilke Agreed. I wish I had something better for you... thanks anyway for commenting. When I remove the `ggplot2` call, my error goes away.

**Comment by wch** [comment]
@peterhurford I found your [SO post](https://stackoverflow.com/questions/54138329/ggplot2-claims-that-inherit-must-be-a-r6classgenerator) about this, and this gist from @andybega which is referenced in one of the comments: https://gist.github.com/andybega/abed6a8dc097f86d936f61b377480e63

Looking at the code In that gist, the problem seems to be related to the scales package. I think it was probably fixed in https://github.com/r-lib/scales/pull/170, but that fix apparently isn't on CRAN yet. As for why this seems to be happening only on Windows, I have no idea that is.

**Comment by wch** [comment]
Is it possible they're using an ancient version of ggplot2? In 1.0.1, I see the `structure(...., range = DiscreteRange$new()`, but in 2.0.0 it changed to `ggproto(...., range = discrete_range()`.

https://github.com/tidyverse/ggplot2/blob/v1.0.1/R/scale-.r#L149-L167
https://github.com/tidyverse/ggplot2/blob/v2.0.0/R/scale-.r#L612-L629

**Comment by clauswilke** [comment]
To be absolutely safe, it would be good to add the code from the gist to a vignette, though I would expect it will work.

@peterhurford If you want to help debugging this further, the next step is to start stripping parts from your package until you have the absolute minimal variant that still breaks on winbuilder. It could be that the problem is triggered by some dependency or other aspect of the package that isn't immediately obvious.

**Comment by peterhurford** [comment]
Thanks 100x @clauswilke and @wch for taking this issue of mine seriously and providing such useful analysis. My ggplot2 code reliably breaks winbuilder, so I will take lead from here to identify a minimal version that can be shared publicly. 👍

**Comment by clauswilke** [comment]
Actually, maybe a good first step is to comment out the `ggplot()` call in the vignette and place `library(ggplot2); sessionInfo()` somewhere in the examples, to test the hypothesis that an old version of ggplot2 is pulled in.

**Comment by wch** [comment]
One possibility is that a package (other than ggplot2) imported by your package did something like this: It saved some objects from ggplot2 at build time (which is generally a bad idea), and it re-exported those objects. If that package was built with an old version of ggplot2, then it would make the old version of those objects available to your package.

Without seeing your package, or better, a minimal package that reproduces the problem, it's hard to say exactly what the cause is.

**Comment by yutannihilation** [comment]
@peterhurford Is this the vignette?
https://github.com/cran/datarobot/blob/62ef66b559b14f20565b95320d83a4d582ba292b/inst/doc/AdvancedVignette.Rmd#L218

**Comment by peterhurford** [comment]
@yutannihilation Yes, that is the vignette.

**Comment by peterhurford** [comment]
@wch Thanks! I'll try to find a minimally breaking package.

**Comment by andybega** [comment]
This probably muddles things more, but the instance of this problem that I had (in the gist) with R-devel on win-builder was resolved when I re-ran the checks yesterday. As far as I can tell I made no changes that would have been related to this :man_shrugging:

**Comment by yutannihilation** [comment]
@andybega 
Thanks for the information, then it seems a temporary problem in win-builder...

@peterhurford 
Congratulations for the success of datarobot on CRAN! 🎉 Can we close this?

**Comment by yutannihilation** [comment]
> I had to remove all ggplot2 code to get it to work on CRAN.

Oh, sorry to hear that...

Could you try win-builder again with the same source code when you have time? If that was a temporary problem on win-builder's side, it might success now. If it still fails, [r-package-devel](https://stat.ethz.ch/mailman/listinfo/r-package-devel) might be a better place to ask because the maintainers of win-builder are there.

**Comment by peterhurford** [comment]
Hey guys, I resubmitted the package with ggplot2 code to winbuilder and it did spontaneously work again. I dunno what 👻 caused the problem, but I can agree this is resolved. I'll be uploading the v2.12 package of datarobot to CRAN in about a month, so I'll have another run then to be sure. In the meantime, I'll close this issue.

Thanks again for all the wonderful help and for not dismissing this issue. You guys are a great community and make me truly proud to be an R developer.

**Comment by yutannihilation** [comment]
Oh, wow...👻

That's a pity you need to wait for 1 month just because of a temporary problem. Anyway, I'm glad that the problem has gone. Wish you a luck on the next CRAN submission!
