### ISSUE TITLE
 Error in scale_index[[i]]: subscript out of bounds when we have layers with different datasets and facets with free scales

### ISSUE THREAD

**Issue by smouksassi** [tidyverse/ggplot2#3099]
---
When having a composite ggplot with a data subset per layer setting scales = "free" gives an error.
What is fundamentally wrong with this approach ?
setting scales to fixed don't produce an error 

``` r
require(ggplot2)
#> Loading required package: ggplot2
ggplot(mtcars, aes(mpg, disp)) + facet_grid(~cyl,scales="free") + 
  geom_point() +
  geom_point(data = subset(mtcars, cyl == 4)) +
  geom_line(data = subset(mtcars, cyl == 6)) +
  geom_text(data = subset(mtcars, cyl == 8), aes(label = gear))
#> Error in scale_index[[i]]: subscript out of bounds

ggplot(mtcars, aes(mpg, disp)) + facet_grid(~cyl,scales="fixed") + 
  geom_point() +
  geom_point(data = subset(mtcars, cyl == 4)) +
  geom_line(data = subset(mtcars, cyl == 6)) +
  geom_text(data = subset(mtcars, cyl == 8), aes(label = gear))
```

![](https://i.imgur.com/jWAX8gI.png)

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by karawoo** [comment]
What version of ggplot2 are you using? I can't reproduce this error with 3.1.0.

**Comment by smouksassi** [comment]
other attached packages:
[1] ggplot2_3.1.0.9000 usethis_1.4.0      devtools_2.0.1

**Comment by karawoo** [comment]
Ah, looks like this was introduced in #3013. Having any one of the additional layers using subsetted data causes the error. The problem is here: 
https://github.com/tidyverse/ggplot2/blob/1f259f489fa2c88d85812e6a14a24443c1aebd5c/R/layout.R#L275

Taking the following example:

``` r
library("ggplot2")
ggplot(mtcars, aes(mpg, disp)) + facet_grid(~cyl,scales="free") +
  geom_line(data = subset(mtcars, cyl == 6))
#> Error in scale_index[[i]]: subscript out of bounds
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Before the removal of plyr, `scale_index` looked like this:

```r
scale_index
#> [[1]]
#> integer(0)

#> [[2]]
#> [1] 1 2 3 4 5 6 7

#> [[3]]
#> integer(0)
```

With the changes in #3013 only the non-empty list elements are included, which then causes the subsetting error in the next part of the function.

```r
scale_index
#> [[1]]
#> [1] 1 2 3 4 5 6 7
```

**Comment by thomasp85** [comment]
Thanks for dissecting that @karawoo — I’ll make sure to fix it
