### ISSUE TITLE
Warning message when adding a manual scale in ggplot

### ISSUE THREAD

**Issue by SavasAli** [tidyverse/ggplot2#3127]
On [Stackoverflow](https://stackoverflow.com/questions/54580005/how-to-fix-an-error-when-adding-a-manual-scale-in-ggplot/54586124#54586124) they suggested to report my question as a bug, so here it is:

When I add a manual scale like in the example below. I get the following error message:
"Warning message: In if (self$guide == "none") return() : the condition has length > 1 and only the first element will be used"

```r
d <- data.frame(week = seq(1, 52, 1), 
            revenue = round(runif(52, 0, 100)), 0)

p <- ggplot(data = d, aes(x = week, y = revenue, fill = 'lightskyblue')) + 
  geom_bar(stat = 'identity', colour = 'black') 


p <- p + scale_fill_identity(name = NULL,
                             guide = guide_legend(label.position = 'top'),
                             labels = c('2019'))
```

**Comment by batpigandme** [comment]
Would you mind turning this into a [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It's especially helpful for ggplot2, since it automatically generates and uploads the plots (or lack thereof), which makes it much easier to go through at a glance.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

reprex is automatically installed with the tidyverse package, but if you don't have it, you can run
```r
install.packages("reprex")
```
If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks

**Comment by batpigandme** [comment]
You can take the comment above as a "for future reference", since I just ran your code through reprex (below)

``` r
library(ggplot2)
d <- data.frame(week = seq(1, 52, 1), 
                revenue = round(runif(52, 0, 100)), 0)

p <- ggplot(data = d, aes(x = week, y = revenue, fill = 'lightskyblue')) + 
  geom_bar(stat = 'identity', colour = 'black') 


p <- p + scale_fill_identity(name = NULL,
                             guide = guide_legend(label.position = 'top'),
                             labels = c('2019'))
p
#> Warning in if (self$guide == "none") return(): the condition has length > 1
#> and only the first element will be used
```

![](https://i.imgur.com/ZrYCXaM.png)

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
Code lines that need fixing:
https://github.com/tidyverse/ggplot2/blob/652a43189388d185a4d96c1f83cb6e06d00b8b06/R/scale-identity.r#L149
https://github.com/tidyverse/ggplot2/blob/652a43189388d185a4d96c1f83cb6e06d00b8b06/R/scale-identity.r#L170

`if (isTRUE(self$guide == "none")) return()` is probably better than the suggested fix on SO.
