### ISSUE TITLE
Better integrate extensions site with main site

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#3189]
At a minimum, I think we should link to from the main navbar, and we should probably mention it in the readme.

@yutannihilation do you have other ideas?

**Comment by yutannihilation** [comment]
> we should probably mention it in the readme.

http://www.ggplot2-exts.org/gallery/ is already mentioned in README! That's the reason why I became a maintainer of ggplot2-exts to keep it maintained to some extent because, at the time, the site was not well maintained (e.g. the metadata YAML had been broken for years...).

That said, I have no idea how to integrate. Better integration might require some changes on ggplot2-exts's side. Let me think...
