### ISSUE TITLE
Inconsistent formals for `StatIdentity$compute_layer`

### ISSUE THREAD

**Issue by coolbutuseless** [tidyverse/ggplot2#3202]
The formals for `compute_layer` in the majority of the Stats in ggplot2 are `c(self, data, params, layout)`

Two Stats are different from the others: `StatBindot` and `StatIdentity`.

Is there a reason for the different formals for these 2 stats?  Is this just a leftover from earlier version?  

I'm certain the `StatIdentity$compute_layer` and `StatBindot$compute_layer` argument names don't matter (either passed through or ignored) but it may be worth fixing for consistency

```
# formals for `compute_layer` across all Stats
Stat                [1] "self"   "data"   "params" "layout"
StatBin             [1] "self"   "data"   "params" "layout"
StatBin2d           [1] "self"   "data"   "params" "layout"
StatBindot          [1] "self"   "data"   "params" "panels"
StatBinhex          [1] "self"   "data"   "params" "layout"
StatBoxplot         [1] "self"   "data"   "params" "layout"
StatContour         [1] "self"   "data"   "params" "layout"
StatCount           [1] "self"   "data"   "params" "layout"
StatDensity         [1] "self"   "data"   "params" "layout"
StatDensity2d       [1] "self"   "data"   "params" "layout"
StatEcdf            [1] "self"   "data"   "params" "layout"
StatEllipse         [1] "self"   "data"   "params" "layout"
StatFunction        [1] "self"   "data"   "params" "layout"
StatIdentity        [1] "data"   "scales" "params"
StatQq              [1] "self"   "data"   "params" "layout"
StatQqLine          [1] "self"   "data"   "params" "layout"
StatQuantile        [1] "self"   "data"   "params" "layout"
StatSf              [1] "self"   "data"   "params" "layout"
StatSfCoordinates   [1] "self"   "data"   "params" "layout"
StatSmooth          [1] "self"   "data"   "params" "layout"
StatSum             [1] "self"   "data"   "params" "layout"
StatSummary         [1] "self"   "data"   "params" "layout"
StatSummary2d       [1] "self"   "data"   "params" "layout"
StatSummaryBin      [1] "self"   "data"   "params" "layout"
StatSummaryHex      [1] "self"   "data"   "params" "layout"
StatUnique          [1] "self"   "data"   "params" "layout"
StatYdensity        [1] "self"   "data"   "params" "layout"
```

**Comment by yutannihilation** [comment]
Thanks. I quickly checked the code.

* `StatIdentity` seems safe to fix because only `data` is used. 
* `StatBindot` might needs some care, but it seems no CRAN packages use this (c.f. https://github.com/search?q=org%3Acran+%28StatBindot+OR+bindot%29+-repo%3Acran%2Fggplot2&type=Code). So I think this is also OK to fix.

Let me see if there are some historical reasons.

**Comment by yutannihilation** [comment]
* `StatIdentity$compute_layer()` was added by this commit: https://github.com/tidyverse/ggplot2/commit/66b9df75f79f3a8f62c9683982a96b5a6d7bea38
* `StatBindot$compute_layer()` was added by this commit: https://github.com/tidyverse/ggplot2/commit/09faf058d789632974ffeb8da8c1a7ac91c3a91a

I found no special reason to keep them as is. It seems just because the common set of formals was `data, scales, ...` at that time (c.f. https://github.com/tidyverse/ggplot2/commit/8af983bc2b18118934d511368c00476d3ee2b624#diff-2b0d9305b6b639cd9de20829bd3e66b2R63). So, probably we can fix them.

BTW, 

> Two Stats are different from the others

this is correct, but actually ggplot2 has only three `compute_layer()` methods.

``` console
$ git grep "compute_layer = "
R/position-.r:  compute_layer = function(self, data, params, layout) {
R/position-identity.r:  compute_layer = function(data, params, scales) {
R/position-jitter.r:  compute_layer = function(data, params, panel) {
R/position-nudge.R:  compute_layer = function(data, params, panel) {
R/stat-.r:  compute_layer = function(self, data, params, layout) {
R/stat-bindot.r:  compute_layer = function(self, data, params, panels) {
R/stat-identity.r:  compute_layer = function(data, scales, params) {
```

Oh, and positions might be good to fix as well.

**Comment by thomasp85** [comment]
@yutannihilation can you make a PR for this?
