### ISSUE TITLE
Parse problem for label axis

### ISSUE THREAD

**Issue by agila5** [tidyverse/ggplot2#3228]
I want to create a plot with col and axis labels that need to be firstly parsed. I read [here](https://github.com/tidyverse/ggplot2/issues/311) that I have to use scales::parse_format and, while it works for the fill legend, it does not seem to work for the x axis since it shows only the ticks . Am I doing something wrong? 

``` r
# packages
library(ggplot2)

# data
fake_data <- data.frame(
  classes = c("alpha", "beta"),
  value = c(1, 2),
  stringsAsFactors = FALSE
)

ggplot(fake_data) + 
  geom_col(aes(x = classes, y = value, fill = classes)) + 
  scale_fill_discrete(labels = scales::parse_format()) + 
  scale_x_discrete(labels = scales::parse_format())
```

![](https://i.imgur.com/DTwvupv.png)

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
This looks like a bug in scales rather than in ggplot2. Would you mind [reporting it there](https://github.com/r-lib/scales/issues)? If I use ggplot2's internal parse function (which is not meant for public use, I'm just testing here) things work fine, so the problem lies with `scales::parse_format()`.

``` r
# packages
library(ggplot2)

# data
fake_data <- data.frame(
  classes = c("alpha", "beta"),
  value = c(1, 2),
  stringsAsFactors = FALSE
)

ggplot(fake_data) + 
  geom_col(aes(x = classes, y = value, fill = classes)) + 
  scale_fill_discrete(labels = scales::parse_format()) + 
  scale_x_discrete(labels = ggplot2:::parse_safe)
```

![](https://i.imgur.com/Eqzq7aI.png)

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by agila5** [comment]
Thank you very much for your help! I just reported the same issue [there](https://github.com/r-lib/scales/issues/203).
