### ISSUE TITLE
Adding limits that contain all data to a histogram generates incorrect missing values warning (due to #2719)

### ISSUE THREAD

**Issue by jmarshallnz** [tidyverse/ggplot2#3265]
This seems to have been introduced in 3.1.1 - it does not occur in 3.0.0. I haven't verified completely but I believe it's due to #2719.

Adding scale_x_continuous/xlim to specify limits where all data are contained results in a warning that is incorrect (as no data are missing). The problem is the *transformed* data (i.e. the bars, xmin/xmax etc) are outside the specified limits, as they are computed using the limits (+/- width). This makes the error quite confusing! The plot is fine - no data are missing as the missing bars contain no data.

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.5.2
set.seed(2)
d <- data.frame(x=runif(1000))
g <- ggplot(d, aes(x=x)) + geom_histogram(bins=10)
g
```

![](https://i.imgur.com/1hr4AIC.png)

``` r

g + scale_x_continuous(limits=c(-1,2))
#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/9gcudeq.png)

Created on 2019-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by thomasp85** [comment]
@clauswilke this seem to be an unforeseen consequence of your fix. The only way I can see this being fixed is by having `StatBin` remove zero-count bins, and I think that will have a lot of unforeseen consequences... alternatively we'd need to subclass `GeomBar` for `geom_histogram()` to do some extra work... Thoughts..?

**Comment by clauswilke** [comment]
I have a number of thoughts:

1. This is broadly related to #2887, which we just decided we won't fix at this time.

2. Not sure what the use case is here, but I assume setting limits via `coord()` would be more appropriate here. Also, it's generally a good idea to set `binwidth` and `center` manually for `geom_histogram()`. We may need to write a tutorial to explain how to get histograms behave nicely.

3. An argument could be made that if only the requested bin number is set (via `bins`) **and** explicit limits are set in the scale, then the bins should be chosen such that they fit exactly into the scale limits. This is a fairly easy change to `stat_bin()` that somebody could implement.

Below I show two examples of how one could plot this example without generating a warning. The first is my preferred solution in this case, because it exactly matches the bins to the known data range. (And it works even if limits are set to 0 to 1).

``` r
library(ggplot2)
set.seed(2)
d <- data.frame(x=runif(1000))

ggplot(d, aes(x=x)) + 
  geom_histogram(binwidth = 0.2, center = 0.1) + 
  scale_x_continuous(limits = c(-1, 2))
```

![](https://i.imgur.com/4UbyfW5.png)

``` r

# this is not entirely appropriate, because the
# bins extend beyond the known data range of [0, 1)
ggplot(d, aes(x=x)) + 
  geom_histogram(bins = 10) + 
  coord_cartesian(xlim = c(-1, 2))
```

![](https://i.imgur.com/KB1PHaP.png)

<sup>Created on 2019-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
Ok, as this is covered by #2887 I'm closing

**Comment by jmarshallnz** [comment]
Thanks! Agreed that #2887 covers this -apologies for missing that one!

I gave the student that spotted this the `coord` solution before posting.

Agreed that clearly documenting how the limit filtering applies and how coord limiting may be more suited is a decent way to go, as it definitely feels like a change would break things 😀

I wonder if it’s possible to improve the warning? I’ll take a look and see if anything jumps out. Might be able to use Inf for out of scale and add to handle_na?
