### ISSUE TITLE
Upgrade license to GPL 2 *or* 3

### ISSUE THREAD

**Issue by miguelmorin** [tidyverse/ggplot2#3272]
I am writing a package that depends on `ggplot2` and `e1071`, which is GPL 2, and `rstan`, which is GPL 3.

On choosing a license, I realised that [I cannot use packages that depend on GPL 2 and 3](https://www.gnu.org/licenses/license-list.en.html#GPLv2):

> Please note that GPLv2 is, by itself, not compatible with GPLv3. However, most software released under GPLv2 allows you to use the terms of later versions of the GPL as well.

Following [this thread on StackExchange](https://opensource.stackexchange.com/questions/4414/if-my-r-package-uses-gpl-packages-does-mine-automatically-inherit-gpl), I request a change of licence to GPL 2 **or** 3:

> these two versions [(GPL 2 and 3)] are mutually incompatible so you cannot distribute a program that would depend on libraries under both licenses. To solve this hurdle, the best way is probably to write to the authors of the "GPL 2.0 only" packages and ask them to license their libraries under "GPL 2.0 or later" instead.

#1723 mentions "It is ok to include the GPL v2/3 license in the LICENSE file." but the `DESCRIPTION` and `LICENSE` seem to be GPL 2 only.

**Comment by clauswilke** [comment]
I think the general interpretation of the GPL license in R (which is consistent with my reading of the GPL 2 right now) is that using the exported interface of a GPL-licensed package A in a package B does not mean B needs to have a GPL-compatible license. You're not redistributing or modifying A, you're just using it. The situation would be different if you copied substantial portions of ggplot2 code into your package, such that your package is a direct derivative of ggplot2.

I note that rstan depends on ggplot2, to if my above understanding of the licenses were incorrect then rstan would be out of compliance and would have to fix their license.

Relicensing a large open-source project such as ggplot2 is almost always impossible, because you'd have to get agreement from every contributor who ever worked on the code.
