### ISSUE TITLE
breaks for `scale_y_continuous` are sometimes ignored, but labels are not

### ISSUE THREAD

**Issue by daranzolin** [tidyverse/ggplot2#3296]
Using `ylim`, however, works (see both plots below).

Reprex:

``` r
library(ggplot2)
df <- data.frame(
  x = 1:5,
  y = sample(seq(0.4, 0.5, by = 0.01), 5, replace = TRUE)
)

ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = paste(seq(0, 50, by = 10), "%"), breaks = seq(0, 0.5, by = 0.1))
```

![](https://i.imgur.com/p6liZfc.png)

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```

``` r
library(ggplot2)
df <- data.frame(
  x = 1:5,
  y = sample(seq(0.4, 0.5, by = 0.01), 5, replace = TRUE)
)

ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  geom_line() +
  ylim(0, 0.5)
```

![](https://i.imgur.com/Cz9k3Gv.png)

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```

**Comment by aosmith16** [comment]
The `ylim()` function is equivalent to using the `limits` argument in `scale_y_continuous()`.  

In your plot, the `breaks` and `labels` are set correctly given the default limits of the plot; there is only a break/label at 0.4 since that is the only value within the `y` range of the plot. 

Add in your limits, `limits = c(0, .5)`, to change them to the range you want.

``` r
ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = paste(seq(0, 50, by = 10), "%"), 
                     breaks = seq(0, 0.5, by = 0.1), 
                     limits = c(0, 0.5) )
```

![](https://i.imgur.com/XLpeq27.png)

Created on 2019-05-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by daranzolin** [comment]
Thanks @aosmith16 ! Sometimes I don't need to specify the `limits` argument, which is odd, but this solves it.
