### ISSUE TITLE
geom_sf prints extra misaligned grid lines

### ISSUE THREAD

**Issue by kendonB** [tidyverse/ggplot2#3326]
`geom_sf` with a particular transformed dataset prints odd misaligned grid lines. Not sure if this is a bug with `ggplot2` or `sf`. cc @edzer

[coastlines.zip](https://github.com/tidyverse/ggplot2/files/3175850/coastlines.zip)

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

coastlines = readRDS("~/coastlines.rds") %>% 
  st_transform(crs = 27200)

coastlines %>%   ggplot() + geom_sf()
```

![](https://i.imgur.com/kCeofCs.png)

<sup>Created on 2019-05-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
The problem lies in the graticules generated (also in geom_sf) by `sf::st_graticule`, but we need to sort out whether the code there needs improvement, or whether PROJ has difficulty with this projection, which is rather [unusual](https://www.linz.govt.nz/data/geodetic-system/datums-projections-heights/projections/new-zealand-map-grid-nzmg). The problem is further illustrated by
```r
plot(coastlines, axes = TRUE, 
graticule = TRUE)
```
![x](https://user-images.githubusercontent.com/520851/57676366-a4f60e80-7624-11e9-835c-24b9de68c41d.png)

**Comment by kendonB** [comment]
Will close here. Ref: https://github.com/r-spatial/sf/issues/1047
