### ISSUE TITLE
Add shape option to geom_dotplot

### ISSUE THREAD

**Issue by abalter** [tidyverse/ggplot2#3355]
Four years ago #1111 said this is "not possible." However, it seems essential. Despite the fact that only dinosaurs still read print journals, they still charge more for color plots. We NEED a shape option.

I'm confused about how this is "not possible" as if there is a physical law preventing it.

What about somehow manipulating the jitter machinery in stripchart to use binning?

**Comment by thomasp85** [comment]
It is not possible because geom_dotplot uses a circleGrob instead of a pointGrob. Points have uneven extend and it is thus not possible to stack them in a way that makes sense.

Of course it is not physically impossible to implement this somehow and you are free to do so using the extension system. The complexity of this puts it fairly outside the scope of ggplot2 itself though
