### ISSUE TITLE
Non sensical POSIXct axis labels

### ISSUE THREAD

**Issue by BartJanvanRossum** [tidyverse/ggplot2#3475]
---

Looking at the example below the first plot produces an output that looks perfectly fine. However when plotting only one point as in the second plot, the date time value on the x-axis is set to the number of seconds, so only a value of 50 is displayed.     
I know this can be fixed manually by setting date_labels in scale_x_datetime. However I think a more sensible default would be nice.

```r
library(ggplot2)
library(lubridate)

dat <- data.frame(x = as_datetime(c("2010-08-03 00:50:50", 
                                    "2010-08-04 00:50:50")), y = 1)

ggplot(dat, aes(x = x, y = y)) + geom_point()
ggplot(dat[1, ], aes(x = x, y = y)) + geom_point() 
```

**Comment by teunbrand** [comment]
I think this might be a better issue for {scales}, because that package decides the default formatting. Small reprex:

``` r
limits <- lubridate::as_datetime("2010-08-03 00:50:50")
limits <- c(limits, limits)
                      
trans <- scales::time_trans()
breaks <- trans$breaks(limits)
labels <- trans$format(breaks)
labels
#> [1] "47" "48" "49" "50" "51" "52"
```

<sup>Created on 2022-12-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

`trans$breaks()` uses `pretty()`, which assigns labels to the breaks, which are then used by `trans$format()` to give labels.

**Comment by teunbrand** [comment]
Opened https://github.com/r-lib/scales/issues/446, closing this here
