### ISSUE TITLE
Feature request: Allow expanding only horizontally or vertically in `coords_cartesian`

### ISSUE THREAD

**Issue by tmalsburg** [tidyverse/ggplot2#3513]
The function `coords_cartesian` has a parameter called `expand` that allows us to expand the x- and y-limits around the data a bit.  Possible values are `TRUE` for expanding and `FALSE` for not expanding.  I encountered multiple cases were it would have been useful to be able to expand just in the x- or y-dimension.  Please consider adding these options.  Thank you.

**Comment by clauswilke** [comment]
Could you please do a search for this topic among recent open and closed issues, and link back here to what you find? There have definitely been discussions of this topic, but I don't remember the latest status.

**Comment by tmalsburg** [comment]
I had searched for `coords_cartesian expand` but that didn't yield any results. When searching just for  `expand`, I get lots of results but they seem only vaguely related, e.g: #3371, #3270, #3338.

Through this search I found that I can use `scale_x_continuous(expand=c(0, 0))` to selectively disable expansion on one axis.  While this is useful, I still think it would be good to have more options for `coords_cartesian`'s `expand` parameter.

**Comment by clauswilke** [comment]
According to the discussion in #3270, expansion in coords can be controlled via the scale functions. In general, I believe the ggplot2 philosophy has been to set axis-specific properties via scale functions rather than via coord(*), to avoid overly complicated interfaces in coords. Is there anything you cannot currently do (i.e., a true missing feature), or are you only asking for a convenience change to the API?

(*) The same is true for brakes, labels, axis titles, etc. Those properties are all set via scale functions, not via coords.

**Comment by tmalsburg** [comment]
No feature is missing, afaict.  It's just confusing when you can set some aspects of expansion with `coords_cartesian` but for more fine-grained control you need to look elsewhere.  In this regard, the API is already overly complicated and slightly misleading IMO.  Thanks for your responses and please feel free to close this issue.
