### ISSUE TITLE
Fix error message for geom_density() when using y

### ISSUE THREAD

**Issue by Maschette** [tidyverse/ggplot2#3514]
Hi, 
The error message for geom_density() when using x and y comes up and says y is missing. My suggestion would be to change the error when x and y are present but stat is not identity to "y is present, did you mean to use stat = 'identity'" or something like that. Also adding an example that uses x and y to https://ggplot2.tidyverse.org/reference/geom_density.html would be great.  

``` r
x<-data.frame(value=seq(0,1,by=0.2), count=rnorm(6, mean = 10) )

library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.6.1

ggplot(x)+geom_density(aes(x=value, y=count))
#> Error: geom_density requires the following missing aesthetics: y

ggplot(x)+geom_density(aes(x=value, y=count), stat = 'identity')
```

![](https://i.imgur.com/SnZQefY.png)

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by batpigandme** [comment]
Hi Dale,
Would you want to do a PR for this?

**Comment by Maschette** [comment]
Hi Mara, 
If i knew how I might. I find tracking of error messages in ggplot really hard so I might leave it to someone else. 

Thanks for asking though.

**Comment by batpigandme** [comment]
Completely understood!

**Comment by yutannihilation** [comment]
I agree about the error message, but I don't feel it's nice to use `geom_density()` without `stat_density()`. Maybe you should use `geom_area()`?

**Comment by carywreams** [comment]
Have been looking at this for a couple of days, think I'm stuck now.

### Observation 1
I dumped the arguments to ```check_required_params``` prior to the call in ```compute_geom_1```

First observation is that under the default, ```stat="density"``` the ```y``` parm actually does not show up in ```compute_geom_1``` which is why the error kicks.

+ required: ```x, y```, 
+ data:  ```x, density, scaled, ndensity, count, n, flipped_aes, PANEL, group```, 
+ self$aes_params: (empty)

Whereas with ```stat="identity"```:

+ required : ```x, y```, 
+ data, ```x, y, PANEL, group```, 
+ self$aes_params: (empty)

The difference is in the ```names(data)``` result in the two listings.

So my current question -- which went unanswered when I collected Observation 2, below -- is this:
__Where is the manipulation of the ```data``` argument to ```compute_geom_1```? I found ```ggplot_build.ggplot``` but frankly got lost here trying to find the relevant manipulation prior to 
call to ```compute_geom_1```.  I'm going to focus my efforts here, but if there's an insight from someone, I'd be happy to listen to it.__

### Observation 2

stopped and entered traceback at same location as in Observation 1
Traceback call stack and line numbers were identical in the two cases.

stat = "density" | stat = "identity
:-------------------:|:-------------------------:
has ```stat_density``` | has ```stat_identity```
has ```$labels.fill``` | not present
has ```$labels.weight``` | not present

note - while ```stat_density``` has an ```orientation = NA``` value, ```stat_identity``` does not.
not sure that means anything.

**Comment by carywreams** [comment]
## Question

Is the check pulling labels from the data list to figure out what information is available ?
If so, there's a slew of ```xNNN``` elements in ```data```, but nothing with a ```yNNN``` format.

**Comment by carywreams** [comment]
### Observation 3

Under the failure scenario (```stat = "density"```, the default), eventually ```R/stat-density.r::compute_group()``` calls ```stat-density.r::compute_density()``` without passing any ```y``` elements from ```data```. 

Within ```compute_group()```, a new data_frame is created without any ```y``` elements, eventually leading to (from my reading of the code) a failure of the ```data``` to satisfy the ```required_aes``` check and issue the "requires y" error message.

I did find an empty  ```non_missing_aes``` var at one point and wonder if this was intended to avoid this scenario -- but I could not find any documentation on its use or intent.

 ### My Notes

```browser()``` call placed prior to creation of new data frame in ```compute_density```.
Not all line numbers will match master branch because of embedded debugging comments.

[where.log](https://github.com/tidyverse/ggplot2/files/3936509/where.log)

__Welcoming any suggestions on possible approaches to addressing the issue__

**Comment by stragu** [comment]
@thomasp85 , sorry if I misunderstood this, but it seems the issue as described by @Maschette is still the same in ggplot2 3.3.2:

``` r
x <- data.frame(value = seq(0, 1, by = 0.2),
                count = rnorm(6, mean = 10))
library(ggplot2)
ggplot(x) +
  geom_density(aes(x = value, y = count))
#> Error: geom_density requires the following missing aesthetics: y
```

![](https://i.imgur.com/htadkAT.png)

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by chasemc** [comment]
Same for v3.3.5

**Comment by francisbarton** [comment]
@Maschette this helped me solve the error message, when nothing else on the internet did. Thank you.
