### ISSUE TITLE
geom_text and scale_y_log10 issue

### ISSUE THREAD

**Issue by tungmilan** [tidyverse/ggplot2#3543]
Hello,

I'm not sure if I did something wrong but after adding `geom_text` and `scale_y_log10`, my plot was messed up. Any idea what went wrong?

Thanks!

``` r

library(tidyverse)

set.seed(1999)
sampledata <- tibble(Date = seq(as.Date("1999-10-01"), length.out = 60, by = 'day'),
                         Value = runif(60, min = 10, max = 1000))
sampledata
#> # A tibble: 60 x 2
#>    Date       Value
#>    <date>     <dbl>
#>  1 1999-10-01  770.
#>  2 1999-10-02  533.
#>  3 1999-10-03  490.
#>  4 1999-10-04  413.
#>  5 1999-10-05  887.
#>  6 1999-10-06  527.
#>  7 1999-10-07  930.
#>  8 1999-10-08  697.
#>  9 1999-10-09  558.
#> 10 1999-10-10  854.
#> # ... with 50 more rows

threshold <- tribble(~Date, ~Value, ~Note,
                     "1999-10-10", 50, "Bad",
                     "1999-10-10", 250, "Avg",
                     "1999-10-10", 500, "Good") %>%
  mutate(Date = as.Date(Date))
threshold
#> # A tibble: 3 x 3
#>   Date       Value Note 
#>   <date>     <dbl> <chr>
#> 1 1999-10-10    50 Bad  
#> 2 1999-10-10   250 Avg  
#> 3 1999-10-10   500 Good

ggplot(sampledata,
       aes(x = Date, y = Value)) +
  geom_line(size = 0.75) +
  geom_hline(threshold, mapping = aes(yintercept = Value), linetype = 'longdash', color = 'grey30') +
  geom_text(threshold, mapping = aes(x = Date, y = Value, label = Note), 
            inherit.aes = FALSE, nudge_y = 50) +
  scale_y_log10()
```

![](https://i.imgur.com/AUvpkG8.png)

<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is because of the `nudge_y` argument. It gets applied to the transformed data which means that it's effect will become non-linear (and potentially huge). In general the `nudge_*` arguments are pretty crude and should only get applied to linear transformed scales.

You can get something a bit nicer-looking by using `coord_trans(y = "log")` instead of `scaly_y_log()` but then you'll have a non-linear nudging:

```r
ggplot(sampledata,
       aes(x = Date, y = Value)) +
  geom_line(size = 0.75) +
  geom_hline(threshold, mapping = aes(yintercept = Value), linetype = 'longdash', color = 'grey30') +
  geom_text(threshold, mapping = aes(x = Date, y = Value, label = Note), 
            inherit.aes = FALSE, nudge_y = 50) +
  coord_trans(y = 'log')
```
![image](https://user-images.githubusercontent.com/1775316/65749179-ef74b500-e105-11e9-88ef-06fbd690ef96.png)

As your text is all a single line the best course of action would probably be to set a negative `vjust` on the text (be aware that this trick will lead to different offsetting if the text have differences in height)

```r
ggplot(sampledata,
       aes(x = Date, y = Value)) +
  geom_line(size = 0.75) +
  geom_hline(threshold, mapping = aes(yintercept = Value), linetype = 'longdash', color = 'grey30') +
  geom_text(threshold, mapping = aes(x = Date, y = Value, label = Note), 
            inherit.aes = FALSE, vjust = -.5) +
  scale_y_log10()
```
![image](https://user-images.githubusercontent.com/1775316/65749378-41b5d600-e106-11e9-8842-3900124d9d3d.png)

**Comment by tungmilan** [comment]
Thanks @thomasp85!
