### ISSUE TITLE
geom_dotplot "count" axis is meaningless

### ISSUE THREAD

**Issue by AmeliaMN** [tidyverse/ggplot2#3563]
Just trying to reopen #2203 because I don't understand the issue. I'd like to be able to make a dotplot where the y-axis automatically shows the count. This feels like it should be analogous to the switch between `stat="count"` and `stat="prop"` in `geom_bar()`.

**Comment by thomasp85** [comment]
While you are right that the two cases seem identical from the outside, from an implementation point of view they are very different. Scales are trained once and axes are thus fixed at rendering time. This is usually no problem, but in the case of geom_dotplot it is. The geom is dynamic in the sense that points resize and move around as you resize the plot in order to remain circular and stacked, and the y-axis has no way to react to this. In a histogram the bars will change the height together with the axis as you resize but the dotplot cannot do this. Let me know if this explains the issue
