### ISSUE TITLE
geoms react to list of colors differently

### ISSUE THREAD

**Issue by jzadra** [tidyverse/ggplot2#3586]
``` r
require(tidyverse)
#> Loading required package: tidyverse

mycolors <- list(myred = "#EC1D26", myteal = "#006B82")

#works:
mtcars %>% ggplot(aes(x = mpg, y = cyl)) + geom_point(color = mycolors["myred"])
```

![](https://i.imgur.com/gcgs9Rc.png)

``` r

#does not work:
mtcars %>% ggplot(aes(x = mpg, y = cyl)) + geom_line(color = mycolors["myred"])
#> Error in stats::complete.cases(data[c("x", "y", "size", "colour", "linetype")]): invalid 'type' (list) of argument
```

![](https://i.imgur.com/Ohe9KqZ.png)

<sup>Created on 2019-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
The question is more why the first case works rather than why the second case fails. Colors are specified as strings, not as lists containing strings. The correct way to write your code is as follows.

``` r
require(tidyverse)
#> Loading required package: tidyverse

mycolors <- list(myred = "#EC1D26", myteal = "#006B82")

mtcars %>% ggplot(aes(x = mpg, y = cyl)) + geom_point(color = mycolors[["myred"]])
```

![](https://i.imgur.com/hm4D5Np.png)

``` r
mtcars %>% ggplot(aes(x = mpg, y = cyl)) + geom_line(color = mycolors[["myred"]])
```

![](https://i.imgur.com/WgiOc35.png)

<sup>Created on 2019-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
