### ISSUE TITLE
Nonexistent color names: data not displayed without throwing warning/error

### ISSUE THREAD

**Issue by damianooldoni** [tidyverse/ggplot2#3644]
I would expect an error or at least a warning if color names are not correct. Now the data linked to such colors are not displayed. 
I suggest using a warning which informs the user that his/her color mapping has been ignored and default color scale is used.

Here a minimal reprex using the standard example in [documentation](https://ggplot2.tidyverse.org/reference/scale_manual.html): 
```r
p <- ggplot(mtcars, aes(mpg, wt)) +
+   geom_point(aes(colour = factor(cyl)))
p + scale_colour_manual(values = c("darkred", "blue", "dark green")) #dark green instead of darkgreen
```

**Comment by yutannihilation** [comment]
@thomasp85 
Though I don't have a closer look at this yet, it seems scales package unintendedly became tolerant for invalid colour names after it switched to farver by https://github.com/r-lib/scales/pull/224 mainly because of the difference below. Is it possible to add some option to `decode_colour()` to raise error when the colour name is invalid?

``` r
farver::decode_colour("foo")
#>       r  g  b
#> [1,] NA NA NA
grDevices::col2rgb("foo")
#> Error in grDevices::col2rgb("foo"): invalid color name 'foo'
```

<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

...btw, this particular example gives us another surprise. Wow...

``` r
farver::decode_colour("dark green")
#>       r  g  b
#> [1,] NA NA NA
grDevices::col2rgb("darkgreen")
#>       [,1]
#> red      0
#> green  100
#> blue     0
grDevices::col2rgb("dark green")
#>       [,1]
#> red      0
#> green  100
#> blue     0
```

<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
🤬 the ability to accept any number of colour names in col2rgb is just plain annoying...

I'm not sure that throwing an error in farver is the best way forward though? @Hadley do you have any preferences

**Comment by thomasp85** [comment]
I can get behind throwing a warning

**Comment by yutannihilation** [comment]
Yeah, I agree the behavior of `col2rgb()` is not fine. A warning sounds good.

**Comment by hadley** [comment]
Warning seems reasonable to me (although I'd also be fine with an error)

**Comment by yutannihilation** [comment]
It seems this is fixed by https://github.com/thomasp85/farver/commit/0360a086c097542c4c45781362ae56dcfeecfa9b. Thanks @thomasp85!

``` r
library(ggplot2)

p <- ggplot(mtcars, aes(mpg, wt)) +
  geom_point(aes(colour = factor(cyl)))

# dark green is accepted now
p + scale_colour_manual(values = c("darkred", "blue", "dark green")) 
```

![](https://i.imgur.com/Q2qI22g.png)

``` r

# bad names are now warned
p + scale_colour_manual(values = c("darkred", "blue", "foo")) 
#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo

#> Warning: Unknown colour name: foo
```

![](https://i.imgur.com/CvHGviP.png)

``` r
warnings()
```

<sup>Created on 2019-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@thomasp85 I think the 14 warnings here suggest an error would be better

**Comment by thomasp85** [comment]
Yeah - maybe you’re right
