### ISSUE TITLE
Inconsistent when setting different alphas

### ISSUE THREAD

**Issue by luispfonseca** [tidyverse/ggplot2#3695]
I'm trying to do a plot with geom_point and a diagonal line. When alpha is not the same for both, it seems to display weird behavior. It seems the points get very transparent while the line gets none. Is this expected?
``` r
library(ggplot2)
library(forcats)

# Looks fine, I think
ggplot(mtcars, aes(x = disp, y = mpg, color = as_factor(cyl))) + 
  geom_abline(aes(intercept = 0, slope = 1/10, alpha = 0.8)) + 
  geom_point(aes(alpha = 0.8))
```

![](https://i.imgur.com/4cjnQSC.png)

``` r

# Note that in this plot, the points are there, but very faint
# Abline seems to have no transparency
ggplot(mtcars, aes(x = disp, y = mpg, color = as_factor(cyl))) + 
  geom_abline(aes(intercept = 0, slope = 1/10, alpha = 0.8)) + 
  geom_point(aes(alpha = 0.7))
```

![](https://i.imgur.com/M4RCxuF.png)

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
You are plotting a line for each row in mtcars which, I expect, is not what you want. Scalar aesthetic mappings are repeated to the length of the layer data and since mtcars is global it also affects the abline layer.

If you move the data specification from `ggplot()` to `geom_point()` it should work.

Another thing is that I don’t think you want to set alpha inside `aes()` as it will get scaled. Put it outside if you want to set the alpha value directly

**Comment by luispfonseca** [comment]
Thank you. For future reference, here's what you suggested, looking correct:

``` r
library(ggplot2)
library(forcats)

ggplot() + 
  geom_abline(aes(intercept = 0, slope = 1/10), alpha = 0.4) + 
  geom_point(data = mtcars, aes(x = disp, y = mpg, color = as_factor(cyl)), alpha = 0.8)
```

![](https://i.imgur.com/eBtmxSL.png)

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
