### ISSUE TITLE
Inconsistency geom_abline <-> geom_hline for log10 transformation

### ISSUE THREAD

**Issue by lcougnaud** [tidyverse/ggplot2#3741]
In case a transformation is applied, the `geom_hline` function takes the intercept in the initial scale, contrary to the other geoms.

```{r examplePlot}
p1 <- ggplot(mpg, aes(displ, hwy)) + geom_point() + scale_y_log10()
```

The line is created if the intercept is specified in the original (non-transformed) scale in `geom_hline`:
```{r hline-intercept-raw}
p1 + geom_hline(yintercept = 30)
```
![ggplot_hline_intercept-raw](https://user-images.githubusercontent.com/15339154/72598199-a0020100-390f-11ea-9ef7-bd972d3b6365.png)

Contrary to the `geom_abline` behaviour:
```{r abline-intercept-log10}
p1 + geom_abline(intercept = log10(30), slope = 0)
```
![ggplot_abline_intercept-log10](https://user-images.githubusercontent.com/15339154/72598174-95476c00-390f-11ea-8f2a-e26a6dbf3ed6.png)

**Comment by clauswilke** [comment]
I suspect this happens because `yintercept` is recognized as a position aesthetic and automatically transformed whereas `intercept` is not. The simple solution would be to rename `intercept` into `yintercept`, though I'm not too fond of this approach. In general, I'm not too excited about the current mechanism of identifying position aesthetics, because it seems ad-hoc and error-prone. A better approach would allow geoms and stats to identify which aesthetics should be treated as position aesthetics.

**Comment by clauswilke** [comment]
Here is the code that catches all the y position aesthetics. I guess another fix would be to add `intercept` in line 105.
https://github.com/tidyverse/ggplot2/blob/5e388e143f3d24bbeb6ce6b892cdb91deb5af6a2/R/scale-continuous.r#L97-L110

**Comment by thomasp85** [comment]
@clauswilke the issue seems to be the `yintercept` behaviour, not the `intercept` behaviour, right?

**Comment by thomasp85** [comment]
I agree with @clauswilke that `geom_hline()`'s behaviour is correct and it is `geom_abline()` that needs to be corrected
