### ISSUE TITLE
geom_bar() is broken!

### ISSUE THREAD

**Issue by courtiol** [tidyverse/ggplot2#3866]
Adding an aesthetic `ymin` or `ymax` makes `geom_bar()` do silly things.
This is true on both the devel-version and new CRAN version.
It did not use to do that.

``` r
library(ggplot2)

d <- data.frame(x = "A", y = 1, ymin = 0.5)

ggplot(d) +
  aes(y = y, x = x, ymin = ymin) +
  geom_bar(stat = "identity")
```

![](https://i.imgur.com/5sSxRig.png)

<sup>Created on 2020-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
That is a bug with the new bidirectional geoms. For now you can overwrite the behaviour by setting `orientation = “x”` in the geom

**Comment by courtiol** [comment]
Thanks @thomasp85, I had already worked around the problem by using geom_col().
My goal was only to signal you the bug.

**Comment by yutannihilation** [comment]
Curious. A possible solution is forbidding `geom_bar(position = "identity")` (I mean, returning `geom_col()` with a warning)?

``` r
library(ggplot2)

d <- data.frame(x = "A", y = 1, ymin = 0.5, stringsAsFactors = FALSE)

ggplot(d) +
  aes(y = y, x = x, ymin = ymin) +
  geom_col()
```

![](https://i.imgur.com/Fx4xSkE.png)

<sup>Created on 2020-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
@thomasp85 
I don't understand the last sentence of the doc. `data` gets `ymin` etc at `Geom$setup_data()`, but, since `Geom$setup_params()` is called before `Geom$setup_data()`, this check seems unnecessary. What case does this expect? Actually, removing `range_is_orthogonal = FALSE` from `GeomBar` doesn't break any tests...

https://github.com/tidyverse/ggplot2/blob/bb86d3312b5244820de476f47cf38f53a0a510b1/R/utilities.r#L456-L461

If we fix this naively, I think this should be `NA` instead of `FALSE`, to ignore the check about `ymin` etc.

https://github.com/tidyverse/ggplot2/blob/bb86d3312b5244820de476f47cf38f53a0a510b1/R/geom-bar.r#L122

**Comment by thomasp85** [comment]
The reason for the confusion is that `stat_count()` provides `xmin` and `xmax` variables and I was using that to guide the detection.

But if data comes from `stat_count` the direction has already been detected so there is no need to factor these variables in
