### ISSUE TITLE
Error: stat_sf requires the following missing aesthetics: geometry

### ISSUE THREAD

**Issue by alebernnal** [tidyverse/ggplot2#3936]
Hi all!

Im trying to plot a fishing effort map following the first example in this website:  <https://globalfishingwatch.org/data-blog/working-with-our-downloadable-public-data-in-r/> 

But in the last part of the code I get this:
`Error: stat_sf requires the following missing aesthetics: geometry`

````
effort_all %>%
  ggplot() +
  geom_sf(data = world_shp, 
          fill = '#374a6d', 
          color = '#0A1738',
          size = 0.1) +
  geom_sf(data = eezs,
          color = '#374a6d',
          alpha = 0.2,
          fill = NA,
          size = 0.1) +
  geom_raster(aes(x = lon_bin, y = lat_bin, fill = log_fishing_hours)) +
  scale_fill_gradientn( "Fishing Hours",
    na.value = NA,
    limits = c(1, 5),
    colours = effort_pal(5), # Linear Green
    labels = c("10", "100", "1,000", "10,000", "100,000+"),
    values = scales::rescale(c(0, 1))) +
  labs(fill  = 'Fishing hours (log scale)',
       title = 'Global fishing effort in 2016') +
  guides(fill = guide_colourbar(barwidth = 10))
````

**Comment by clauswilke** [comment]
Hello,

the ggplot2 issue tracker is meant for clearly identifiable deficiencies or bugs in ggplot2. Questions about usage should be directed to https://community.rstudio.com/ or https://stackoverflow.com/. If discussion on either of these sites reveals that there is a clear problem with ggplot2, you're welcome to post an issue here, but at that point we'd want to see a minimal reprex that isolates the specific problem.

**Comment by antaldaniel** [comment]
I have created the same error, by making the following three scenarios, using exactly the same code:

* plot1 created in a clean environment, loading dplyr, ggplot2, knitr  [works fine]
* this plot saved into rds file, loaded and ploted in R chunk from Rmd during knitting
* plot2 created with the very same code within Rmd file's R chunk, and output saved to an .rds file - this is possible, because the ggplot code returns a correct looking object. 

However, while plot1 and plot2 correcty have the same data, the layers are different:

plot1$layers[[1]] is
mapping: fill = ~cat, geometry = ~geometry 
geom_sf: na.rm = FALSE, legend = polygon, colour = white, size = 0.05
stat_sf: na.rm = FALSE
position_identity [this is run from a simple R script]

plot2$layers[[1]] is
mapping: fill = ~cat 
geom_sf: na.rm = FALSE
stat_sf: na.rm = FALSE
position_identity   [this is run by knitting Rmarkdown file from an R chunk ]

In both cases, the data file correctly contains the same geometry, data, etc. The layers is returned differently, and the only difference is that in the second case the very same code (with the very same packages) were run from RMarkdown.

**Comment by hjager** [comment]
We are having the same issue plotting an sf object using ggplot2 and geom_sf since changing to R 4.0.  The code worked previously under R.3.6 albeit with a different simple feature object.

Shows that the geometry is there:
geometry(SS.diff)
class       : SpatialLines 
features    : 3967 
extent      : 636698.6, 700388.6, 5240642, 5337752  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=10 +datum=NAD83 +units=m +no_defs 
Warning message:
In proj4string(x) : CRS object has comment, which is lost in output

## ggplot command
> ggplot(SS.diff) + geom_sf()
Error: stat_sf requires the following missing aesthetics: geometry
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
stat_sf requires the following missing aesthetics: geometry
Backtrace:
  1. (function (x, ...) ...
  2. ggplot2:::print.ggplot(x)
  4. ggplot2:::ggplot_build.ggplot(x)
  5. ggplot2:::by_layer(function(l, d) l$compute_statistic(d, layout))
  6. ggplot2:::f(l = layers[[i]], d = data[[i]])
  7. l$compute_statistic(d, layout)
  8. ggplot2:::f(..., self = self)
  9. self$stat$compute_layer(data, params, layout)
 10. ggplot2:::f(..., self = self)
 11. ggplot2:::check_required_aesthetics(...)
Run `rlang::last_trace()` to see the full context.

Below - version information
> r.ver
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.0"

$year
[1] "2020"

$month
[1] "04"

$day
[1] "24"

$`svn rev`
[1] "78286"

$language
[1] "R"

$version.string
[1] "R version 4.0.0 (2020-04-24)"

$nickname
[1] "Arbor Day"

**Comment by antaldaniel** [comment]
I think that the problem is caused by how sf is joining tibbles and spatial objects.  Unfortunately, sf is overwriting the `dplyr::left_join`, `dplyr::inner_join` functions with a not exported [sf::left_join.sf ](https://r-spatial.github.io/sf/reference/tidyverse.html)method, which in turn relies on a number of not exported internal functions.  

I realized this because one of my package relies on sf an dplyr, too.    While I wanted to avoid importing the entire sf for a join, I could not do otherwise.  I find it a very bad idea that instead of creating a `spatial_left_join()` function the `dplyr::left_join` function is tempered with.

**Comment by phdykd** [comment]
what is the solution for this error? I am getting same issue.
Thanks

**Comment by hjager** [comment]
I ended up separating the geometry, merging the non-geometry data, and recreating a spatial object.

**Comment by cramjaco** [comment]
I encountered this problem as well. I found that in my case I was forgetting to specify that `returnclass="sf"` when I downloaded y data from natural earth. So in my case to get something like world_shp, I needed to specify

```
world_shp <- ne_download(scale = 10, type = "ocean", category = "physical", returnclass = "sf")
```

**Comment by gklarenberg** [comment]
As an FYI - July 2021 and this is still an issue. @antaldaniel is right, when I `left_join` a tibble and an sf, the result is a tibble.
To solve it, I run `st_as_sf()` on the object I created from a `left_join()`. Not ideal, but it works.

**Comment by clauswilke** [comment]
To be clear: This is not a ggplot2 bug. The problem arises with sf and should be reported there as a bug. Workarounds are switching the order of the join (provide the table with the geometry data as the first input to `left_join()`) or manually mapping the geometry column. See reprex below.

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1

US_counties <- readRDS(url("https://wilkelab.org/SDS375/datasets/US_counties.rds")) %>%
  rename(FIPS = GEOID)

US_census <- read_csv(
  "https://wilkelab.org/SDS375/datasets/US_census.csv",
  col_types = cols(FIPS = "c")
)

# works
US_counties %>%
  left_join(US_census, by = "FIPS") %>%
  ggplot() +
  geom_sf(aes(fill = home_ownership))
```

![](https://i.imgur.com/qBL8pzZ.png)

``` r
# doesn't work, left_join has stripped the sf class info
US_census %>%
  left_join(US_counties, by = "FIPS") %>%
  ggplot() +
  geom_sf(aes(fill = home_ownership))
#> Error: stat_sf requires the following missing aesthetics: geometry

# works, we can manually map the geometry column
US_census %>%
  left_join(US_counties, by = "FIPS") %>%
  ggplot() +
  geom_sf(aes(fill = home_ownership, geometry = geometry))
```

![](https://i.imgur.com/FnCLbFe.png)

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hjager** [comment]
Thank you.

From: Claus Wilke ***@***.***>
Sent: Monday, August 2, 2021 12:27 PM
To: tidyverse/ggplot2 ***@***.***>
Cc: Jager, Henriette ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [tidyverse/ggplot2] Error: stat_sf requires the following missing aesthetics: geometry (#3936)


To be clear: This is not a ggplot2 bug. The problem arises with sf and should be reported there as a bug. Workarounds are switching the order of the join (provide the table with the geometry data as the first input to left_join()) or manually mapping the geometry column. See reprex below.

library(tidyverse)

library(sf)

#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1



US_counties <- readRDS(url("https://wilkelab.org/SDS375/datasets/US_counties.rds")) %>%

  rename(FIPS = GEOID)



US_census <- read_csv(

  "https://wilkelab.org/SDS375/datasets/US_census.csv",

  col_types = cols(FIPS = "c")

)



# works

US_counties %>%

  left_join(US_census, by = "FIPS") %>%

  ggplot() +

  geom_sf(aes(fill = home_ownership))

[https://camo.githubusercontent.com/ceff88fdd3f44a64e2565bd2cfcedd8de9a6c59d562700aed537792bca98b309/68747470733a2f2f692e696d6775722e636f6d2f71424c38707a5a2e706e67]<https://camo.githubusercontent.com/ceff88fdd3f44a64e2565bd2cfcedd8de9a6c59d562700aed537792bca98b309/68747470733a2f2f692e696d6775722e636f6d2f71424c38707a5a2e706e67>

# doesn't work, left_join has stripped the sf class info

US_census %>%

  left_join(US_counties, by = "FIPS") %>%

  ggplot() +

  geom_sf(aes(fill = home_ownership))

#> Error: stat_sf requires the following missing aesthetics: geometry



# works, we can manually map the geometry column

US_census %>%

  left_join(US_counties, by = "FIPS") %>%

  ggplot() +

  geom_sf(aes(fill = home_ownership, geometry = geometry))

[https://camo.githubusercontent.com/b5e7c63c8a5371d26d59ece9d0b6ab37aa4ed0ff42c3c71cee67ba166969e019/68747470733a2f2f692e696d6775722e636f6d2f466e434c6246652e706e67]<https://camo.githubusercontent.com/b5e7c63c8a5371d26d59ece9d0b6ab37aa4ed0ff42c3c71cee67ba166969e019/68747470733a2f2f692e696d6775722e636f6d2f466e434c6246652e706e67>

Created on 2021-08-02 by the reprex package<https://reprex.tidyverse.org> (v2.0.0)

**Comment by clauswilke** [comment]
Actually, thinking some more about it, there's probably not much sf can do about left_join() since S3 methods don't support double dispatch. But `right_join()` is an option if `left_join()` is joining in the wrong direction.

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1

US_counties <- readRDS(url("https://wilkelab.org/SDS375/datasets/US_counties.rds")) %>%
  rename(FIPS = GEOID)

US_census <- read_csv(
  "https://wilkelab.org/SDS375/datasets/US_census.csv",
  col_types = cols(FIPS = "c")
)

US_counties %>%
  right_join(US_census, by = "FIPS") %>%
  ggplot() +
  geom_sf(aes(fill = home_ownership))
```

![](https://i.imgur.com/DVlwaIT.png)

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by colebaril** [comment]
Hello,

Writing to let you know that this bug is still occurring as of March 2024, and is a pretty major bug. I managed to fix my issue by swapping geom_sf to geom_polygon.

**Comment by thomasp85** [comment]
@colebaril if you are reporting the same issue as above then it has been established that it is not an issue in ggplot2 and it would follow that no changes in ggplot2 has been made to address it
