### ISSUE TITLE
conflict of `coord_flip()` with `annotation_logticks()`

### ISSUE THREAD

**Issue by DSLituiev** [tidyverse/ggplot2#3954]
This behaves exactly like the closed issue #881, still here in ggplot2 version 3.3.0

Using a bit modified [example](https://ggplot2.tidyverse.org/reference/annotation_logticks.html)

```r
a <- ggplot(msleep, aes(bodywt, brainwt)) +
 geom_point(na.rm = TRUE) +
 scale_x_log10(
   breaks = scales::trans_breaks("log10", function(x) 10^x),
   labels = scales::trans_format("log10", scales::math_format(10^.x))
 ) +
 scale_y_log10(
   breaks = scales::trans_breaks("log10", function(x) 10^x),
   labels = scales::trans_format("log10", scales::math_format(10^.x))
 )
```
This works:
```r
a + coord_flip()
```
And this works:
```r
a + annotation_logticks()
```
 Now,
```r
a + coord_flip() + annotation_logticks()
```

returns error: `Error in unit(xticks$x, "native") : 'x' and 'units' must have length > 0`

**Comment by clauswilke** [comment]
I can confirm this problem.
``` r
library(ggplot2)

a <- ggplot(msleep, aes(bodywt, brainwt)) +
  geom_point(na.rm = TRUE) +
  scale_x_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  )

a + annotation_logticks()
```

![](https://i.imgur.com/LzzNPtj.png)

``` r
a + annotation_logticks() + coord_flip()
#> Error in unit(xticks$x, "native"): 'x' and 'units' must have length > 0
```
<sup>Created on 2020-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It arises because `annotation_logticks()` doesn't properly use the `coord` to figure out where to draw ticks. It just assumes that the x axis is bottom/top and the y axis is left/right. See e.g.:
https://github.com/tidyverse/ggplot2/blob/c7f9398391a9f94b38fe8b691e031d096afc6199/R/annotation-logticks.r#L136-L142

**Comment by clauswilke** [comment]
The correct way to obtain the ranges would probably be something like this (from `geom_hline()`):
https://github.com/tidyverse/ggplot2/blob/c7f9398391a9f94b38fe8b691e031d096afc6199/R/geom-hline.r#L48-L51

**Comment by clauswilke** [comment]
Or just `coord$range(panel_params)`, not sure off the top of my head.
