### ISSUE TITLE
Misaligned date axis for some custom breaks functions

### ISSUE THREAD

**Issue by geotheory** [tidyverse/ggplot2#3965]
A custom breaks function on the date axis seem to mis-align the breaks and labels.  Another does not.  But corresponding date vector inputs for both functions work fine.  

Not sure if this has already been reported - I've looked and found [this issue](https://github.com/tidyverse/ggplot2/issues/814), but it's old.

Reproducible example - note how the 30 March break shifts off the maximum data point it should align with.

```
require(tidyverse)

set.seed(pi)
df <- data.frame(date = Sys.Date() - 0:29, price = runif(30))
p <- ggplot(df, aes(date, price)) + geom_line() +  geom_point() + coord_fixed(ratio=5)

# max price is 0.9101477 on 30 March
df %>% filter(price == max(price))
#>         date     price
#> 1 2020-03-30 0.9101477

weekend_breaks_correct <- function(x) {
  mondays <- scales::fullseq(x, "1 week")
  fridays <- mondays - lubridate::days(3)
  sort(c(mondays, fridays))
}

weekend_breaks_misaligned <- function(x){
  x <- seq(x[1], x[2], by=1)
  x[weekdays(x) %in% c('Monday','Friday')]
}

( breaks_cor = weekend_breaks_correct(range(df$date)) )
#>  [1] "2020-03-20" "2020-03-23" "2020-03-27" "2020-03-30" "2020-04-03"
#>  [6] "2020-04-06" "2020-04-10" "2020-04-13" "2020-04-17" "2020-04-20"
#> [11] "2020-04-24" "2020-04-27"
( breaks_mis = weekend_breaks_misaligned(range(df$date)) )
#> [1] "2020-03-30" "2020-04-03" "2020-04-06" "2020-04-10" "2020-04-13"
#> [6] "2020-04-17" "2020-04-20" "2020-04-24"

# correct function
p + scale_x_date(date_labels = "%a %b %d", breaks = weekend_breaks_correct)
```
![image](https://user-images.githubusercontent.com/1282581/80304289-cbb54280-87ac-11ea-86ed-841f91d1a297.png)

```
# misalisgned function
p + scale_x_date(date_labels = "%a %b %d", breaks = weekend_breaks_misaligned)
```

![image](https://user-images.githubusercontent.com/1282581/80304312-d8d23180-87ac-11ea-85a8-626132b36ecd.png)

```
# vectors are both correct
p + scale_x_date(date_labels = "%a %b %d", breaks = breaks_cor)
p + scale_x_date(date_labels = "%a %b %d", breaks = breaks_mis)
```

![image](https://user-images.githubusercontent.com/1282581/80304325-e687b700-87ac-11ea-843f-66d66be2ea76.png)

**Comment by yutannihilation** [comment]
Thanks, confirmed. Here's a bit different version of the reprex. Maybe some transformation or back-transformation of the Date scale doesn't handle the expansion properly...?

``` r
library(ggplot2)
library(patchwork)

# In my locale, there's no "Monday" and "Friday" :P
Sys.setlocale(locale = "C")
#> [1] "LC_CTYPE=C;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=ja_JP.UTF-8;LC_PAPER=ja_JP.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=ja_JP.UTF-8;LC_IDENTIFICATION=C"

set.seed(pi)
df <- data.frame(date = Sys.Date() - 0:29, price = runif(30))
p <- ggplot(df, aes(date, price)) + geom_line() +  geom_point() + coord_fixed(ratio=5)

weekend_breaks_correct <- function(x) {
  mondays <- scales::fullseq(x, "1 week")
  fridays <- mondays - lubridate::days(3)
  res <- sort(c(mondays, fridays))
  
  print(res)
  res
}

weekend_breaks_misaligned <- function(x){
  x <- seq(x[1], x[2], by=1)
  res <- x[weekdays(x) %in% c('Monday','Friday')]
  
  print(res)
  res
}

p1 <- p + scale_x_date(date_labels = "%a %b %d", breaks = weekend_breaks_misaligned, expand = c(0.05, 0.05))
p2 <- p + scale_x_date(date_labels = "%a %b %d", breaks = weekend_breaks_misaligned, expand = c(0, 0))

p1 / p2
```

![](https://i.imgur.com/IFXy5Eu.png)

    #>  [1] "2020-03-27" "2020-03-30" "2020-04-03" "2020-04-06" "2020-04-10"
    #>  [6] "2020-04-13" "2020-04-17" "2020-04-20" "2020-04-24" "2020-04-27"
    #>  [1] "2020-03-27" "2020-03-30" "2020-04-03" "2020-04-06" "2020-04-10"
    #>  [6] "2020-04-13" "2020-04-17" "2020-04-20" "2020-04-24" "2020-04-27"
    #> [1] "2020-03-30" "2020-04-03" "2020-04-06" "2020-04-10" "2020-04-13"
    #> [6] "2020-04-17" "2020-04-20" "2020-04-24" "2020-04-27"
    #> [1] "2020-03-30" "2020-04-03" "2020-04-06" "2020-04-10" "2020-04-13"
    #> [6] "2020-04-17" "2020-04-20" "2020-04-24" "2020-04-27"

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by javlon** [comment]
@yutannihilation's assumption is almost right. 
Misalignment is appearing due to non-zero decimal part on Date objects [e.g. `structure(c(18455, 18455.5, 18455.7), class = "Date")` are the same day, but they have different numeric values with the same integer part].

From Date object's documentation:
> It is intended that the date should be an integer, but this is not enforced in the internal representation. Fractional days will be ignored when printing.

In above example breaks contain 0.5 fractional part in numeric presentation. That's why breaks moved a little bit to right side.

In above example, first time fractional part appears after [expanding limits](https://github.com/tidyverse/ggplot2/blob/cc7ac3b5056ef26ae4472b26b347f9ca5d5228a0/R/coord-cartesian-.r#L203). So, user's breaks function obtain [transformed](https://github.com/tidyverse/ggplot2/blob/cc7ac3b5056ef26ae4472b26b347f9ca5d5228a0/R/scale-.r#L613) bad date objects and also [return](https://github.com/tidyverse/ggplot2/blob/cc7ac3b5056ef26ae4472b26b347f9ca5d5228a0/R/scale-.r#L635) bad date objects. [Reverse transformation](https://github.com/tidyverse/ggplot2/blob/cc7ac3b5056ef26ae4472b26b347f9ca5d5228a0/R/scale-.r#L641) of breaks is also doesn't check to non-zero fractional part.

There are three solutions to this "bug":
* coerce results of `breaks` function to integer for date axis (after this [line](https://github.com/tidyverse/ggplot2/blob/cc7ac3b5056ef26ae4472b26b347f9ca5d5228a0/R/scale-.r#L641)).
* coerce [expanding limits](https://github.com/tidyverse/ggplot2/blob/cc7ac3b5056ef26ae4472b26b347f9ca5d5228a0/R/coord-cartesian-.r#L203) to integer for date axis. It will guarantee that `breaks` function obtain numeric presentation of date without decimal part. And throw warning if user's `breaks` function return date object with non-zero decimal part on internal representation.
*  fix it inside [transformation functions](https://github.com/r-lib/scales/blob/350b0dc949de5a51afb3df2f32613a473d1be4af/R/trans-date.r#L15) by rounding down numeric values. In this case transformed and reverse transformed values will differ but same integer part.
