### ISSUE TITLE
Points fill in legend

### ISSUE THREAD

**Issue by DrrDom** [tidyverse/ggplot2#4049]
I noticed that if I use fill with `geom_point` I have to manually set the shape of the legend point to make the fill color visible

```r
library(ggplot2)

set.seed(42)
d <- data.frame(x = rnorm(12), y = rnorm(12), 
                shape = rep(LETTERS[1:4], each = 3), 
                fill = rep(letters[1:3], 4))

ggplot(d, aes(x = x, y = y, shape = shape, fill = fill)) +
  geom_point(size = 3) +
  scale_shape_manual(values = 21:25) +
  theme(legend.box = "horizontal")
```

![0](https://user-images.githubusercontent.com/4629017/83974052-af97db80-a8ea-11ea-96bc-c34104f2cd9f.png)

```r
ggplot(d, aes(x = x, y = y, shape = shape, fill = fill)) +
  geom_point(size = 3) +
  scale_shape_manual(values = 21:25) +
  guides(fill = guide_legend(override.aes=list(shape=21))) +
  theme(legend.box = "horizontal")
```
![1](https://user-images.githubusercontent.com/4629017/83974053-b0c90880-a8ea-11ea-9c03-6dfd8d68ebe8.png)

It seems to be reasonable to change the default behavior in such cases, because it is not obvious and requires search for a solution over the internet.

**Comment by thomasp85** [comment]
Yeah, this is clearly a bug

**Comment by thomasp85** [comment]
Hmm... this is actually not easy to fix. There is no way in the legend key drawing code where it is given that the values comes from the defaults or not.

Because of this we cannot selectively use another shape if a fill is given... @yutannihilation, @clauswilke, @Hadley any good ideas?

**Comment by thomasp85** [comment]
The best approach (but also rather involved) is to modify

https://github.com/tidyverse/ggplot2/blob/668a51eaa1011f737dc6e2795f3265e795cc9a3e/R/guide-legend.r#L267-L276

So that instead of using `geom$use_defaults()` it would use another another function that fills in default values from values actually used by the layer... This would require the layer to keep track of aesthetic values used and will have other downsides in that e.g. a red glyph colour would be used in the shape legend instead of the more neutral black

All in all I'm not sure this is worth "fixing" since it would open up other issues

**Comment by hadley** [comment]
Could we change the shape if `colour` is constant and `fill` is varying?

**Comment by thomasp85** [comment]
The keys are created one by one, so there is no concept of constant vs varying...

Another issue is that if a global fill is set, e.g. to fill a boxplot and the points are drawn with the default 19 shape you don't want the legend to show points with a coloured center

**Comment by clauswilke** [comment]
My opinion: When people venture into shapes 21-25 they're accepting that they'll have to deal with minor inconveniences such as this one. It's an advanced use case that can lead to unintuitive results on occasion.

**Comment by hadley** [comment]
Yeah, in that case I'm with @clauswilke.

**Comment by thomasp85** [comment]
Ok, let's close it
