### ISSUE TITLE
Unexpected warning about missing values when setting xlim and ylim

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/ggplot2#4083]
Setting `xlim()` and `ylim()` gives unexpected warning about missing values when there are no missing values in the data.

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.3.2'

# works as expected
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 3)
```

![](https://i.imgur.com/QsRsXTm.png)

``` r

# note min and max
summary(mtcars$mpg)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   10.40   15.43   19.20   20.09   22.80   33.90

# gives warning about missing values
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 3) +
  xlim(0, 100)
#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/aEeRBhq.png)

``` r

# make one value NA and try again
mtcars2 <- mtcars
mtcars2[1,1] <- NA

ggplot(mtcars2, aes(x = mpg)) +
  geom_histogram(binwidth = 3)
#> Warning: Removed 1 rows containing non-finite values (stat_bin).
```

![](https://i.imgur.com/0gqV2Xq.png)

``` r

ggplot(mtcars2, aes(x = mpg)) +
  geom_histogram() +
  xlim(0, 100)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 1 rows containing non-finite values (stat_bin).

#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/g6qYF9U.png)

``` r

# same issue with ylim
ggplot(mtcars, aes(y = mpg)) +
  geom_histogram(binwidth = 3)
```

![](https://i.imgur.com/avuvYE8.png)

``` r

ggplot(mtcars, aes(y = mpg)) +
  geom_histogram(binwidth = 3) +
  ylim(0, 100)
#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/a0L0BcU.png)

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Thanks. `StatBin` calculates bin over the scale range, but since the right-most and left-most bars are over the range, they are removed with the default `oob`. Honestly, I'm unhappy with the current behaviour, but we concluded that this issue is too complex and not worth fixing (c.f. https://github.com/tidyverse/ggplot2/issues/2887#issuecomment-485721611). So, let me close this issue. A workaround is to specify `oob = scales::keep_oob`.

``` r
library(ggplot2)

d <- data.frame(x = 1)

p <- ggplot(d, aes(x)) +
  geom_histogram(bins = 3)

layer_data(p)
#>   y count x xmin xmax density ncount ndensity flipped_aes PANEL group ymin ymax
#> 1 1     1 1 0.95 1.05      10      1        1       FALSE     1    -1    0    1
#>   colour   fill size linetype alpha
#> 1     NA grey35  0.5        1    NA

layer_data(p + scale_x_continuous(limits = c(0, 3), oob = scales::oob_keep))
#>   y count   x  xmin xmax   density ncount ndensity flipped_aes PANEL group ymin
#> 1 0     0 0.0 -0.75 0.75 0.0000000      0        0       FALSE     1    -1    0
#> 2 1     1 1.5  0.75 2.25 0.6666667      1        1       FALSE     1    -1    0
#> 3 0     0 3.0  2.25 3.75 0.0000000      0        0       FALSE     1    -1    0
#>   ymax colour   fill size linetype alpha
#> 1    0     NA grey35  0.5        1    NA
#> 2    1     NA grey35  0.5        1    NA
#> 3    0     NA grey35  0.5        1    NA

# xlim(0, 3) is a shortcut of this; default `scales::censor` removes all the data that are outside of the limits
layer_data(p + scale_x_continuous(limits = c(0, 3), oob = scales::censor))
#>   y count   x xmin xmax   density ncount ndensity flipped_aes PANEL group ymin
#> 1 0     0 0.0   NA 0.75 0.0000000      0        0       FALSE     1    -1    0
#> 2 1     1 1.5 0.75 2.25 0.6666667      1        1       FALSE     1    -1    0
#> 3 0     0 3.0 2.25   NA 0.0000000      0        0       FALSE     1    -1    0
#>   ymax colour   fill size linetype alpha
#> 1    0     NA grey35  0.5        1    NA
#> 2    1     NA grey35  0.5        1    NA
#> 3    0     NA grey35  0.5        1    NA
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, I had to read that over a few times to understand the issue. Indeed seems unintuitive but I don't have a better suggestion at this point either.

Part of my confusion was also due to the difference between the messages referencing `non-finite` vs. `missing` values. The [docs](https://ggplot2.tidyverse.org/reference/lims.html) say "By default, any values outside the limits specified are replaced with `NA`. Be warned that this will remove data outside the limits and this can produce unintended results." so I would have expected the same wording for true `NA`s in the data and these "artificial" `NA`s. I imagine something else is going on here that I can't quite wrap my head around.

**Comment by yutannihilation** [comment]
Ah, it's not that the `NA` was removed as "non-finite" because it was artificial; it's just the data gets cleaned up multiple times.

Infinite values and missing values are removed from the data before Stat calculates over the data. (Note that a missing value is not a finite value as `is.finite(NA)` returns `FALSE`. This feels a bit confusing to me, too...).

https://github.com/tidyverse/ggplot2/blob/7d05fa3b6cda40fe645fe04090485275a0666979/R/stat-.r#L88-L92

Then, the data is calculated and the result is chopped by the Scale with the limits. If the data is over the limits, the default `oob` (`scales::censor()`) replaces it with `NA`, accordingly the row will be removed when the corresponding Geom draws it.

https://github.com/tidyverse/ggplot2/blob/7d05fa3b6cda40fe645fe04090485275a0666979/R/scale-.r#L573-L574

https://github.com/tidyverse/ggplot2/blob/7d05fa3b6cda40fe645fe04090485275a0666979/R/geom-.r#L67-L71

**Comment by yutannihilation** [comment]
By the way, I found my comment above

> A workaround is to specify `oob = scales::keep_oob`.

was wrong. Sorry. What we need was `coord_cartesian(xlim = c(0, 100))` instead of `xlim(0, 100)` (I took a peek on the answer of https://github.com/tidyverse/ggplot2/pull/3421 :roll_eyes: )

``` r
library(ggplot2)

ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 3) +
  coord_cartesian(xlim = c(0, 100))
```

![](https://i.imgur.com/UGhvX6O.png)

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by teunbrand** [comment]
I don't think the usage of `scales::oob_keep()` was wrong, maybe just misspelled. It was introduced exactly for that purpose (see https://github.com/r-lib/scales/issues/255) in scales v1.1.1, which was only released after the answer you mentioned.

**Comment by yutannihilation** [comment]
Oh, thanks! Yeah, maybe I wasn't wrong, but I think the primary advice should be "use coord if you want to zoom" because it's simpler than understanding how `oob` works. I love `oob_keep()`, thanks for adding it!
