### ISSUE TITLE
facets fail with uninformative error for some column names

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#4138]
If one tries to facet a plot using columns with name "COL", "ROW", "PANEL", "SCALE_X" or "SCALE_Y", ggplot2 fails with a rather obscure error. 

``` r
library(ggplot2)

mtcars$ROW <- mtcars$cyl
ggplot(mtcars, aes(hp, mpg)) +
   geom_point() +
   facet_grid(ROW ~  am) 
#> Error: `scale_id` must not be `NA`
```

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Thanks, confirmed. This seems a long-standing known issue. c.f. #838 We might not be able to fix this easily, but maybe we can show some informative error message.

**Comment by thomasp85** [comment]
it is rather unfortunate and I think we should look into a fix... This should not be unsurmountable as it is only a weird interaction between the layout data.frame (containing the reserved words) and the column names

Quick thought would be to keep all facet panel data values in a nested data.frame instead of as separate columns (which creates the issue due to multiple identical column names)

**Comment by kotliary** [comment]
Spend a lot of time today debugging a problem with the PANEL column in my data.  Just a warning that the input data frame has column(s) with these names would be good enough.

**Comment by eliocamp** [comment]
> Just a warning that the input data frame has column(s) with these names would be good enough.

How about if we just make it work? :wink:  

With [this PR](https://github.com/tidyverse/ggplot2/pull/4315) : 
```r
library(ggplot2)
mtcars$PANEL <- mtcars$cyl
ggplot(mtcars, aes(hp, mpg)) +
  geom_point() +
  facet_grid(PANEL ~  am) 
```
![image](https://user-images.githubusercontent.com/8617595/104379221-edf01b80-5507-11eb-972a-a6d545536dc6.png)

**Comment by kotliary** [comment]
Looks great. 👍 Hope the PR will be successful.
