### ISSUE TITLE
Can't change horizontal justification for y axis title

### ISSUE THREAD

**Issue by jernest1** [tidyverse/ggplot2#4162]
I'm not able to change the horizontal justification for a y axis title, in my case when I'm using angle = 0. I've tried using the `hjust` and `margin` parameters but they don't seem to affect anything. This issue is noticeable when I put two plots on the same page going top to bottom and want to right-align the y axis titles. `vjust` does work, however.
```r
library(ggplot2)
library(cowplot)
df <- data.frame(x = 1, y = 1)
p1 <- ggplot(df, aes(x, y)) +
  ylab("y label") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1))
p2 <- ggplot(df, aes(x, y)) +
  ylab("longer y label") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1))
plot_grid(p1, p2, ncol = 1, align = "hv")
```
![image](https://user-images.githubusercontent.com/13725669/89469616-d1c1a480-d747-11ea-86aa-ce1472d33c63.png)

**Comment by clauswilke** [comment]
This type of question is more appropriate for the RStudio Forums or Stackoverflow. Please ask there first. And in particular, since your problem involves an add-on package, before filing an issue with ggplot2 we would want you to verify that the problem is actually caused by ggplot2 itself and not by the add-on package.
