### ISSUE TITLE
ggplot breaks when facet variable is `POSIXct` with `tz` attribute specified

### ISSUE THREAD

**Issue by edzer** [tidyverse/ggplot2#4175]
This came up [here](https://github.com/r-spatial/stars/issues/305), and I think I can reduce it to the presence of a time zone attribute in a `POSIXct` vector. Not sure if this is a `vctrs` issue or `ggplot2`, but this is where it showed up. 

Minimal reprex:
```r
library(ggplot2)
x = data.frame(x = 1:6, y = 6:1, time = strptime("2020-09-14",format="%Y-%m-%d") + 1:6)
ggplot(x) + geom_point(aes(x=x, y=y)) +facet_wrap(~time) # OK
x = data.frame(x = 1:6, y = 6:1, time = strptime("2020-09-14",format="%Y-%m-%d",tz="UTC") + 1:6)
ggplot(x) + geom_point(aes(x=x, y=y)) +facet_wrap(~time)
# Error: `scale_id` must not be `NA`
# Backtrace:
#     █
#  1. ├─(function (x, ...) ...
#  2. └─ggplot2:::print.ggplot(x)
#  3.   ├─ggplot2::ggplot_build(x)
#  4.   └─ggplot2:::ggplot_build.ggplot(x)
#  5.     └─layout$train_position(data, scale_x(), scale_y())
#  6.       └─ggplot2:::f(..., self = self)
#  7.         └─self$facet$train_scales(...)
#  8.           └─ggplot2:::f(...)
#  9.             └─ggplot2:::scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales)
# Execution halted
```

**Comment by yutannihilation** [comment]
Thanks, confirmed.

On this line, `facet_vals` and `layout` doesn't match, since the latter got stripped its timezone. This results in missing `scale_id`.

https://github.com/tidyverse/ggplot2/blob/3be0acce79dc295d5470d949c60de1b9c84a6fc9/R/facet-wrap.r#L207

It seems the problem comes from `rbind_dfs()`, which is used here:

https://github.com/tidyverse/ggplot2/blob/3be0acce79dc295d5470d949c60de1b9c84a6fc9/R/layout.R#L46

``` r
x = data.frame(x = strptime("2020-09-14",format="%Y-%m-%d",tz="UTC") + 1:2)
x
#>                     x
#> 1 2020-09-14 00:00:01
#> 2 2020-09-14 00:00:02
ggplot2:::rbind_dfs(list(x))
#> Warning: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame'
#> when loading 'dplyr'
#>                     x
#> 1 2020-09-13 15:00:01
#> 2 2020-09-13 15:00:02
```

<sup>Created on 2020-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
hopefully this will all be fixed when we begin using vctrs
