### ISSUE TITLE
GGPlot2 axis ticks and tick labels not following specification

### ISSUE THREAD

**Issue by jam1015** [tidyverse/ggplot2#4181]
---
I am trying to set perfectly black ticks and labels in ggplot2 but they are coming with a very slight grey tint. Here is an example: 

```r
library(tidyverse)

mpg %>% ggplot(aes(x = cty, y = cyl)) + geom_point() + theme_classic() +
  theme(line =  element_line(size = 4,color = "black",lineend = "square"),
        text = element_text(color = "black", face = "bold",size = 24))

```
![grey_text](https://user-images.githubusercontent.com/2414185/91222849-c5e55480-e6ed-11ea-97b6-64584898742b.png)

The difference in color is subtle but noticeable.

**Comment by karawoo** [comment]
You need to add `axis.ticks = element_line(color = "black")` to your call to `theme()` because the theme you're using sets the axis tick color directly and doesn't inherit it from `line`.

In the future, this type of question is a better fit for [RStudio Community](https://community.rstudio.com/) or StackOverflow. The ggplot2 issue tracker is intended for bug reports and feature requests.
