### ISSUE TITLE
Text will blur with a red-like color: when geom_text() for 1 single text

### ISSUE THREAD

**Issue by DawnEve** [tidyverse/ggplot2#4202]
![ggplot2](https://user-images.githubusercontent.com/5974903/93463585-88ee3580-f91a-11ea-9098-679e2613bfda.png)

Left: text on the figure blurs with a red-like color;
Right: normal text effect, **which I want.**

Below is the code. In fact, when annotating p-value, I prefer to use Method 1, as it is simpler than Method 2.
But Method 1 don't print text as clear as Method 2, when there is only one single text to show.

```r
library(ggplot2) #ggplot 3.3.2
p=ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species))+
  geom_point()+theme_bw();p
# Method(1) add text in picture, text NOT normal: text blurs with a red-like color
p+geom_text(aes(x=4.5, y=4.2, label="setosa"), color='black' )

# Method(2) add text in picture, text normal
df1=data.frame( x=4.5, y=4.2, label="setosa" )
p+geom_text(data=df1, aes(x, y, label=label), color='black' )
```

**Comment by teunbrand** [comment]
The issue with the text is probably that it is in actuality 150 copies of the text at the same location. This is because the `geom_text()` tries to map your data to the aesthetics, thus resulting in `nrow(iris)` copies. The subpixel antialiasing becomes very prominent due to the multiple copies, giving the red (and blue) glow. What you're probably looking for is the `annotate()` function, which interprets input literally instead of in the context of the data.

**Comment by DawnEve** [comment]
Yes, I think you are right. If no data specified, geom_text() will use the previous iris.
I should use annotate instead. 
Thanks.
