### ISSUE TITLE
after_scale() in the initial ggplot() call

### ISSUE THREAD

**Issue by mikmart** [tidyverse/ggplot2#4260]
Consider the `after_scale()` example from `?aes_eval`:

``` r
library(ggplot2) # tidyverse/ggplot2@a132727

ggplot(mpg, aes(class, hwy)) +
  geom_boxplot(aes(colour = class, fill = after_scale(alpha(colour, 0.4))))
```

![](https://i.imgur.com/fgAIK0X.png)

Moving the colour and fill specification form the geom to the initial `ggplot()` call causes the fill to not be mapped at all:

``` r
ggplot(mpg, aes(class, hwy, colour = class, fill = after_scale(alpha(colour, 0.4)))) +
  geom_boxplot()
```

![](https://i.imgur.com/kqS2xQ8.png)

**Comment by yutannihilation** [comment]
Thanks, this seems because `Layer$compute_geom_2()` refers only to the layer's mapping and ignores `plot$mapping`.

https://github.com/tidyverse/ggplot2/blob/a132727e9de06dc43828b53de0257aa3fb76b33d/R/layer.r#L356-L364

I think `compute_geom_2()` needs to take `plot` as we do with `map_statistics()`.

https://github.com/tidyverse/ggplot2/blob/a132727e9de06dc43828b53de0257aa3fb76b33d/R/plot-build.r#L73
