### ISSUE TITLE
Default colour aesthetic in geom_polygon() set to string "NA"?

### ISSUE THREAD

**Issue by mdlama** [tidyverse/ggplot2#4279]
There might be a bug in the default aesthetics for `geom_polygon()`.  It appears to be set to the string "NA" rather than NA.  Here's a minimal reprex:

``` r
library(ggplot2)

geom_polygon()$geom$default_aes
#> Aesthetic mapping: 
#> * `colour`   -> "NA"
#> * `fill`     -> "grey20"
#> * `size`     -> 0.5
#> * `linetype` -> 1
#> * `alpha`    -> NA
#> * `subgroup` -> NULL
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by yutannihilation** [comment]
Good catch. Probably `"NA"` still works because farver interprets it the same as `NA` (this is consistent with the behaviour of `grDevices::col2rgb()`), but I agree this should be `NA`. Do you want to contribute a pull request?

``` r
farver::decode_colour(NA)
#>       r  g  b
#> [1,] NA NA NA
farver::decode_colour("NA")
#>       r  g  b
#> [1,] NA NA NA
```

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdlama** [comment]
Sure!  I'll reference this issue in the pull request. Thanks!
