### ISSUE TITLE
Registered S3 method overwritten by 'GGally'

### ISSUE THREAD

**Issue by BatoolMM** [tidyverse/ggplot2#4304]
Not sure if this is the right place to post this issue. `ggplot` used to work  perfectly fine for ages but once I installed `ggpolt2` after `ggbio`, I encounter this error:

```
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
```
Which makes the console stuck forever in the RStudio. I tried the same thing on my sister's MacBook and had the same error. 

I used the following to install the packages:
```
install.packages("ggplot2")
BiocManager::install("ggbio")
```
To resolve the problem, I re-installed both R, all RFrameworks, and RStudio at least 3 times but still, the same problem occurs after installing `ggpolt2` after `ggbio`. Things go back to normal if I remove either `ggplot2` or `ggbio`.
I use R-4.0.3, RStudio v1.3.

**Comment by clauswilke** [comment]
Since ggbio is an extension package to ggplot2, I think you should report there. Maybe it pulls in an outdated version of GGally. When extension packages start overwriting our core functions (such as `+.gg`) we can't guarantee that anything works anymore, it's 100% on them.

Also, I notice that ggbio lists ggplot2 under `Depends`, so when you install ggbio you automatically install ggplot2 also. Not sure why you'd want to install it separately.
https://bioconductor.org/packages/release/bioc/html/ggbio.html

**Comment by BatoolMM** [comment]
Thank you for replying quickly. 
I happen to install `ggbio` recently when I already have `ggplot2`. That's why I mentioned that the problem happens if `ggbio` is installed after `ggplot2`. Thank you again @clauswilke and enjoy the holidays! ☃️ 🎅.
