### ISSUE TITLE
fullrange makes fit line shorter instead of longer in geom_smooth and throws warnings

### ISSUE THREAD

**Issue by dperlman** [tidyverse/ggplot2#4322]
When the x limits have been expanded with scale_x_continuous, setting fullrange=TRUE in geom_smooth causes the fit line to be shorter rather than longer, and also a warning appears:
```
Warning message:
Removed 59 rows containing missing values (geom_smooth). 
```
The number depends on the specifics of the data set being plotted, of course.
On my system in a fresh session with a new install of ggplot2 package, the following code reproduces this behavior. Set fullrange=FALSE first, and you will observe expected behavior: no warnings, and the fit line ends exactly at the range of the data. But when fullrange=TRUE the warning appears and the fit line is shorter.

```r
library(ggplot2)
df <- data.frame(time=rep(6:10, each=4), val=(rep(1:4, times=5) + rep(c(1,2,3,2,1), each=4)))
p <- ggplot(data=df, aes(x=time)) +
  geom_point(aes(y=val)) + 
  stat_summary(data=df, aes(y=val, group=1, size=10), fun=mean, color='red', geom='point') +
  geom_smooth(data=df, aes(y=val, group=1), method='loess', se=TRUE, formula=y~x, fullrange=FALSE) +
  scale_x_continuous(limits=c(0,15))
p
```

![fullrangeFALSE](https://user-images.githubusercontent.com/8398233/105423523-879b8500-5bfa-11eb-8a9e-c0504cec5998.png)

```r
p <- ggplot(data=df, aes(x=time)) +
  geom_point(aes(y=val)) + 
  stat_summary(data=df, aes(y=val, group=1, size=10), fun=mean, color='red', geom='point') +
  geom_smooth(data=df, aes(y=val, group=1), method='loess', se=TRUE, formula=y~x, fullrange=TRUE) +
  scale_x_continuous(limits=c(0,15))
p
```

![fullrangeTRUE](https://user-images.githubusercontent.com/8398233/105423518-8702ee80-5bfa-11eb-8d64-3b0423927b41.png)

**Comment by thomasp85** [comment]
This is a mix of things happening. Loess cannot smooth outside the data range so everything outside is set to `NA` - these are promptly removed by the geom before rendering. The reason why it appears as if it decreases the range is because the sample points doesn't lie exactly on the boundary of the data. So, the first and last non-NA values do not coincide with the data boundary...

You can see (and fix) this by adding more sample points by setting e.g. `n = 500` in `geom_smooth()`
