### ISSUE TITLE
geom_density giving wrong impression from graph

### ISSUE THREAD

**Issue by safoueneKa** [tidyverse/ggplot2#4328]
Hello,

I am data analyst for manufacturing, a part of my work is to search for outliers.

I was lead by mistake today that we have an outlier on one type with geom_density where the real outlier was on the other type.
![boxplotPlot](https://user-images.githubusercontent.com/65088068/105847656-2ef33000-5fde-11eb-97a2-93e5e502933d.PNG)
![densityPlot](https://user-images.githubusercontent.com/65088068/105847662-30245d00-5fde-11eb-89fd-25847e88f5fd.PNG)

I have put the two graphs using the same data set. you can see that in the geom density the outlier at around -3000 belongs to the blue line where in reality it belongs to the red graph.

**Comment by smouksassi** [comment]
Hi can you facet by type ? this is probably an artifact that the blue line is on top of the red line there is ways to tell geom density not to add line beyond data limits have a look at the trim argument

**Comment by safoueneKa** [comment]
Hello,

thank you for your reply,
Yes that’s why I was writing this because this is a graphical artifact. The type 2 data does not reach -3000. Yes I can Facet the graphs, there are multiple solutions around this issue, but I wanted showcase where it can go wrong.

kind regards,

**Comment by yutannihilation** [comment]
If you read the documentation of `geom_density()`, you can find `trim` is useful in this case.

As a side note, I think it's nothing weird that data points or lines can overlap, and no visualization is perfect in that each visualization focuses only on some specific aspects of the data. IMHO, there's nothing ggplot2 (or any visualization tool) can do to save you when you are doomed to misunderstand a data from using just a single plot. You need multiple visualizations to look at the data from multiple angles, and that's why ggplot2 is useful on exploring your data; as you did, you can quickly change facet, change the type of geom from density to boxplot.

(One more thing, I suspect that weirdly chopped line might be a problem of Windows' graphic device. You can try ragg as [it's integrated with RStudio now](https://ragg.r-lib.org/#use-ragg-in-rstudio))

``` r
library(ggplot2)
library(patchwork)

d1 <- data.frame(x = c(rnorm(5000, -550, 500), -3000), type = "1")
d2 <- data.frame(x = c(rnorm(5000, -500, 50)), type = "2")

d <- rbind(d1, d2)

p1 <- ggplot(d) +
  geom_density(aes(x, colour = type))

p2 <- ggplot(d) +
  geom_density(aes(x, colour = type), trim = TRUE)

p1 / p2
```

![](https://i.imgur.com/mK9qblj.png)

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
