### ISSUE TITLE
Incorrect placement of legend label with certain expressions

### ISSUE THREAD

**Issue by tamas-ferenci** [tidyverse/ggplot2#4337]
The problem is that the text of the legend overlaps the symbol for certain expressions.

Minimal reproducible example:
```r
ggplot2::ggplot() + ggplot2::stat_function(fun = function(x) x, geom = "line", ggplot2::aes(color = "blue")) + 
    ggplot2::scale_color_discrete(labels = expression(a[b-d]^c+a[b-d]^c+a[b-d]^c+a[b-d]^c+a[b-d]^c))
```

Expected behavior: the legend text should begin at the right side of the symbol.

**Comment by thomasp85** [comment]
This is what I get when I run the code, which looks right to my eyes...

![image](https://user-images.githubusercontent.com/1775316/112292465-65bd8d80-8c91-11eb-8d57-5e097fe5b6fb.png)

If this is not right, can you please explain what you were expecting.

If this is not what you see, my guess is that you are using a bad graphic device (probably on windows since that is the only version that ships with a horrible default device). You should consider switching to ragg, or the built-in cairo devices

**Comment by tamas-ferenci** [comment]
That's how it looks for me:

![kép](https://user-images.githubusercontent.com/25476790/112964309-82057280-9148-11eb-88d4-a1e410157925.png)

If I change RStudio backend to AGG (or Cairo) everything is perfect, so the problem was surely what you mentioned. Thank you very much!
