### ISSUE TITLE
Faceting by POSIXct fails with uninformative error if timezone is UTC

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4341]
``` r
library(ggplot2)
library(tibble)

df <- tibble(y = as.POSIXct("2018-01-01 00:00:00", tz = "UTC"), x = 110)
df %>% 
  ggplot(aes(x)) +
  geom_histogram() +
  facet_wrap(~y)
#> Error: `scale_id` must not be `NA`

df <- tibble(y = as.POSIXct("2018-01-01 00:00:00"), x = 110)
df %>% 
  ggplot(aes(x)) +
  geom_histogram() +
  facet_wrap(~y)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/aHbMGdy.png)

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by yutannihilation** [comment]
Thanks, this is a duplicate of #4175. This is because `rbind_dfs()` doesn't support timezone (see https://github.com/tidyverse/ggplot2/issues/4175#issuecomment-675438387).

I think we have two points here:

1. facet should handle `POSIXct` with timezone properly.
2. the error message should be more informative (e.g. #4138 is a different issue, but shows the same message)

For point 1, we can keep discussing on #4175. By the way, do you have any thoughts on vctrs integration?

**Comment by hadley** [comment]
Ok, lets close this issue, and discuss in #4175. I did a very quick vctrs experiment in #4342; I think it's probably worth committing to for the next big ggplot2 release.

**Comment by yutannihilation** [comment]
Oh, the PR looks promising.

> it's probably worth committing to for the next big ggplot2 release.

Agreed!

**Comment by thomasp85** [comment]
Full support of a switch to vctrs
