### ISSUE TITLE
geom_polygon fails to draw polygon if part of it falls outside of the plotting area

### ISSUE THREAD

**Issue by ekatko1** [tidyverse/ggplot2#4354]
Thank you developers for the amazing package!

If even a small part of a polygon falls outside the bound of the plot, the whole polygon fails to appear in the plot. Though this may seem inoffensive at face value, it becomes problematic when there are rounding errors which cause the polygon to be only ever so slightly outside the bounds of the plotting area. I could not come up with a simple example of this, but it did come up in my code. 

Best!
Egor

```r
library(ggplot2)
df = data.frame(x=c(1, 2, 1), y = c(2, 2, 1))

# This works fine
ggplot(aes(y=y, x=x), data=df) + 
  geom_polygon()

# This does not work at all
ggplot(aes(y=y, x=x), data=df) + 
  geom_polygon() +
  scale_x_continuous(limits=c(NA, 1.5))
```

**Comment by teunbrand** [comment]
The polygon gets deleted because the `oob` function in the scale censors out-of-bounds data  by default.
The typical way to fix this is to specify the limits in the `coord_*()` instead.
``` r
library(ggplot2)
df = data.frame(x=c(1, 2, 1), y = c(2, 2, 1))

ggplot(aes(y=y, x=x), data=df) + 
  geom_polygon() +
  coord_cartesian(xlim = c(NA, 1.5))
```

![](https://i.imgur.com/v5Aqbrn.png)

Alternatively you can choose a different `oob` argument in the scale.

``` r
ggplot(aes(y=y, x=x), data=df) + 
  geom_polygon() +
  scale_x_continuous(limits=c(NA, 1.5),
                     oob = scales::oob_keep)
```

![](https://i.imgur.com/9GlklcE.png)

<sup>Created on 2021-02-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by yutannihilation** [comment]
Thanks @teunbrand!

**Comment by ekatko1** [comment]
Very cool thank you!
