### ISSUE TITLE
Discrete and continuous color scales have different logic in using options values

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#4466]
See discussion in #4456: The question is whether settings for `fill` should be applied to `colour` and vice versa or not. Currently discrete scales do so, continuous scales do not.

Related: #4149

**Comment by teunbrand** [comment]
In #5946 we grab default palettes from the theme. The type option still exists for backward compatibility reasons, but this is no longer the preferred approach to setting default palettes. As such, the inconcistency described in this issue becomes just a historical flaw that I probably doesn't require a fix. For this reason, I'll consider this issue fixed by #5946.
