### ISSUE TITLE
Regression: ggsave() fails if `device` is function without `...`

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/ggplot2#4539]
Since a9b3b17bd92a0526deb8626586ec44a4b3e714aa, if a `device` is passed to `ggsave()` and this device lacks a `...` argument (at least if it also uses a `file` argument instead of `filename`), it produces an "unused argument" error.

``` r
ggplot2::ggsave("test.emf", ggplot2::ggplot(), device = devEMF::emf)
#> Saving 7 x 5 in image
#> Error in (function (file = "Rplot.emf", width = 7, height = 7, bg = "transparent", : unused argument (filename = "test.emf")
```

<sup>Created on 2021-07-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clauswilke** [comment]
Is this different from #4521?

**Comment by yutannihilation** [comment]
It's a different package.

https://cran.r-project.org/package=devEMF

Looking at the diff of a9b3b17, I guess the problem is that we remap `filename` to `file` but don't remove the original one from the arguments, so probably both "file" and "filename" are passed?

https://github.com/tidyverse/ggplot2/blob/acaa98e4cfcd922a737f35c16ec3dd6079aab3dc/R/save.r#L161-L172

**Comment by bwiernik** [comment]
Yes, that’s the issue.
