### ISSUE TITLE
Use devEMF::emf instead of grDevices::win.metafile for .wmf/.emf

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/ggplot2#4541]
Currently, `ggsave()` uses the `grDevices::win.metafil()` device for output to .wmf/.emf. This device doesn't seem to work very well—when I use it, the actual plot is rendered at half the size of the canvas in the upper left corner. Like this:

![image](https://user-images.githubusercontent.com/4773225/124364003-a459d100-dc0c-11eb-8ba4-43b580ba90b0.png)

The `devEMF::emf()` device seems to work much better:

![image](https://user-images.githubusercontent.com/4773225/124364014-ade33900-dc0c-11eb-8d94-9cca77699c7a.png)

I think it would be better to render wmf/emf files using the *devEMF* device. It would add a dependency (perhaps in Suggests with a warning or error to prompt installation?), but would be worth it for much better emf generation. If that would be acceptable, I can make a PR.

Example emf files for the two devices are attached.
[emf_output.zip](https://github.com/tidyverse/ggplot2/files/6758890/emf_output.zip)

Reprex:
``` r
library(ggplot2)
g <- ggplot(cars, aes(x = speed, y = dist)) +
  geom_point()
ggsave("grDevices.emf", g, height = 7, width = 7)
ggsave("devEMF.emf",    g, height = 7, width = 7,
       device = {\(filename, ...) devEMF::emf(file = filename, ...)})
```

<sup>Created on 2021-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by yutannihilation** [comment]
We already use ragg for high-quality image output, so the idea of using another external package for the same purpose can be acceptable itself. However, I think the question is whether ggplot2 supports .emf/.wmf format that eagerly. Honestly, while I used R on Windows for 5 years, I've never heard of the format until #4521. I'm not totally against your idea, but, considering no maintainer uses Windows actively, I'm afraid it's virtually impossible to maintain the feature reliably (as you already notice .emf/.wmf-related features are broken twice recently: #4521 and #4539).

@thomasp85 @clauswilke 
Any thoughts?

**Comment by bwiernik** [comment]
EMF is basically the only vector format that works reliably in Microsoft Word on either Windows or Mac--SVG and PDF support are very buggy

**Comment by clauswilke** [comment]
@yutannihilation: I think we should fix any bugs that prevent people from using the graphics device of their choice, but otherwise I'd be wary of adding dependencies to relatively obscure external packages. Also note that users would likely not have devEMF installed unless they already know about it, so out of the box ggplot2 would basically never use this functionality in practice.

@bwiernik Please be aware that another way to fix this issue is for `devEMF::emf()` to add the `...` argument. You could file a bug with the maintainer. There's no public bug tracker, as far as I can tell, so you'd have to rely on sending an email...

**Comment by bwiernik** [comment]
My point with this issue is that the default behavior with ggsave when the file extension is wmf or emf is pretty unusable

**Comment by yutannihilation** [comment]
> I think we should fix any bugs that prevent people from using the graphics device of their choice, but otherwise I'd be wary of adding dependencies to relatively obscure external packages. 

I agree with you. I basically believe it should be fixed on grDevices's side if it's grDevices's problem.

**Comment by pmur002** [comment]
I have committed a change to r-devel (r81221) so that the user can specify `xpinch` and `ypinch` to `win.metafile()`.  This will still require some trial-and-error to get the right result (e.g., 96 seemed to work for me on this example), but once you have found the right number it should continue to work (for that machine/display).  Hope that helps.
