### ISSUE TITLE
Misleading error message when plotting with empty data.frame

### ISSUE THREAD

**Issue by jarauh** [tidyverse/ggplot2#4588]
When plotting with an empty data (which may happen when filtering goes wrong), there is an error if constant aesthetics are mixed with column names, and the error message is a little confusing.

Example:
```r
> ggplot(head(mtcars, 0)) + geom_point(aes(x = hp, y = mpg)) # no error here, plot is empty
> ggplot(head(mtcars, 0)) + geom_point(aes(x = 3, y = 4))        # no error here, plot contains one point
> ggplot(head(mtcars, 0)) + geom_point(aes(x = 3, y = mpg))   # error!
 Fehler: Aesthetics must be either length 1 or the same as the data (1): y
Run `rlang::last_error()` to see where the error occurred. 
```

Taken literally, the error message is wrong: Aesthetics `y` does have the same length as the data (0).

Expected behaviour: No error message, return an empty plot.

**Comment by karawoo** [comment]
I think an error makes sense here because unlike the first two plots, the x and y aesthetics have different lengths (1 vs. 0). The value you provided to `x` is the data with length 1 the message is referencing. As another example:

``` r
library("ggplot2")
ggplot() + geom_point(aes(x = 3, y = numeric(0)))
#> Error: Aesthetics must be either length 1 or the same as the data (1): y
```

![](https://i.imgur.com/ZFHzDmB.png)

<sup>Created on 2021-08-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jarauh** [comment]
@karawoo I don't understand: aesthetics of different length are ok, as long as one of the lengths is 1.  Example:

```r
ggplot() + geom_point(aes(x = 3, y = 1:3))
```

**Comment by karawoo** [comment]
These are the relevant lines: 
https://github.com/tidyverse/ggplot2/blob/cabb74660e55e16351e1e4d3b671c8c2fd7c644e/R/layer.r#L261-L270

Aesthetics of different length are ok as long as they are all length 1 or the length of the data; in my example (and your third example) the length of the data is taken to be 1 because that is the longest evaluated aesthetic, so the y aesthetic can't be length 0.

**Comment by jarauh** [comment]
Ah, I see.  I would still say that the error message is confusing: If `nrow(data) == 0`, then 'n' is not the "length of the data."

In my opinion, the error message should be changed.

I'm also thinking whether it makes sense to change the behaviour and not raise an error but return an empty plot?  In my use case that would be the right thing to do (or at least a decent thing to do), but there may be cases where that would be even more confusing.
