### ISSUE TITLE
Geom_smooth with binomial GLM doesn't work with log scale

### ISSUE THREAD

**Issue by tamas-ferenci** [tidyverse/ggplot2#4592]
Consider the following example:

``` r
library(ggplot2)
tb1 <- data.frame(x = runif(100)*100, success = rbinom(100, 100, 0.1), failure = rbinom(100, 100, 0.8))

p1 <- ggplot(tb1, aes(x, y=success/(success+failure), succ=success, fail=failure)) +
  geom_point() + geom_smooth(method = "lm", formula = y ~ x)
p1
```

![](https://i.imgur.com/040jPin.png)

``` r
p1 + scale_y_log10()
```

![](https://i.imgur.com/nKmczr2.png)

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Everything works fine, both for the original and for the log-scale.

However, all else equal, but using Binomial GLM instead of LM, this is what we get:

``` r
library(ggplot2)
tb1 <- data.frame(x = runif(100)*100, success = rbinom(100, 100, 0.1), failure = rbinom(100, 100, 0.8))
p2 <- ggplot(tb1, aes(x, y=success/(success+failure), succ=success, fail=failure)) +
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"), formula = cbind(succ, fail) ~ x)
p2
```

![](https://i.imgur.com/kTuwm9a.png)

``` r
p2 + scale_y_log10()
```

![](https://i.imgur.com/cnAPxMm.png)

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I.e., it seems it doesn't really like the log scale for some reason.

**Comment by teunbrand** [comment]
I don't have a full understanding of the mechanism, but what I think is happening is that your `succ` and `fail` aesthetics are not included in the y-axis transformation and hence the prediction from `geom_smooth()` is on identity scale, whereas you want to display a log scale.

An attempt to pre-transform the `succ` and `fail` aesthetics with a separate fail due to the binomial family requiring integers.

``` r
library(ggplot2)

tb1 <- data.frame(x = runif(100)*100, success = rbinom(100, 100, 0.1), failure = rbinom(100, 100, 0.8))

p <- ggplot(tb1, aes(x, y=success/(success+failure), succ=success, fail=failure)) +
  geom_point() +
  scale_y_log10()

p +
  geom_smooth(method="glm", method.args=list(family="binomial"),
              formula = cbind(succ, fail) ~ x) +
  continuous_scale(c("succ", "fail"), "succfail", identity,
                   trans = "log10")
#> Warning in eval(family$initialize): non-integer counts in a binomial glm!
```

![](https://i.imgur.com/C4IJJsE.png)

For reasons I only vaguely* understand, if you wrap all the outcome aesthetics in `stage/after_stat()`, it seems that the line is more correct.

``` r
p +
  geom_smooth(method="glm", method.args=list(family="binomial"),
              formula = cbind(succ, fail) ~ x,
              aes(y = stage(success/(success + failure), y),
                  ymin = after_stat(ymin), ymax = after_stat(ymax)))
```

![](https://i.imgur.com/FW1zcWM.png)

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

\* it seems that they are re-transformed if their evaluation is slightly delayed because then the data passes this logic branch:

https://github.com/tidyverse/ggplot2/blob/cabb74660e55e16351e1e4d3b671c8c2fd7c644e/R/layer.r#L336-L338

**Comment by tamas-ferenci** [comment]
Thank you very much @teunbrand ! It seems to work perfectly in my real problem as well. Nevertheless, it would be interesting to know it this is really "the" workaround, and, much more importantly, if this whole story can be considered to be a bug, so that there is a chance that it'll be corrected in the future.

**Comment by thomasp85** [comment]
thinking more about it, I would be very weary of trying to fix this. What we are seeing is two different lazy evaluation schemes battling with each other and I have a hard time figuring out how we can fix this in a general way. I'm open to having my mind changed though...

**Comment by hadley** [comment]
I don't think it's worth fixing this special case, given other development priorities.
