### ISSUE TITLE
apparently spurious is.na() warning on use of language in label

### ISSUE THREAD

**Issue by twest820** [tidyverse/ggplot2#4644]
I suspect this is the lack of support for languages in labels mentioned in #4505 but that issue seems to have gotten closed for lack of a repex rather than triggering a code change. I'm seeing `annotate(label = bquote(...))` works fine but raises a warning which suggests some internal type check is missing.
```r
ggplot() + annotate("text", x = 0, y = 0, label = bquote(R[adj]^2 == 0.9))
# renders without the colored border mentioned in 4505 for me but still produces
# Warning message:
# In is.na(x) : is.na() applied to non-(list or vector) of type 'language'
```

The workaround to avoid the warning is only slightly different code but I found it surprisingly difficult to discover. Quite a minor thing but it's unclear to me making users jump this particular hoop adds value to the use of ggplot.
```r
ggplot() + annotate("text", x = 0, y = 0, label = 'R[adj]^2 == 0.9', parse = TRUE)
```

**Comment by hadley** [comment]
`bquote()` returns a single call object, whereas here you need a list:

``` r
library(ggplot2)
ggplot() + annotate("text", x = 0, y = 0, label = list(bquote(R[adj]^2 == 0.9)))
```

![](https://i.imgur.com/ri9kd4x.png)

<sup>Created on 2022-03-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Improving this error is likely to fall out of changes when we revamp ggplot2 to use vctrs; I don't think it's otherwise likely to be worth fixing because the root cause is this base R infelicity:

``` r
is.na(bquote(x + y))
#> Warning in is.na(bquote(x + y)): is.na() applied to non-(list or vector) of type
#> 'language'
#> [1] FALSE FALSE FALSE
```

<sup>Created on 2022-03-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
