### ISSUE TITLE
geom_segment example confusing

### ISSUE THREAD

**Issue by jxu** [tidyverse/ggplot2#4679]
https://ggplot2.tidyverse.org/reference/geom_segment.html

It is confusing to name the colour aes "curve" and "segment" because those could be confused with how to specify the shape. Also color can be specified to `geom_curve` outside of aes which should be noted.

**Comment by thomasp85** [comment]
I don't think it is the purpose of the documentation of segments/curves examples to explain how standard geom calls work. All aesthetics can be set outside of `aes()` in all geoms, so I don't see why we should specifically mention the combination of `geom_curve` and `colour`. And mapping colour to a string is also pretty standard behaviour.

**Comment by ptoche** [comment]
It will definitely not confuse the intermediate user. However, to benefit beginners, perhaps the simple change below?


from:
```
geom_curve(aes(x = x1, y = y1, xend = x2, yend = y2, colour = "curve"), data = df) +
geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2, colour = "segment"), data = df)
 ```
 
to:
 
 ```
 geom_curve(aes(x = x1, y = y1, xend = x2, yend = y2, colour = "my curve"), data = df) +
 geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2, colour = "my segment"), data = df)
 ```

**Comment by jxu** [comment]
My point is not to document geom calls, but to reduce confusion that may occur, especially among beginners. I think that even among intermediate users, there is a slight cognitive dissonance in giving the color option a string of "curve" or "segment". Maybe even an example of https://en.wikipedia.org/wiki/Stroop_effect, you know the activity where you have to read the color the word is printed in instead of the word itself.

**Comment by clauswilke** [comment]
Have you actually run the code and looked at the output? How is this in any way confusing?


``` r
library(ggplot2)
b <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point()

df <- data.frame(x1 = 2.62, x2 = 3.57, y1 = 21.0, y2 = 15.0)
b +
  geom_curve(aes(x = x1, y = y1, xend = x2, yend = y2, colour = "curve"), data = df) +
  geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2, colour = "segment"), data = df)
```

![](https://i.imgur.com/bR3KS8X.png)

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jxu** [comment]
I already explained why. "curve" and "segment" are words we associate with shape, not color. Therefore it might be confusing to beginners why we apparently specify shape words to color. The docs do not only target people who are already well-acquainted with ggplot, but there is no downside to reducing cognitive load.

**Comment by thomasp85** [comment]
I'd be fine with changing the wording in the strings to `"a curve"` and `"a segment"` or something like that. However I do strongly believe that the purpose of the docs and examples are not to be the educator of newcomers, but to showcase functionality for users already acquainted with how ggplot2 "fits together". We have plenty of free long-form introductions to the basics of ggplot2 precisely so that the docs can focus on explaining the specifics of the part they document.

So, this is not to dismiss your confusion about the example, but to explain that the questions and confusion are better addressed elsewhere (IMO) because the docs need to be succinct and to the point of the topic.
