### ISSUE TITLE
SVG output contains fixed-width text boxes, making manual editing harder

### ISSUE THREAD

**Issue by ekernf01** [tidyverse/ggplot2#4699]
More of an enhancement than a bug, but I reported this to inkscape [here](https://gitlab.com/inkscape/inbox/-/issues/6001) because someone on Twitter said it was interesting. When I export an SVG from ggplot2 and open it in InkScape, then delete part of a figure title, the rest stretches out to keep the box the same width. This ruins the aspect ratio. Thanks for taking a look!

```r
library(ggplot2)
ggplot(diamonds) + 
  geom_point(aes(x = cut, y = carat)) + 
  ggtitle("A very long title which I now regret and wish to edit in inkscape or somesuch")
ggsave("~/Desktop/reprex.svg", width = 5, height = 5)
```

I'm using `R 4.0.0`, `ggplot2 3.3.5`, `Inkscape 1.0.2 (1.0.2+r75+1),  Pango version: 1.40.14`.

**Comment by thomasp85** [comment]
This is not related to ggplot2 (or Inkscape for that matter). It is a matter of how the graphic device creates the svgs...

However, this should be fixed with the latest version of svelte, at least for text that is either fully left, right, or center aligned so please try to update svglite and open an issue there if it is not resolved - than we can take it from there
