### ISSUE TITLE
`geom_bar(..., position = "stack")` gives reversed stack with `aes(fill = ..)`, thus not work with `position_stack`

### ISSUE THREAD

**Issue by albert-ying** [tidyverse/ggplot2#4717]
## Code example
```
library(ggplot2)

data.frame(
  A = c(rep("H", 3), rep("L", 3)),
  B = rep(c("I","W", "Q"), 2),
  N = 1:6
) |>
  ggplot(aes(x = A, y = N, label = N)) +
  geom_bar(aes(fill = B), width = 0.5, color = "black", stat = "identity", position = "stack") +
  geom_text(size = 3, position=position_stack(vjust=0.5))
```

<img width="565" alt="image" src="https://user-images.githubusercontent.com/59846322/150701282-4980b477-691d-44f2-a951-4a0f290efc7f.png">

You can notice that the position of text is funny.

```
data.frame(
  A = c(rep("H", 3), rep("L", 3)),
  B = rep(c("I","W", "Q"), 2),
  N = 1:6
) |>
  ggplot(aes(x = A, y = N, label = N)) +
  geom_bar(width = 0.5, color = "black", stat = "identity", position = "stack") + # remove the aes(fill)
  geom_text(size = 3, position=position_stack(vjust=0.5))
```
After the `aes` is removed, it looks normal. And if you compare to previous figure, the position of stacks are reversed, while the position of the text is the same.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/59846322/150701338-c1adbc02-2679-448b-8264-c07aa6404248.png">

**Comment by hadley** [comment]
The problem is the grouping created by the categorical variable `B`. If you set the fill for every layer it all lines up nicely:

``` r
library(ggplot2)

data.frame(
  A = c(rep("H", 3), rep("L", 3)),
  B = rep(c("I","W", "Q"), 2),
  N = 1:6
) |>
  ggplot(aes(x = A, y = N, label = N, fill = B)) +
  geom_col(aes(fill = B), color = "black") +
  geom_text(size = 3, position = position_stack(vjust = 0.5))
```

![](https://i.imgur.com/11uHtlF.png)

<sup>Created on 2022-03-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is a little surprising, but I'm pretty sure we've tried to fix this in the past and have only ever succeeded in moving the problem elsewhere.
