### ISSUE TITLE
Request for improved documentation of `geom_bar` and `geom_col`

### ISSUE THREAD

**Issue by doliv071** [tidyverse/ggplot2#4766]
Hi All,

I would like to request that the documentation for `geom_bar` and `geom_col` indicate it's behavior when duplicated x/y are present in the data. There is nowhere in the documentation that indicates that the maximum value is taken when this situation occurs and additionally, no warnings are emitted to indicate that data is dropped. 

Arguably, this situation should cause an error since there is no way to plot "identity" of multiple values. 

In addition, this issue gets compounded when `position = "fill"` since the length of the segments now reflect the proportion of the group maximums. 

I've included a reprex below for clarification. 

```r
# Begin reprex --------------
reps <- paste0("rep", 1:3)
res <- lapply(reps, \(x){
    data.frame(x = paste0("sample", 1:3), 
                       y1 = abs(rnorm(3)),
                       y2 = abs(rnorm(3)),
                       y3 = abs(rnorm(3))) |>
    tidyr::pivot_longer(cols = where(is.numeric))
}) %>% do.call(rbind, .)

ggplot2::ggplot(res, ggplot2::aes(fill = name, y = x, x = value)) +
    ggplot2::geom_bar(position = "dodge", stat = "identity")

# show the 3 values associated with the top bar in the plot 
dplyr::filter(res, name == "y3", x == "sample3")

# End reprex --------------
```

**Comment by teunbrand** [comment]
It is easier to see what is going on when you set an `alpha` and a `colour`. Every row in the data is displayed as-is and starts to overlap with others in the same group, implicitly marked by `fill` and `y`: no maximum is taken, but you only see the maximum because they overlap.  You've instructed `geom_bar()` to do so by setting `stat = "identity"`.

``` r
library(dplyr)
library(ggplot2)

reps <- paste0("rep", 1:3)
res <- lapply(reps, \(x){
    data.frame(x = paste0("sample", 1:3), 
               y1 = abs(rnorm(3)),
               y2 = abs(rnorm(3)),
               y3 = abs(rnorm(3))) |>
        tidyr::pivot_longer(cols = where(is.numeric))
}) %>% do.call(rbind, .)

ggplot(res, aes(fill = name, y = x, x = value)) +
    geom_bar(position = "dodge", stat = "identity",
             colour = "black", alpha = 0.5)
```

![](https://i.imgur.com/M5PUu8X.png)

If instead you wanted to sum the values per group, you can use `stat = "summary"` and `fun = sum`.

``` r
ggplot(res, aes(fill = name, y = x, x = value)) +
    geom_bar(position = "dodge", stat = "summary", fun = sum, 
             colour = "black", alpha = 0.5)
```

![](https://i.imgur.com/YYzDFkj.png)

<sup>Created on 2022-03-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by doliv071** [comment]
Thanks for the quick response. Makes sense to me now. In addition to adding `alpha`, `"dodge2"` also shows that all of the data are indeed there.
