### ISSUE TITLE
Evaluation of If Else in Aesthetics Error

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#4826]
The example seems to be evaluating the else part, even though the if condition is true, and so it probably shouldn't be evaluated.

``` r
characteristicsList <- list(x = "Classifier Name")
ggplot2::aes(fill = if(is.null(characteristicsList[["fillColour"]])) NULL else !!rlang::sym(characteristicsList[["fillColour"]]))
#> Error in `rlang::sym()`:
#> ! Can't convert NULL to a symbol.
```

<sup>Created on 2022-05-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I sought feedback on R-package-devel mailing list and [a former R Core member thought it looks like a bug in ggplot2](https://stat.ethz.ch/pipermail/r-package-devel/2022q2/008009.html). The overall aim of this code is that I am creating a function that allows the end-user to specify what to place on the x-axis, and what variable (if any) to use for line colour and what one for fill colour. Also, being robust to spaces in column names in case end-user has those.

**Comment by yutannihilation** [comment]
You simply cannot convert `NULL` to a symbol by `sym()`.

``` r
characteristicsList <- list(x = "Classifier Name")
rlang::sym(characteristicsList[["fillColour"]])
#> Error in `rlang::sym()`:
#> ! Can't convert NULL to a symbol.
```

<sup>Created on 2022-05-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
Ah, okay, I was wondering what part of this is confusing to you, but probably it's the behaviour of `!!`? It's "injection operator", the syntax to make the expression get evaluated eagerly and inject the result to a quoted expression. Because it happens before the entire expression of the `if` statement gets evaluated, you see the error.

c.f. https://rlang.r-lib.org/reference/topic-inject.html

I think you can simply do it outside of `aes()`.

``` r
characteristicsList <- list(x = "Classifier Name")

if (is.null(characteristicsList[["fillColour"]])) {
  fill_var <- NULL
} else {
  fill_var <- rlang::sym(characteristicsList[["fillColour"]])
}

ggplot2::aes(fill = !!fill_var)
#> Aesthetic mapping: 
#> * `fill` -> NULL
```

<sup>Created on 2022-05-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DarioS** [comment]
Thank you, Hiroaki. It turns out both the R core member and I incorrectly understood `!!` I now understand correctly.

**Comment by yutannihilation** [comment]
No worries. My first response was a bit too terse, sorry.

For future reference, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). I think you can get better feedbacks there.
