### ISSUE TITLE
labeled breaks for binned color scale malfunction when show.limits = T

### ISSUE THREAD

**Issue by waynerroper** [tidyverse/ggplot2#4831]
---

When formatting labels for breaks in color scales, ggplot returns an error for the length of label vector if _show.limits = T_. This error appears even if the breaks and labels vectors are the same length. 

This may be because limits and breaks are passed to different vectors before compiling the final plot and therefore the user cannot easily write labels for limits and breaks together. An example is provided here: [https://stackoverflow.com/questions/71976832/custom-labels-for-limit-and-break-values-when-using-scale-color-binned-in-r-ggpl](url)

Is it possible to integrate limits and breaks in a more streamlined way to avoid the error message and not have to define labels with a custom function that circumvents the issue?

```r
library(ggplot2)

ggplot(mpg, aes(cty, hwy, color = year)) +
  geom_point() +
  scale_color_binned(limits = c(1999, 2008),
                    breaks = c(2000, 2002, 2004, 2006),
                    labels = c('2', '3', '4', '5'),
                    show.limits = F) # labels work

ggplot(mpg, aes(cty, hwy, color = year)) +
  geom_point() +
  scale_color_binned(limits = c(1999, 2008),
                    breaks = c(2000, 2002, 2004, 2006),
                    labels = c('2', '3', '4', '5'),
                    show.limits = T) # method fails when limits are activated

    # Error in f(): ! Breaks and labels are different lengths

```

**Comment by yutannihilation** [comment]
Thanks, confirmed. It seems the problem is that, when `show.limits = TRUE`, the labels for the upper and lower limits are set separately with `scale$get_labels()`, whereas `get_labels()` always validates the result against the supplied `labels`.

https://github.com/tidyverse/ggplot2/blob/b9e1694ddc35e6c24013dbca581e5fcc4ebfae2b/R/guide-colorsteps.R#L104-L110

https://github.com/tidyverse/ggplot2/blob/b9e1694ddc35e6c24013dbca581e5fcc4ebfae2b/R/scale-.r#L1122-L1135
