### ISSUE TITLE
In geom_pointrange, changes to the fatten arg are not reflected in the legend

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4872]
```
library(ggplot2)

df <- data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  upper = c(1.1, 5.3, 3.3, 4.2),
  lower = c(0.8, 4.6, 2.4, 3.6)
)

df %>% 
  ggplot() +
  geom_pointrange(aes(x = trt, y = resp, col = group, ymin = lower, ymax = upper),
                  fatten = 1)
```

<img width="311" alt="image" src="https://user-images.githubusercontent.com/55065152/173333856-aa6ed044-c922-41ba-a6ee-afdeba58bebc.png">

**Comment by smouksassi** [comment]
possibly related to https://github.com/tidyverse/ggplot2/issues/2798 
 fatten is not a parameter and currently, the legend does not reflect any changes to it and is currently kind of hard coded:
 https://github.com/tidyverse/ggplot2/blob/0e64d9c56ccc8db31971723810c3c10f0a67d9e4/R/legend-draw.r#L197

with the ongoing work of linewidth aesthetic things might be easier to handle/fix.
https://github.com/tidyverse/ggplot2/pull/3672

**Comment by yutannihilation** [comment]
Thanks @smouksassi. As suggested, I think this issue is resolved by https://github.com/tidyverse/ggplot2/pull/3672. Now you can combine `size` and `linewidth` to control the sizes of points and lines differently. My understanding is `fatten` was a workaround for this, but is probably no longer needed.

``` r
library(ggplot2)

df <- data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  upper = c(1.1, 5.3, 3.3, 4.2),
  lower = c(0.8, 4.6, 2.4, 3.6)
)

ggplot(df) +
  geom_pointrange(aes(x = trt, y = resp, col = group, ymin = lower, ymax = upper),
    size = 2, linewidth = 0.5
  ) +
  theme(legend.key.size = unit(0.15, "npc"))
```

![](https://i.imgur.com/R0geHjE.png)

<sup>Created on 2022-06-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
