### ISSUE TITLE
 geom_segment size cannot change the line width, but the line length

### ISSUE THREAD

**Issue by shenzhenzth** [tidyverse/ggplot2#4906]
colnames(df) <- c("ref_start", "ref_end", "qry_start", "qry_end", "ref_len", "qry_len", 
                  "identiy", "ref_tag","qry_tag" )
ggplot(data = df) + facet_grid(ref_tag~qry_tag, as.table = FALSE, 
                               switch = "both", scales = "free", 
                               space = "free",margins="TRUE") + 
  geom_segment(aes(x = ref_start/10000, y = qry_start/10000,
                   xend = ref_end/10000, 
                   yend = qry_end/10000,color=qry_end-qry_start > 0),
                   size=0.5)
if I change size from 0.5 to 5 ,  geom_segment size cannot change the line width, but the line length
can anyone help me 
think you very much
![1657471624249](https://user-images.githubusercontent.com/109035781/178153992-45f20b48-d598-482b-bb10-bb97da03c560.png)
![1657471532869](https://user-images.githubusercontent.com/109035781/178153995-169d8ac3-f9af-4971-9081-19b402f92787.png)

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by shenzhenzth** [comment]
[data.txt](https://github.com/tidyverse/ggplot2/files/9084210/data.txt)

This is part of my data.

thank u very much again

**Comment by yutannihilation** [comment]
@shenzhenzth 
We gently ask you to use the reprex package, and provide more minimal example, like I do below. Please try next time, but in general, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). We use this issue tracker for bug reports and feature requests.

It's actually the line width, but it looks like the line length because your segments are too short compared to the range. Hope this helps!

``` r
library(ggplot2)

df <- data.frame(
  x = c(0, 2, 197, 200),
  y = c(0, 2, 197, 200)
)

p1 <- ggplot(df[1:2, ]) +
  geom_segment(
    aes(x, y, xend = x + 1, yend = y + 1),
    size = 5,
    colour = alpha("red", 0.7)
  ) +
  theme_minimal() +
  coord_fixed()
#> size aesthetic has been deprecated for use with lines as of ggplot2 3.4.0
#> ℹ Please use linewidth aesthetic instead
#> This message is displayed once every 8 hours.

p2 <- ggplot(df) +
  geom_segment(
    aes(x, y, xend = x + 1, yend = y + 1),
    size = 5,
    colour = alpha("red", 0.7)
  ) +
  theme_minimal() +
  coord_fixed()

patchwork::wrap_plots(p1, p2)
```

![](https://i.imgur.com/1XjBetY.png)

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
