### ISSUE TITLE
scale_size inconsistency?

### ISSUE THREAD

**Issue by baderstine** [tidyverse/ggplot2#4924]
When attempting to make multiple geom_point() plots with [consistent point sizes using a variable to define size](https://stackoverflow.com/questions/20155400/defining-minimum-point-size-in-ggplot2-geom-point?noredirect=1&lq=1), I've been unable to ensure consistent point sizes between plots in the special case where points with both sizes don't exist in the source dataset: 

```r
# typical case: i have points of two different sizes
df <- data.frame(x = 1:10,y = runif(10),sz = c(rep(2,8),5,5))

# the default scales the small ones too small...
ggplot(df,aes(x = x,y = y,size = sz)) + 
  geom_point() 
```
![image](https://user-images.githubusercontent.com/2738299/181307276-24c29520-4c20-4aa7-af1c-022c9fc52a3d.png)
```r
# so i use scale_size_continuous with a range argument to make the smaller ones bigger
ggplot(df,aes(x = x,y = y,size = sz)) + 
  geom_point() + 
  scale_size_continuous(range = c(2,5))
```
![image](https://user-images.githubusercontent.com/2738299/181307330-b580848f-9b31-4f68-83e5-c2c5df7da34f.png)
```r
# special case where i only have one of the two sizes
df2 <- df %>%
  mutate(sz = rep(2,10))

# the default scales these points huge
ggplot(df2,aes(x = x,y = y,size = sz)) + 
  geom_point() 
```
![image](https://user-images.githubusercontent.com/2738299/181307376-0f3ff1cb-9b06-4310-b2e2-b3063a525609.png)
```r
# and using scale_size_continuous with a range argument does not result in the same size points as when i had two different sizes
ggplot(df2,aes(x = x,y = y,size = sz)) + 
  geom_point() + 
  scale_size_continuous(range = c(2,5))
```
![image](https://user-images.githubusercontent.com/2738299/181307419-5ca2d283-4a2c-44cb-aa20-189cc8e76d8e.png)
```r
# I tried using scale_size_area but these point sizes are variable as well:
ggplot(df,aes(x = x,y = y,size = sz)) + 
  geom_point() + 
  scale_size_area(max_size = max(df$sz))
```
![image](https://user-images.githubusercontent.com/2738299/181307466-e498361d-b2b4-46be-a164-4ec6e988e007.png)
```r
ggplot(df2,aes(x = x,y = y,size = sz)) + 
  geom_point() + 
  scale_size_area(max_size= max(df2$sz))
```
![image](https://user-images.githubusercontent.com/2738299/181307512-3e7b38bf-580c-4c93-ba34-87a254ad63f5.png)

So my question is how do I use a variable in my data.frame to consistently define point sizes?  For color, I know that "grey" is "grey", but for size 2 is not always 2?

**Comment by teunbrand** [comment]
Perhaps the tricky bit to understand here is that the `range` is the range of output sizes. Since the scale maps values from the scale's limits to this range, and in the case that all `size == 2` (i.e., input has zero-range) you get inconsistent sizes between plots. To prevent this you can set `scale_size_continuous(range = c(2, 5), limits = range(df$sz))` to have a consistent mapping between the input range (limits) and the output range (range).

**Comment by yutannihilation** [comment]
> "grey" is "grey"

It's not true when you map the variable to the aesthetic because, as @teunbrand explained, it gets scaled. `size` is the same.

``` r
library(ggplot2)

ggplot(data.frame(x = 1:3, y = 1:3, colour = "grey")) +
  geom_point(aes(x, y, colour = colour), size = 30)
```

![](https://i.imgur.com/KBvK8Q0.png)

<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If you want the identical size as the value in the data, what you want is probably `scale_size_identity()`.

**Comment by baderstine** [comment]
Sorry I should have been more clear.  I meant 'for scale_color`, "grey" is "grey":

```r 
ggplot(data.frame(x = 1:3, y = 1:3, colour = "grey")) +
  geom_point(aes(x, y, colour = colour), size = 30) + 
  scale_color_manual(values="grey")
```
