### ISSUE TITLE
ggsave saves plots into SVG format somewhat streched

### ISSUE THREAD

**Issue by SarenT** [tidyverse/ggplot2#4929]
SVG files generated by ggsave (tested on Ubuntu 18.04 LTS) are kind of stretched compared to the plots in RStudio or PNG format.
(R 4.0.3 ggplot2 3.3.6 svglite 2.1.0)
```r
plot = ggplot(iris, aes(x = Species, y = Sepal.Length)) + geom_violin()
plot # RStudio
ggsave("test_ggsave.png", plot, "png")
ggsave("test_ggsave.svg", plot, "svg")
```

SVG files looks like this:
![image](https://user-images.githubusercontent.com/2906565/182261633-f7b4b468-1d19-419d-abd3-79be6236b77a.png)
And the PNG file looks like this:
![image](https://user-images.githubusercontent.com/2906565/182262024-c073b679-a758-410e-be03-d04680db40d0.png)
This is in RStudio:
![image](https://user-images.githubusercontent.com/2906565/182262080-cda560a1-7e24-4170-992e-10808101d701.png)

I have removed the attribute `lengthAdjust='spacingAndGlyphs'` from text objects:
![image](https://user-images.githubusercontent.com/2906565/182261904-9bdff829-069b-4470-b841-106353c76ebc.png)

I think that this option could be the culprit.

**Comment by thomasp85** [comment]
`ggsave()` uses svglite to render svg. As svg files doesn't know how they are going to get rendered by default they fix the width of the string in order to make various adjustments and calculations on the string possible. This can be turned off by setting `fix_text_size = FALSE` in `svglite()`/`ggsave()` which effectively removes the `lengthAdjust` attribute you discovered

**Comment by cbrnr** [comment]
I also ran into this issue, and `fix_text_size=FALSE` helps. However, I noticed that the generated SVG files still differ slightly depending on which platform they were created. I compared macOS vs. Linux, and although the fonts now look identical, some of the horizontal spacing is still off. This behavior is not ideal from a reproducibility point of view, since I'd really want the SVGs to be identical and not dependent on the platform. Is there anything else I can do? Should I open a new issue? I can provide an example SVG produced on macOS and Linux.

**Comment by teunbrand** [comment]
@cbrnr Does that only happen in ggplot2 or can this be reproduced in pure grid as well?

**Comment by cbrnr** [comment]
I should probably use `svglite::svglite()` though, right?

**Comment by teunbrand** [comment]
Yes, though it can be much simpler than the ChatGPT example.

```r
library(grid)
# Try reproduce text that gave problems
x <- textGrob("my problematic label", gp = gpar(fontfamily = "Impact"))

# Write to file
svglite::svglite("example.svg", fix_text_size = FALSE)
grid.newpage(); grid.draw(x)
dev.off()
```

I don't have convenient access to multiple platforms so I won't be able to identify if they give different results. But the essence is that if the problem also occurs when using pure grid, then perhaps it is a {svglite} issue instead of a {ggplot2} issue.

**Comment by cbrnr** [comment]
Thanks, I'll report back once I've tested this on multiple platforms.

**Comment by cbrnr** [comment]
However, I'll probably stick with the longer example, because text rendered identically if setting `fix_text_size=FALSE` (although I also find this a bit weird, because I really do want to fix text size, so I would assume that the default of `TRUE` would work). The entire SVG seems to be a little stretched in the x-direction (i.e., lines and positions), but not text by itself.

**Comment by cbrnr** [comment]
So I don't think this is an `{svglite}` issue, since the SVGs look identical if `fix_text_size=FALSE`. Should I open a new issue? I also think that `fix_text_size=FALSE` should probably be the default, since the current default of `fix_text_size=TRUE` stretches text depending on the platform.

![Image](https://github.com/user-attachments/assets/1c30874e-8eec-4d12-be37-f255907e4c67)
![Image](https://github.com/user-attachments/assets/16f5f7f1-ae7d-408b-8d7d-97b94155b1ef)
![Image](https://github.com/user-attachments/assets/bb9c1fe6-b615-40a0-8f1b-a5d19dd6071b)
![Image](https://github.com/user-attachments/assets/7d748693-c9dc-41c0-9bd7-ad6887ff2758)
