### ISSUE TITLE
`scale_y_continuous(limits = c(0, 1))` does not work as expected when `position = "fill"` is set

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4942]
`scale_y_continuous(limits = c(0, 1))` does not work as expected when `position = "fill"` is set. 

```
library(palmerpenguins)
library(tidyverse)

p <- penguins %>%
  tidyr::drop_na() %>%
  group_by(species, sex) %>%
  summarise(body_mass_g = mean(body_mass_g, na.rm = T)) %>%
  ggplot() +
  geom_col(aes(species, body_mass_g, fill = sex), position = "fill")

p
```
<img width="353" alt="image" src="https://user-images.githubusercontent.com/55065152/184447573-478561de-e423-4cf6-9ee8-8c673c967232.png">

```
p +
  scale_y_continuous(limits = c(0, 1))
```
<img width="362" alt="image" src="https://user-images.githubusercontent.com/55065152/184448012-1b765984-4a95-43e0-8682-d60afb21c25a.png">

**Comment by yutannihilation** [comment]
That `limit` is applied on the raw data, not on the computed result. Since all the data are >1, no data is plotted. Please use `coord_cartesian()` (in this case `coord_cartesian(ylim = c(0, 1))`) for zooming purposes.

* FAQ: https://ggplot2.tidyverse.org/articles/faq-bars.html#why-do-the-bars-on-my-plot-disappear-when-i-specify-an-axis-range-with-ylim-how-can-i-get-the-bars-to-show-up-within-a-given-axis-range
* more details: https://github.com/tidyverse/ggplot2/issues/2887#issue-358576803
