### ISSUE TITLE
geom_smooth without interactions

### ISSUE THREAD

**Issue by rressler** [tidyverse/ggplot2#4968]
When adding a factor variable F to an Y ~ X  point plot, e.g., aes(x, y, color = F),  it appears stat_smooth includes the interaction terms for XF in the predictdf model argument for method = lm. 

Issue 1.
Example 1 and 2 show a message for formula as `y ~ x` which seems incorrect (note same message for both calls to geom_smooth() in the examples even though one includes F). The second call should be `y ~ x * color` based on how state_smooth() currently includes the factor and the interaction term.

Issue 2
There does not appear to be a way for one to exclude the interaction term, e.g., when one determines separately the term is not of interest. Recommend allowing one to submit an argument such as `formula  = y ~ x  + color` (or whatever aesthetic is mapped to F). This would allow the use of geom_smooth to represent the model without interactions instead of using geom_abline.

---
```r
# example 1 interaction is of interest
summary(lm(cty ~ displ + as.factor(cyl), data = mpg)) 
summary(lm(cty ~ displ * as.factor(cyl), data = mpg))
ggplot(mpg) +
  geom_point(aes(x = displ, y = cty, color = as.factor(cyl)), alpha = .5) +
  geom_smooth(aes(x = displ, y = cty), color = "black",
              method = lm, se = FALSE) +
  geom_smooth(aes(x = displ, y = cty, color = as.factor(cyl)),
              method = lm, se = FALSE)

# example 2 interaction is not of interest
summary(lm(cty ~ displ + as.factor(year), data = mpg))
summary(lm(cty ~ displ * as.factor(year), data = mpg))
ggplot(mpg) +
  geom_point(aes(x = displ, y = cty, color = as.factor(year)), alpha = .5) +
  geom_smooth(aes(x = displ, y = cty), color = "black",
              method = lm, se = FALSE) +
  geom_smooth(aes(x = displ, y = cty, color = as.factor(year)),
              method = lm, se = FALSE)
```

**Comment by aphalo** [comment]
My understanding is that rather than an interaction term being included, the model is fitted separatelly to data in each group. A new version of `stat_smooth()` using a `compute_panel` function would make it possible to fit a model jointly to all data in a panel and include the grouping variables in model formulas.

**Comment by teunbrand** [comment]
Pedro is right here, the model is indeed fitted seperately for every group. I like the idea of being more explicit about what is being modelled, but if people'd have to include `y ~ x * group` to get the current behaviour, that will affect a lot of existing plots. For that reason, I think we probably shouldn't change the default behaviour.

**Comment by aphalo** [comment]
I agree, a new `stat` with a different name could be written, which would be easier to implement. Or rewrite `stat_smooth()` using a `compute_panel` function that by default mimics a `compute_group` function but that can be switched through an argument to do the fit by panel.

**Comment by teunbrand** [comment]
I think the stance that ggplot2 has taken previously is that if you'd want to do anything more complicated than `geom_smooth()` offers out-of-the-box, it is probably best the do the modelling outside ggplot2 and use the package to plot the modelling results instead of having ggplot2 handling the modelling. With that in mind, I'm going to close this issue, but not before thanking you for the thoughts you've put into this issue and coming up with reproducible examples.
