### ISSUE TITLE
Error: Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes

### ISSUE THREAD

**Issue by ProfessorPeregrine** [tidyverse/ggplot2#5017]
ggplot2 version 3.3.6.9000. Error goes away with 3.3.6

---

ggplot generates a spurious console error:

Warning message:
In structure(in_domain, pos = match(in_domain, breaks)) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

In the repex if you comment out scale_color_manual(values=leg_names)+ the error stops.

```r
library(ggplot2)

facet<-rep(c("Sample 1","Sample 2","Sample 3","Sample 4","Sample 5"),20)
num_data<-rnorm(100)

data<-data.frame(cbind(facet,num_data))
data$num_data<-as.numeric(data$num_data)

names(data)<-c("ID","Data")

plot_data<-data

leg_names<-c("Data"="red")

p<-ggplot(plot_data,aes(x=Data))+
  scale_color_manual(values=leg_names)+
  scale_fill_manual(values=leg_names)

p<-p+
  geom_histogram(aes(fill="Data"))+
  labs(y="Count")

p
```

**Comment by teunbrand** [comment]
A more minimal example:

``` r
library(ggplot2)

ggplot(data.frame(x = 1), aes(x, x)) +
  scale_colour_manual(values = c("x" = "blue"))
#> Warning in structure(in_domain, pos = match(in_domain, breaks)): Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
#>   Consider 'structure(list(), *)' instead.
```
<sup>Created on 2022-10-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

At a first glance, it seems a combination of having no mapping for `colour` and using names `values`. I think the problem might be that the following line can return `NULL`, in which case the `ScaleDiscrete$get_breaks()` method is in hot water.

https://github.com/tidyverse/ggplot2/blob/a58b48c961cb391b8646bf072b6620a0c9f3d999/R/scale-manual.r#L137

If there is still time to patch this up in the rc branch, I'd suggest to change the line above to something like:

``` r
limits <- function(x) intersect(x, names(values)) %||% logical()
```

To return a 0-length vector instead of `NULL`, that should satisfy the `get_breaks()` method. A `logical` type seems good here because of flexibility with coercion rules.
