### ISSUE TITLE
Remove margins with `geom_sf()`

### ISSUE THREAD

**Issue by turbanisch** [tidyverse/ggplot2#5049]
This has been asked before on [Stackoverflow](https://stackoverflow.com/questions/57868862/crop-unused-margin-in-a-ggplot-plot) but I was wondering if it is actually a bug or intended behavior. The issue is that (unlike the sf plot method or tmap) ggplot imposes an aspect ratio on the plot that leads to margins (above and below in the following example):

``` r
library(tidyverse)
library(sf)
library(spData)
library(tmaptools)

# sf plot method
plot(spData::world["pop"])
```

![](https://i.imgur.com/5DEy5xl.png)

``` r

# ggplot
ggplot(spData::world) +
  geom_sf(aes(fill = pop))
```

![](https://i.imgur.com/qMDlSx1.png)

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Following the advice from Stackoverflow, I can remove most of the margins with a custom aspect ratio like so:

```r
# ggplot with adjusted ratio
asp <- tmaptools::get_asp_ratio(spData::world)
ggsave("adjusted_ratio.png", height = 5, width = 5 * asp)
```
However, this procedure is tedious to begin with and in dynamic documents I typically do not even explicitly save graphics. So it would be nice if there was an option to remove the margins within `geom_sf()`, in my view.

**Comment by clauswilke** [comment]
The margins are caused by the final output size of the figure. This is not a ggplot2 issue. For example, in an RMarkdown document, you'd have to set the figure width and height accordingly. Similarly, when you save the figure you have to set width and height, as shown in your example code.

I'm also quite confident that the same problem exists with `plot()`. The reason why the output of `plot()` looks better in your example is that the legend is underneath rather than on the side, and that eats up some of the margin. By contrast, the legend on the side in the ggplot2 example exacerbates the issue.

**Comment by turbanisch** [comment]
Absolutely, you're right. For a moment I forgot that RMarkdown/Quarto have defaults for figure dimensions. There is, however, a difference in the default settings for saving graphics with ggplot2 and tmap: tmap's output is tightly cropped around the map contents, which I find preferable in this case. 

```r
# ggplot
ggplot_plot <- ggplot(spData::world) +
  geom_sf(aes(fill = pop))

ggsave("ggplot.png")
```

![ggplot](https://user-images.githubusercontent.com/51969412/202048794-ef19e2e8-e265-47ab-b3e2-3131a0718b75.png)


```r
# tmap
library(tmap)
tmap_plot <- qtm(spData::world, "pop")
tmap_save(tmap_plot, "tmap.png")
```
![tmap](https://user-images.githubusercontent.com/51969412/202048827-70c89708-1248-4f89-931e-8970c4545f59.png)

**Comment by turbanisch** [comment]
Absolutely, you're right. For a moment I forgot that RMarkdown/Quarto have defaults for figure dimensions. There is, however, a difference in the default settings for saving graphics with ggplot2 and tmap: tmap's output is tightly cropped around the map contents, which I find preferable in this case. I would love Quarto/Rmarkdown to respect this crop in the case of maps but I see why it's working differently.

```r
# ggplot
ggplot_plot <- ggplot(spData::world) +
  geom_sf(aes(fill = pop))

ggsave("ggplot.png")
```

![ggplot](https://user-images.githubusercontent.com/51969412/202048794-ef19e2e8-e265-47ab-b3e2-3131a0718b75.png)


```r
# tmap
library(tmap)
tmap_plot <- qtm(spData::world, "pop")
tmap_save(tmap_plot, "tmap.png")
```
![tmap](https://user-images.githubusercontent.com/51969412/202048827-70c89708-1248-4f89-931e-8970c4545f59.png)

**Comment by SimonDedman** [comment]
I'd love if this could be revisited.

I have a large function which automates the job of plotting a `ggmap`. When printed before `ggsaving`, there don't seem to be any permanent white margins, insofar as the margins shrink or expand to fill the space when I resize the pane in Rstudio:

![image](https://github.com/tidyverse/ggplot2/assets/4599748/6984e9c5-dfb5-4b76-9f60-0bcf6a6b3d1e)

Intuitively therefore this plot has an existing, unchanging aspect ratio.

`?ggsave` says about `width` and `height`:

> If not supplied, uses the size of current graphics device

However that introduces even wider borders, and I don't know where the current graphics device would have created that from, since the plot in the RStudio pane doesn't have these present borders:

![image](https://github.com/tidyverse/ggplot2/assets/4599748/520e4e8d-00e0-4052-8aa0-152115f7abcf)

(screenshot includes extra bit of toolbar & stuff just to show extent of saved image)

Clearly this is an ongoing issue with others. [This thread](https://stackoverflow.com/questions/35346111/r-ggplot-remove-white-margins-in-ggsave-ggplot) proposes various solutions but I personally don't believe one should have to include `knitr`, `pdfcrop`, and `magick` in ones package in order to fix the issue after the image has been saved.

Similarly in [this thread](https://stackoverflow.com/questions/57868862/crop-unused-margin-in-a-ggplot-plot), a complex solution builds a wrapper around `ggsave` to solve this, but sadly this doesn't seem to work on my `ggmap` object:

> Error in get_aspect_ratio(geometry): "geometry" must be of class "Spatial", "Raster", "sf" or "sfc".

Possibly there's some disconnect between the actual/concept of "the size of current graphics device", at least as pertains to ggmaps, possibly more broadly, but to me it feels intuitive that a `ggsave` call with no height nor width params specified should default to respecting an existing plot ratio, and sizing/scaling that image to a sensible default, such that the user could then tweak either the height or width in order to resize the image saved.

Please could the team review this? And apologies if this is technically subtly distinct from @turbanisch 's OP given it's a `ggmap` not a `geom_sf`.

Thanks.

**Comment by teunbrand** [comment]
Simply adhering to an aspect ratio isn't going to work either, because one have y-labels that are wider than the x-labels are high (or, less commonly, vice versa). I admit I don't enough about devices and their sizes to give a sensible answer on how feasible this is.

**Comment by thomasp85** [comment]
Short answer is "no" we won't have this in ggplot2. I emphasise with the annoyance this causes but it is one of those issues (of which there are many in programming) that seems simple enough on the surface but is a horrible can of worms when you dig in.

It is true that the plotting area has a fixed aspect ratio that you can query before rendering but that doesn't translate to a fixed aspect for the plot. The plot is surrounded by elements that are measured in absolute size and the amount to which they contribute to the final aspect ratio depends on the dimensions at which they are plotted so we immediately end up in a circular dependency. The there is the issue of faceting that also wreck havoc on any aspect ratio assumptions we may have, as well as the fact that different graphic devices measures text differently or doesn't even find the same fonts which again result in different dimensions for the elements around the plot. The only way to know is to render the plot at a given size and cut off the margins.

**Comment by SimonDedman** [comment]
Cheers Thomas.

I don't know what `magick::image_trim` is doing under the hood, but it does work... would that be a possible approach, i.e. save the image, then resave it with the margins cropped? I wonder if this might get around the worms, insofar as all the sizes and ratios will have been resolved?
