### ISSUE TITLE
scale_binned() removes last bar when show.limits = TRUE

### ISSUE THREAD

**Issue by danatemple** [tidyverse/ggplot2#5095]
I am using geom_bar() and scale_x_binned() to make a histogram with the ticks between the bars.

R 3.6.2, ggplot2 3.3.5. Reproduced on R4.2.2 ggplot2 3.4.0 in this [SO case](https://stackoverflow.com/questions/74715943/r-histogram-scale-x-binned-gets-an-empty-last-bin-and-right-option-appears).

As documented in [this SO issue](https://stackoverflow.com/questions/74715943/r-histogram-scale-x-binned-gets-an-empty-last-bin-and-right-option-appears), the last bin is empty, and it appears to be related to the show.limits being true.

``` r
library(ggplot2)
library(Hmisc, warn.conflicts = FALSE)
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula

Time = c(17, 14, 21, 19, 18, 24, 25, 14, 17, 19, 20, 17, 21, 20, 23, 27, 25, 25, 27, 29, 24, 22, 26, 29)

# The last bin should be 28-30 and have a count of 2

data = data.frame(Time)

p <- ggplot(data, aes(x = Time)) +
  geom_bar()

p + scale_x_binned(right = FALSE, show.limits = TRUE)
#> Warning: Removed 1 rows containing missing values (`geom_bar()`).
```

![](https://i.imgur.com/qCo7aPx.png)

``` r
p + scale_x_binned(right = FALSE, show.limits = FALSE)
```

![](https://i.imgur.com/5xKIPuY.png)

<sup>Created on 2022-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I tested with a function for the limits param, and could see that the passed original limits were set to c(14, 29).

**Comment by teunbrand** [comment]
If we reproduce what happens up to this point:

https://github.com/tidyverse/ggplot2/blob/0d0de37decd4e5c101d70d3f4a4764622e3c70e5/R/scale-binned.R#L73

As follows:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.2.2

x <- c(14, 29)
scale <- scale_x_binned(right = FALSE, show.limits = TRUE)
scale$train(x)

limits <- scale$get_limits()
breaks <- scale$get_breaks(limits)
unique(sort(c(limits[1], breaks, limits[2])))
#>  [1] 14 16 18 20 22 24 26 28 29 30
```

<sup>Created on 2022-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We can see that the distance between breaks is 2, except for the 28-29-30 sequence. This is due to the upper limit being smaller than the largest break

``` r
limits
#> [1] 14 29
breaks
#> [1] 14 16 18 20 22 24 26 28 30
```

It should be able to fix this by recalibrating limits after break calculation.
