### ISSUE TITLE
ggplot 3.4.0 size backwards-compatibility

### ISSUE THREAD

**Issue by bersbersbers** [tidyverse/ggplot2#5111]
The following code works with `ggplot2==3.3.6`, in the sense that `size = 10` increases the line width. It stops doing that with `ggplot2==3.4.0`, and replacing `size = 10` by `linewidth = 10` does not work, either.

```r
# https://github.com/wilkelab/ungeviz
ggplot2::ggplot(data = data.frame(x = 0, y = c(1, 2, 3, 4, 5)), mapping = ggplot2::aes(x = x, y = y)) +
ggplot2::geom_point() +
ggplot2::stat_summary(fun = median, geom = ungeviz::GeomHpline, size = 10)
```

It basically seems to use the default value from here:
https://github.com/wilkelab/ungeviz/blob/aeae12b014c718dcd01343548f2221b58ece63f6/R/geom_hpline.R#L52-L58

Since `ungeviz` has not been touched since 2019, I wonder if there is a workaround or some watch of externally patching it, along the lines of the ggplot 3.4.0 announcement:

> We have gone to great lengths to ensure that old code continues to work.

If that was integrated in a future ggplot version, that would be awesome as well.

**Comment by clauswilke** [comment]
This uses old code from a tech demo that is not maintained. I have thought about copying this code over to ggforce, because I do think the specific geom you're using is helpful, but I have never gotten around to doing it.

In the meantime, as this is only about 100 lines of code, your best bet is to just copy it over to your own code and use that way rather than installing the outdated tech demo.

**Comment by bersbersbers** [comment]
Thank you, this works!
