### ISSUE TITLE
Bug in ggplot2 3.4.0 using scales::probability_trans

### ISSUE THREAD

**Issue by andrewgustar** [tidyverse/ggplot2#5112]
Prompted by this question on StackOverflow, https://stackoverflow.com/questions/74809918/y-axis-scaling-to-normal-distribution there seems to be a bug in how ggplot2 3.4.0 does axis transformations. The example that works as expected in version 3.3.5, producing a nice straight line, is 

```r
data.frame(v = rnorm(1000)) %>% 
    ggplot(aes(x = v)) + 
    stat_ecdf() + 
    scale_y_continuous(trans=scales::probability_trans("norm"))
```

Compare that to the same code in 3.4.0, which gives an S-shaped curve and also has the y axis starting at 0.5. 

In this case, the transformation seems to be using `pnorm` and `qnorm` the wrong way round in adjusting the scale and the axis. 

I tried a few other transformations, and several of them look odd, so I think this is an example of something deeper in the axis transformation routine. 

I'm using R 4.2.2 on Windows 11.

**Comment by teunbrand** [comment]
Hi there, thanks for the report. On a first glance, this issue seems the same as #5113. 

I think this might be related to the recent change introduced in #4194. Briefly, the default aesthetic for the eCDF stat is `y = after_stat(y)`, and the `y` column gets back-transformed. Effectively, the system thinks the values that roll out of the stat are already in transformed space, whereas they're not.

It should be relatively easy to fix by giving the computed variable a different name than `y`.

**Comment by andrewgustar** [comment]
Thanks for the reply. I agree it is probably the same as #5113. I haven't found similar problems with other stats, so your explanation sounds promising. Hopefully a simple fix!
