### ISSUE TITLE
scale_x_log10 does not work with ggplot2 v3.4.0

### ISSUE THREAD

**Issue by elizeng** [tidyverse/ggplot2#5128]
For some reason, the same code works when I load v3.3.4 but not when i load v3.4.0, and the same code used to work with ggpubr.

```
ggplot()+  
  geom_step(data=data, aes(x=Time, y=Ne, color = Individual), size = 1.5) +
  scale_colour_manual(values=colours)+
  theme_bw(base_size=12) +
  labs(x ="Time since present (years)", y = expression(Effective ~population ~Size ~(x10^4))) +
  scale_y_continuous(position = "right")+
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x)), expand = expansion(mult = c(0, .1)), limits=c(10000,10000000))
```

Instead scale_x_continous works with the same input but does not work with limits.

Is this a bug or otherwise?

Package versions:
R v3.6.3 (have always been using this version of R)
ggplot v3.4.0
scales v1.2.1

I changed my ggplot2 to v3.3.6 and it now works, but still does not work on v3.4.0.

**Comment by teunbrand** [comment]
Hi there, would you be able to provide a working, minimal reproducible example of the issue?
I tried to naively replicate the issue, but wasn't able to. It seems to work as intended in ggplot2 3.4.0 as far as I can tell.

**Comment by elizeng** [comment]
Here's what I used.

```
library(readxl)
library(writexl)
library(ggplot2)
require(scales)

data<-read_xlsx("data.xlsx", 1)

colours=c("#48a6a4","black")

ggplot()+  
  geom_step(data=data, aes(x=Time, y=Ne, color = Individual), size = 1.5) + #PSMC
  scale_colour_manual(values=penguin_colours)+
  theme_bw(base_size=12) +
  labs(x ="Time since present (years)", y = expression(Effective ~population ~Size ~(x10^4))) +
  scale_y_continuous(position = "right")+
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x)), expand = expansion(mult = c(0, .1)), limits=c(10000,10000000))
```

[data.xlsx](https://github.com/tidyverse/ggplot2/files/10349401/data.xlsx)

  
The error I got whilst using ggplot2 v3.4.0 was `"Error: 'cli_inform' is not an exported object from 'namespace:cli'"`
Which only appeared with the line with `scale_x_log10`

**Comment by teunbrand** [comment]
Thanks, that allowed me to replicate two warnings and the error message you posted is also helpful. Have you tried (re)installing the cli package with `install.packages("cli")`? It should still work on R3.6.3

**Comment by BB1464** [comment]
I was able to run your code but I discovered that the transformation introduced some infinte values after looking at the layered data:

## Code 

library(readxl)
library(writexl)
library(ggplot2)
require(scales)

data<-read_xlsx(here::here('~/../Desktop/data.xlsx'), 1)

colours=c("#48a6a4","black")

p=ggplot()+  
  geom_step(data=data, aes(x=Time, y=Ne, color = Individual), size = 1.5) + #PSMC
  scale_colour_manual(values=colours)+
  theme_bw(base_size=12) +
  labs(x ="Time since present (years)", y = expression(Effective ~population ~Size ~(x10^4))) +
  scale_y_continuous(position = "right")+
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x)), expand = expansion(mult = c(0, .1)), limits=c(10000,10000000))



layer_data(plot = p,i = 1L)


I was able to run your code but I discovered that the transformation introduced some infinte values:

<html>
<body>


colour           y        x PANEL group size linetype alpha 1     black   0.7518313     -Inf     1     2  1.5        1    NA 2     black   0.7518313       NA     1     2  1.5        1    NA 3     black   0.7518313       NA     1     2  1.5        1    NA 4     black   0.7518313 4.176036     1     2  1.5        1    NA 5     black   9.0540540 4.321454     1     2  1.5        1    NA 6     black   9.0540540 4.439134     1     2  1.5        1    NA 7     black   4.8464772 4.539376     1     2  1.5        1    NA 8     black   4.8464772 4.627664     1     2  1.5        1    NA 9     black   5.2100328 4.707285     1     2  1.5        1    NA 10    black   5.2100328 4.780353     1     2  1.5        1    NA 11    black   5.9287587 4.848302     1     2  1.5        1    NA 12    black   5.9287587 4.912171     1     2  1.5        1    NA 13    black   6.3793766 4.972709     1     2  1.5        1    NA 14    black   6.3793766 5.030498     1     2  1.5        1    NA 15    black   6.0944618 5.085980     1     2  1.5        1    NA 16    black   6.0944618 5.139509     1     2  1.5        1    NA 17    black   5.6842508 5.191371     1     2  1.5        1    NA 18    black   5.6842508 5.241796     1     2  1.5        1    NA 19    black   5.0580053 5.290976     1     2  1.5        1    NA 20    black   5.0580053 5.339069     1     2  1.5        1    NA 21    black   4.2737714 5.386211     1     2  1.5        1    NA 22    black   4.2737714 5.432515     1     2  1.5        1    NA 23    black   3.5939091 5.478080     1     2  1.5        1    NA 24    black   3.5939091 5.522988     1     2  1.5        1    NA 25    black   3.0491803 5.567312     1     2  1.5        1    NA 26    black   3.0491803 5.611115     1     2  1.5        1    NA 27    black   2.6168600 5.654453     1     2  1.5        1    NA 28    black   2.6168600 5.697375     1     2  1.5        1    NA 29    black   2.2760518 5.739922     1     2  1.5        1    NA 30    black   2.2760518 5.782133     1     2  1.5        1    NA 31    black   2.0070952 5.824041     1     2  1.5        1    NA 32    black   2.0070952 5.865676     1     2  1.5        1    NA 33    black   1.8048375 5.907064     1     2  1.5        1    NA 34    black   1.8048375 5.948229     1     2  1.5        1    NA 35    black   1.6715957 5.989193     1     2  1.5        1    NA 36    black   1.6715957 6.029973     1     2  1.5        1    NA 37    black   1.6141408 6.070588     1     2  1.5        1    NA 38    black   1.6141408 6.111053     1     2  1.5        1    NA 39    black   1.6819253 6.151382     1     2  1.5        1    NA 40    black   1.6819253 6.191586     1     2  1.5        1    NA 41    black   2.1224060 6.231678     1     2  1.5        1    NA 42    black   2.1224060 6.271668     1     2  1.5        1    NA 43    black   4.0728423 6.311564     1     2  1.5        1    NA 44    black   4.0728423 6.351375     1     2  1.5        1    NA 45    black  12.4235292 6.391110     1     2  1.5        1    NA 46    black  12.4235292 6.430774     1     2  1.5        1    NA 47    black  40.7465649 6.470374     1     2  1.5        1    NA 48    black  40.7465649 6.509915     1     2  1.5        1    NA 49    black  92.6887786 6.549403     1     2  1.5        1    NA 50    black  92.6887786 6.588843     1     2  1.5        1    NA 51    black 112.3989074 6.628238     1     2  1.5        1    NA 52    black 112.3989074 6.667593     1     2  1.5        1    NA 53    black  72.0384814 6.706911     1     2  1.5        1    NA 54    black  72.0384814 6.746195     1     2  1.5        1    NA 55    black  24.1462796 6.785449     1     2  1.5        1    NA 56    black  24.1462796 6.824675     1     2  1.5        1    NA 57    black  24.1462796 6.863875     1     2  1.5        1    NA 58    black  24.1462796 6.903051     1     2  1.5        1    NA 59  #48a6a4   1.7836093     -Inf     1     1  1.5        1    NA 60  #48a6a4   1.7836093       NA     1     1  1.5        1    NA 61  #48a6a4   1.7836093 4.182528     1     1  1.5        1    NA 62  #48a6a4   1.7836093 4.377094     1     1  1.5        1    NA 63  #48a6a4 108.2727110 4.520761     1     1  1.5        1    NA 64  #48a6a4 108.2727110 4.636651     1     1  1.5        1    NA 65  #48a6a4  36.6783138 4.735046     1     1  1.5        1    NA 66  #48a6a4  36.6783138 4.821457     1     1  1.5        1    NA 67  #48a6a4  21.6346409 4.899147     1     1  1.5        1    NA 68  #48a6a4  21.6346409 4.970241     1     1  1.5        1    NA 69  #48a6a4  15.7399181 5.036178     1     1  1.5        1    NA 70  #48a6a4  15.7399181 5.097988     1     1  1.5        1    NA 71  #48a6a4  12.8827776 5.156427     1     1  1.5        1    NA 72  #48a6a4  12.8827776 5.212076     1     1  1.5        1    NA 73  #48a6a4  10.0027523 5.265379     1     1  1.5        1    NA 74  #48a6a4  10.0027523 5.316688     1     1  1.5        1    NA 75  #48a6a4   7.5840744 5.366292     1     1  1.5        1    NA 76  #48a6a4   7.5840744 5.414421     1     1  1.5        1    NA 77  #48a6a4   6.3259498 5.461267     1     1  1.5        1    NA 78  #48a6a4   6.3259498 5.506992     1     1  1.5        1    NA 79  #48a6a4   5.8304664 5.551730     1     1  1.5        1    NA 80  #48a6a4   5.8304664 5.595595     1     1  1.5        1    NA 81  #48a6a4   5.5721904 5.638687     1     1  1.5        1    NA 82  #48a6a4   5.5721904 5.681091     1     1  1.5        1    NA 83  #48a6a4   5.2640058 5.722880     1     1  1.5        1    NA 84  #48a6a4   5.2640058 5.764118     1     1  1.5        1    NA 85  #48a6a4   4.8368282 5.804862     1     1  1.5        1    NA 86  #48a6a4   4.8368282 5.845160     1     1  1.5        1    NA 87  #48a6a4   4.3093357 5.885057     1     1  1.5        1    NA 88  #48a6a4   4.3093357 5.924591     1     1  1.5        1    NA 89  #48a6a4   3.7535561 5.963797     1     1  1.5        1    NA 90  #48a6a4   3.7535561 6.002706     1     1  1.5        1    NA 91  #48a6a4   3.2658357 6.041345     1     1  1.5        1    NA 92  #48a6a4   3.2658357 6.079738     1     1  1.5        1    NA 93  #48a6a4   2.9147143 6.117908     1     1  1.5        1    NA 94  #48a6a4   2.9147143 6.155875     1     1  1.5        1    NA 95  #48a6a4   2.7397682 6.193656     1     1  1.5        1    NA 96  #48a6a4   2.7397682 6.231268     1     1  1.5        1    NA 97  #48a6a4   2.8028080 6.268725     1     1  1.5        1    NA 98  #48a6a4   2.8028080 6.306042     1     1  1.5        1    NA 99  #48a6a4   3.3195046 6.343229     1     1  1.5        1    NA 100 #48a6a4   3.3195046 6.380299     1     1  1.5        1    NA 101 #48a6a4   5.0246800 6.417260     1     1  1.5        1    NA 102 #48a6a4   5.0246800 6.454123     1     1  1.5        1    NA 103 #48a6a4   9.8968607 6.490895     1     1  1.5        1    NA 104 #48a6a4   9.8968607 6.527583     1     1  1.5        1    NA 105 #48a6a4  20.0959339 6.564196     1     1  1.5        1    NA 106 #48a6a4  20.0959339 6.600739     1     1  1.5        1    NA 107 #48a6a4  30.1591355 6.637217     1     1  1.5        1    NA 108 #48a6a4  30.1591355 6.673637     1     1  1.5        1    NA 109 #48a6a4  29.2217439 6.710002     1     1  1.5        1    NA 110 #48a6a4  29.2217439 6.746318     1     1  1.5        1    NA 111 #48a6a4  20.6893502 6.782588     1     1  1.5        1    NA 112 #48a6a4  20.6893502 6.818817     1     1  1.5        1    NA 113 #48a6a4  11.9003607 6.855006     1     1  1.5        1    NA 114 #48a6a4  11.9003607 6.891161     1     1  1.5        1    NA 115 #48a6a4  11.9003607 6.927283     1     1  1.5        1    NA 116 #48a6a4  11.9003607 6.963375     1     1  1.5        1    NA Warning message: Transformation introduced infinite values in continuous x-axis
--
 
  |  
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by teunbrand** [comment]
I think the scale works as intended. The installation error isn't something ggplot2 can improve.
