### ISSUE TITLE
`stat_summary_hex()` very different from `stat_summary_2d()`

### ISSUE THREAD

**Issue by kkralicek0** [tidyverse/ggplot2#5165]
It seems like `stat_summary_hex()` is now re-organizing or summarizing data in an odd way; meanwhile, `stat_summary_2d()` is still plotting data as expected: 

```r
library(ggplot2)

head(diamonds)
d <- ggplot(diamonds, aes(carat, depth, z = price))

# behaves as expected
d + stat_summary_2d()
```
![ex_2d](https://user-images.githubusercontent.com/50850350/215298916-e450f5ba-347b-4591-9def-ec61cae6153a.PNG)

```r
# not sure how data are being re-organized here
d + stat_summary_hex()
```
![ex_hex](https://user-images.githubusercontent.com/50850350/215298924-d06cc9ff-f4e9-492c-af47-c5faf39d7be3.PNG)

**Comment by flyingfalling** [comment]
I also have this issue.

I found a reference to an old ggplot2 issue (#5044?). Has this been fixed? The version in the CRAN repos is ggplot2_3.4.0

https://community.rstudio.com/t/geom-hex-is-giving-faulty-outputs/153725/12

**Comment by teunbrand** [comment]
This has been fixed in the development version of ggplot2:

https://github.com/tidyverse/ggplot2/blob/882584f915b23cda5091fb69e88f19e8200811bf/NEWS.md?plain=1#L22-L23

You can download the development version as follows:

```r
# install.packages("devtools")
devtools::install_github("tidyverse/ggplot2")
```

We're in the process of preparing a new release #5149, but it is going to take some time still.
