### ISSUE TITLE
Incorrect warning from geom about missing values when scale sets limits, unless data is filtered first

### ISSUE THREAD

**Issue by ellisp** [tidyverse/ggplot2#5250]
---

I found a problem with a misleading warning from geom_xxx when a scale is truncated with the limits argument

I expected no warnings.

I suspect this is related to or the same problem as https://github.com/tidyverse/ggplot2/issues/5118 but because the discussion there is histogram-specific I have opened a new issue.

Here is the code to reproduce the bug:

```r

library(tidyverse)

d <- tibble (yr = rep(2000:2020, 2),
             animal = rep(c("cat", "dog"), each = 21),
             value = rnorm(42))

d |>
  ggplot(aes(x = yr, y = value, colour = animal)) +
  geom_line() +
  scale_x_continuous(limits = c(2011, 2020))
#> Warning: Removed 22 rows containing missing values (`geom_line()`).
```

![](https://i.imgur.com/Uwiohb6.png)

``` r

# also happens with other geoms:
d |>
  ggplot(aes(x = yr, y = value, colour = animal)) +
  geom_point() +
  scale_x_continuous(limits = c(2011, 2020))
#> Warning: Removed 22 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/yq4fL0Y.png)

``` r

# Warning goes away if data is explicitly filtered to match the scale limits:
d |>
  filter(yr >= 2011) |>
  ggplot(aes(x = yr, y = value, colour = animal)) +
  geom_line() +
  scale_x_continuous(limits = c(2011, 2020))
```

![](https://i.imgur.com/wOiZrUu.png)

<sup>Created on 2023-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
```

**Comment by teunbrand** [comment]
I agree that the warning is useful and appropriate, but perhaps the wording could be improved.

The censoring itself occurs in the scales, which doesn't know about what layer it is censoring data. The dropping of the data occurs in the layers, which don't know whether they see `NA`s because they were missing from the beginning, or censored by the out-of-bounds handler. This makes it a bit hard to signal a tailored error message.

Instead, we might just update the wording so that it reflects the possibility of censored data:

```
#> Warning: Removed 22 rows containing excluded or missing values (`geom_point()`).
```
