### ISSUE TITLE
geom_abline no longer being included in legend

### ISSUE THREAD

**Issue by JaredAllen2** [tidyverse/ggplot2#5320]
Lines plotted using geom_abline are no longer being included in the plot legend, even when including "show.legend=TRUE". 

```{r}
library(ggplot2)
mtcars <- dput(mtcars)
ggplot(mtcars, aes(x=wt, y=hp, colour=cyl)) + geom_point() + geom_abline(slope=50, show.legend=TRUE)
```

**Comment by teunbrand** [comment]
Because you're providing `slope`, `geom_abline()` will act as an annotation and ignore any mappings. To spawn a legend for `geom_abline()`, use an aesthetic mapping that will be displayed in a legend. For example:

``` r
library(ggplot2)

ggplot(mtcars, aes(x=wt, y=hp, colour=cyl)) + 
  geom_point() + 
  geom_abline(
    data = data.frame(slope = 50),
    aes(slope = slope, intercept = 0, linetype = "my line")
  )
```

![](https://i.imgur.com/esqTEc4.png)

<sup>Created on 2023-06-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
