### ISSUE TITLE
stat_summary_hex not working properly with discrete z values

### ISSUE THREAD

**Issue by rvalieris** [tidyverse/ggplot2#5353]
I found a problem with `stat_summary_hex` when `z` is a discrete variable:

```R
p1 = ggplot(diamonds, aes(x=carat, y=depth)) + geom_hex()
p1 # ok, default stat

p2 = ggplot(diamonds, aes(x=carat, y=depth)) + stat_summary_hex(aes(z=carat),fun=length)
p2 # ok, same result as p1, carat is a continuous variable 

p3 = ggplot(diamonds, aes(x=carat, y=depth)) + stat_summary_hex(aes(z=cut),fun=length)
p3 # bug, cut is a discrete variable
```
![p3](https://github.com/tidyverse/ggplot2/assets/6310472/1d1a31b1-fce6-410b-8534-c574de6c5064)

I expected p3 to be the same as p1 and p2 since length should return the same number regardless of which variable I pick for `z`, however it seems that the bins are being grouped by `z`, which was not intended.

Also `stat_summary_2d` have the same behavior, but its harder to see the overlapping bins.

this was tested with ggplot2 3.4.2

**Comment by teunbrand** [comment]
I think this is one of the cases documented in `?aes_group_order` where the defaults fail. In any case, it is true in (almost?) all geoms that using a discrete variable auto-implies grouping and I don't think it would make sense to apply a specific exception here. The plot can be fixed by using `aes(group = 1)` in either the main plot call or the `stat_summary_hex()`.

**Comment by rvalieris** [comment]
Thanks, that `The 'group' aesthetic is by default set to the interaction of all discrete variables in the plot.` was missing for me, I did tried to set `group=NULL` but didn't see any difference, `group=1` solves the issue.
