### ISSUE TITLE
geom_dotplot() with continuous x variable and a categorical y variable.

### ISSUE THREAD

**Issue by retodomax** [tidyverse/ggplot2#5462]
I found a problem with `geom_dotplot()` if I provide a continuous x variable and a categorical y variable.

I expected a plot as the following but with reversed x and y axis.

``` r
library(ggplot2)
ggplot(data = iris) +
  geom_dotplot(aes(y = Sepal.Length, x = Species), binaxis = "y")
```

![](https://i.imgur.com/IrXdHo8.png)

Instead, I got the following

``` r

ggplot(data = iris) +
  geom_dotplot(aes(x = Sepal.Length, y = Species), binaxis = "x")
```

![](https://i.imgur.com/81nYl3e.png)

The dots start at the bottom instead of at the corresponding species level (y-axis).

<sup>Created on 2023-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The culprit seems to be the following line:

https://github.com/tidyverse/ggplot2/blob/88357090ea36bcf1f12ad847d2e507c5bc263530/R/geom-dotplot.R#L249

Which was originally written for compatibility with `coord_flip()` in 0de20da0574cd897fc45f5f83bf3ba7fa01b1511. 

`coord_flip()` has been deprecated in favour of swapping x/y aesthetics but that doesn't seem to work here. I'm a bit surprised that `geom_dotplot()` doesn't have the bidirectionality mechanism introduced in ggplot2 3.3.0.

@thomasp85 do you happen to remember why `geom_dotplot()` was exempted from #3506?
