### ISSUE TITLE
SVG saved with a different size to PNG

### ISSUE THREAD

**Issue by edent** [tidyverse/ggplot2#5497]
I found a problem with `ggsave` - when I save an SVG with an explicit height and width in px, it is saved with smaller dimensions than specified.

I expected the SVG save would take the same commands of the PNG save.

```r
ggsave("test.png", width = (1600), height = (900), units = "px", limitsize = FALSE)
ggsave("test.svg", width = (1600), height = (900), units = "px", limitsize = FALSE)
```

The SVG is saved with dimensions of 512x288.  The SVG header shows:
 
` width='384.00pt' height='216.00pt' viewBox='0 0 384.00 216.00'`

I don't understand why it is using pt rather than px, nor why they are 3.125x smaller. I assume that it's because something is treating the pixels as being printed at 96dpi and then trying to make them 300dpi?

The [documentation](https://ggplot2.tidyverse.org/reference/ggsave.html) says that I should be able to specify pixels and that the dpi setting only affects raster graphics.

Any idea what's going on here? I can manually multiply the dimension, but I'd like to understand if the bug's with ggplot2 or me.

**Comment by teunbrand** [comment]
I think the dimensions are first cast to inches and then forwarded to the device.
So 1600px / 300dpi = 5.333in, next from inches to pts is 72 pt/in so that would be 384pts in width.
I think the graphics devices have inches as the dimensions, so it makes sense to me to cast to inches first, but why the svg devices then converts this to points is unknown to me.

**Comment by teunbrand** [comment]
I think the documentation should just be a little bit clearer when `dpi` is applied.
