### ISSUE TITLE
element_text() ignores left and right margins for some plot elements

### ISSUE THREAD

**Issue by ccsarapas** [tidyverse/ggplot2#5533]
Left and right margins get ignored for some elements (including plot titles and captions), but work fine for other elements (such as strip and axis labels.

Given this plot:
``` r
library(ggplot2)

p <- ggplot(mpg, aes(cty, hwy)) +
  geom_point() +
  facet_wrap(vars(cyl)) +
  labs(
    title = "City vs. Highway Mileage by Cylinders", 
    caption = "Values are in MPG."
  ) +
  theme(
    plot.background = element_rect(color = "black", linewidth = 1),
    axis.title.y = element_text(angle = 0, vjust = 0.5),
    strip.text = element_text(hjust = 0)
  )

p
```

![](https://i.imgur.com/PbNmvFp.png)

You can change the top and bottom margins for the title and caption, but the left and right margins don't budge:
``` r
p + 
  theme(
    plot.title = element_text(margin = margin(20, 20, 20, 20)),
    plot.caption = element_text(margin = margin(20, 20, 20, 20))
  )
```

![](https://i.imgur.com/zUIeP4M.png)

But all 4 margins seem to work for axis titles and strip labels:
``` r
p +
  theme(
    strip.text = element_text(margin = margin(20, 20, 20, 20)),
    axis.title.y = element_text(margin = margin(20, 20, 20, 20))
  )
```

![](https://i.imgur.com/2O7Adud.png)

<sup>Created on 2023-11-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
For some theme elements, only one margin is used purposefully, see for example the (sub)title/caption declarations here:

https://github.com/tidyverse/ggplot2/blob/ca47270fc504193dcf3a29b89408f59df767668c/R/plot-build.R#L267-L277

For some elements, say x-axis text, the horizontal margins are ignored due to the labels being linked to a single point that varies in the x-direction. This makes sense to me. 

Other elements are linked to a cell in the layout, like the titles.  It makes less sense to me to ignore part of the margins there.
The default theme's margins are 0 for left/right (sub)titles and captions, so I don't see any explicit harm in enabling them, but I'd like to wait out to hear what the others think.
