### ISSUE TITLE
last_plot retrieves only custom axis of plot

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#5552]
I have a package called [deeptime](https://williamgearty.com/deeptime/index.html) which adds a custom axis to a ggplot by extending the `CoordTrans` class. As part of this extension, it generates a list of ggplot objects which are converted to grobs, combined into a gTree, and then used for the axis. Unfortunately, somewhere along the line, this process causes the last_plot to be set to the last of these axis ggplot objects and not the full ggplot object that is returned to the user. So, when last_plot() or ggsave() is called, it only returns or saves (respectively) that last axis object. I've included code below to reproduce the issue. I'd appreciate any suggestions anyone might have!

``` r
library(ggplot2)
library(deeptime)
# single scale on bottom
ggplot() +
    geom_point(aes(y = runif(1000, 0, 8), x = runif(1000, 0, 1000))) +
    scale_x_reverse() +
    coord_geo(list("bottom", "bottom"), xlim = c(1000, 0), ylim = c(0, 8)) +
    theme_classic()
```

![](https://i.imgur.com/Qc6B6kG.png)

``` r
last_plot()
```

![](https://i.imgur.com/QSaecAu.png)

<sup>Created on 2023-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The functionality of annotating the (x-)axis with (I presume, geological time) ranges sounds like a prime candidate to implement as a guide instead of a separate plot. 

From a brief glance at the code, it seems like you are building a new plot in this line: https://github.com/willgearty/deeptime/blob/4bf2fdfb19d25b1218531b9add7243eb3d9c50e3/R/gggeo_scale.R#L180C11-L180C11
The default S3 method for `ggplot()` sets a new last plot, so presumably that might be overriding what you 'expect' to be the last plot. Wouldn't it solve the issue to call `set_last_plot()` somewhere before you return the final object from that code?

**Comment by willgearty** [comment]
I suppose I could make an internal function that is identical to [`ggplot.default()`](https://github.com/tidyverse/ggplot2/blob/a96e6640214a99a9488d166353f94bf8939b52b2/R/plot.R#L110), but without the `set_last_plot()` call, then use that when I am assembling the geological time scales?

Also, adding the geological time scales works fairly well as a coord at the moment. Is there a reason you think it would be better as a guide?

**Comment by teunbrand** [comment]
Right thanks for pointing out the relevant file. The same thing seems to happen here:  ttps://github.com/willgearty/deeptime/blob/4bf2fdfb19d25b1218531b9add7243eb3d9c50e3/R/coord_geo.R#L328C1-L328C2

Does it help to do the following just above the line I mentioned?
```r
old_plot <- last_plot()
on.exit(set_last_plot(old_plot))
```

**Comment by willgearty** [comment]
That does work, thank you so much!
