### ISSUE TITLE
In `theme`, could `axis.ticks` inherit from `axis.line`?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5673]
I think 99% of the time when people change the axis line colour, they would also like to change the ticks to this colour likewise.

So in the below example, I think it would be helpful if the ticks colour also changed to red without the user needing to add code for this.

``` r
library(tidyverse)
library(palmerpenguins)

penguins |> 
  ggplot() +
  geom_point(
    aes(x = flipper_length_mm,
        y = body_mass_g)
  ) +
  theme_classic() +
  theme(axis.line = element_line(colour = "red"))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/RW7FHro.png)

<sup>Created on 2024-02-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
The reason why this isn't happening is because the axis ticks actually have a different color than the axis line in `theme_classic()`. Not sure if this is intentional or not, but it's one of these things most people are not aware of.

``` r
library(tidyverse)

df <- tibble(x = 1:3, y = 3:1)

ggplot(df, aes(x, y)) +
  geom_point(color = "red", size = 5) +
  theme_classic() +
  theme(
    line = element_line(linewidth = 10),
    axis.ticks.length = unit(40, "pt")
  )
```

![](https://i.imgur.com/Y9M5wZV.png)

<sup>Created on 2024-01-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Aha, thanks! 

Feel free to close then @clauswilke, unless you think `theme_classic` etc should be updated per this
