### ISSUE TITLE
geom_dotplot y scale does not seem to be built correctly

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5787]
The max dots are cut in half, and there is no expanding at the upper end

``` r
library(tidyverse)
library(palmerpenguins)

penguins |> 
  ggplot() +
  geom_dotplot(aes(x = flipper_length_mm))
#> Bin width defaults to 1/30 of the range of the data. Pick better value with
#> `binwidth`.
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`stat_bindot()`).
```

![](https://i.imgur.com/PN3fiqC.png)

<sup>Created on 2024-03-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
This is because `geom_dotplot()` is one of those arcane layers where the absolute size of the dots needs to be reconciled with the relative size of the plot window. The solution to this would be to dynamically adjust the binning to have the max stack size not exceed the plotting window, but that would require a complete rewrite of the geom and stat. I recommend using `ggdist::geom_dots()` instead.

**Comment by davidhodge931** [comment]
Oh, thanks @teunbrand
