### ISSUE TITLE
Could colour bar guide ticks be more readable?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5852]
Currently, the ticks are hard to read when on light colours.

Also, the ticks on the side furthest from the labels are not required.

Possible solutions:
* ticks on the outside 
* colour inside ticks a light/dark colour depending on the key colour

For either solution, it'd be cool if it was more minimalist with ticks only closest to the label

**Comment by teunbrand** [comment]
Some of these already have solutions.
To just put ticks on one side of the colourbar, set the size to 0 for one of the ticks:

``` r
library(ggplot2)

p <- ggplot(mpg, aes(displ, hwy, colour = cty)) +
  geom_point()

p + theme(legend.ticks.length = rel(c(0.2, 0)))
```

![](https://i.imgur.com/I7nGu8i.png)

To put ticks outside the bar, use negative tick lengths.
I'm overriding `legend.ticks` because white ticks can't be seen on white background.

``` r
p + theme(legend.ticks.length = rel(c(-0.2, -0.2)),
          legend.ticks = element_line())
```

![](https://i.imgur.com/pxNNLc2.png)

<sup>Created on 2024-04-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Aha, thanks @teunbrand !

Feel free to change, if you think defaults should stay as is

**Comment by teunbrand** [comment]
Changing these defaults will probably affect a lot of people's plots, so I'd rather refrain from that unless there is an objective improvement to be made. Stylistic sensibility varies from person to person, so let's leave this as is for now.
