### ISSUE TITLE
Cryptic error when mis-specifying linetype

### ISSUE THREAD

**Issue by njspix** [tidyverse/ggplot2#5864]
When 'linetype' is mis-specified, the resulting error is extremely confusing, and could be misleading if a color is also specified for the line. I would expect the error to read something like `'dash' is not a valid linetype`.

Reprex:
``` r
library(tidyverse)
tibble(
  x = rnorm(50),
  y = rnorm(50)
) |> 
  ggplot()+
  geom_point(aes(x, y))+
  geom_abline(linetype = "dash", color = "gray")
#> Error in grid.Call.graphics(C_segments, x$x0, x$y0, x$x1, x$y1, x$arrow): invalid hex digit in 'color' or 'lty'

tibble(
  x = rnorm(50),
  y = rnorm(50)
) |> 
  ggplot()+
  geom_point(aes(x, y))+
  geom_abline(linetype = "dash")
#> Error in grid.Call.graphics(C_segments, x$x0, x$y0, x$x1, x$y1, x$arrow): invalid hex digit in 'color' or 'lty'

tibble(
  x = rnorm(50),
  y = rnorm(50)
) |> 
  ggplot()+
  geom_point(aes(x, y))+
  geom_abline(linetype = "dashed")
```

![](https://i.imgur.com/Miqt96o.png)

<sup>Created on 2024-04-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report! While I agree that this is a poor error message, this error isn't really under ggplot2's control as it is thrown from {grid}. Unrelated to linetype, I'm not sure that doing (computationally 'expensive') checks on input data is the best idea as it can hamper some performance.

**Comment by njspix** [comment]
Thanks for clarifying. I understand better now why the error is thrown, seems like `dash` is getting passed as a hex string to grid, and of course `s` and `h` are not valid hex. 

Related to performance, I'm not a maintainer of a huge codebase used by 100k's of people, so I don't understand everyone's use case. However I fail to see how input validation could impose a substantial performance cost. I'll venture that the time it took me to understand this error was several orders of magnitude greater than the runtime of e.g. `linetype %in%  c("dashed", "dot" ...) | str_detect(linetype, "^[0-9a-f]+$")`...

**Comment by njspix** [comment]
Ah, that makes perfect sense. Thank you for clarifying!

I don't know that the error message is particularly bad from `grid`'s perspective. For all it knows, it's just being passed an invalid hex color. And trying to ask them to change the error message just for `ggplot` creates a sort of 'accidental api', which I doubt would be mutually beneficial. 

It's a bigger ask, but perhaps we could consider whether the 'linetype' argument is a little _too_ flexible? I understand the attraction of flexibility, but I really think the error message is pretty bad... :-)

**Comment by teunbrand** [comment]
I don't think limiting what can be considered a linetype is the right way forward, as it'll hurt backward compatibility. All valid input is documented in the [vignette](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html#sec:line-type-spec). Grid's error message could just be `Invalid linetype: "dash"` like they do for colours. It doesn't need to be tailored to ggplot2. Saying that the hex code is wrong (incorrectly) assumes that the user was trying to pass a linetype as a hex code, which might start off the user on the wrong path to solving the issue.

In any case, while I agree with you that the error message can be improved, I don't think it is ggplot2's place to do input validation for the reasons outlined in my previous message. I'll close the issue here and we can reopen if other maintainers disagree with me.

**Comment by njspix** [comment]
Great, thank you very much!
