### ISSUE TITLE
ggplot object gets updated without formal assignment

### ISSUE THREAD

**Issue by stitam** [tidyverse/ggplot2#5994]
Below is a simple example in which I prepare two scatter plots using the mtcars data set. `var` contains the name of the variable in mtcars which should be plotted on the y axis. Notice when I change the value of `var` the plot is automatically updated without any formal assignment. Does this happen on your end as well? Is this normal behaviour? Many thanks.

```
library(ggplot2)
data(mtcars)
var <- "cyl"
g <- ggplot(mtcars, aes(get(var), mpg)) + geom_point()
g
```

![](https://i.imgur.com/Y77wTvp.png)

``` r
# change the value of var
var <- "wt"
# look at the original (!) plot
g
```

![](https://i.imgur.com/tgb38mM.png)

<sup>Created on 2024-07-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This was prepared in a clean environment, R v4.4.1, ggplot2 v3.5.1

**Comment by teunbrand** [comment]
These are the consequence of delayed evaluation of the `get()` function in `aes()`. The plot object `g` doesn't get updated, the variable is looked up by `get()` when the plot is build (which happens during printing) rather than when plot components are declared.

For programatically giving variables by name, we instead recommend the `.data[[var]]` construct. This is documented in [this section of the vignette](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html#using-aes-and-vars-in-a-package-function). Please note that the second plot now hasn't changed. 

``` r
library(ggplot2)

var <- "cyl"
g <- ggplot(mtcars, aes(.data[[var]], mpg)) + geom_point()
g
```

![](https://i.imgur.com/ypaTN6V.png)

``` r
var <- "wt"
g
```

![](https://i.imgur.com/tAF6v64.png)

<sup>Created on 2024-07-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by stitam** [comment]
Solves the issue, thanks @teunbrand.
