### ISSUE TITLE
Could `position_dodge` have a `padding` argument?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#6001]
Just as this is sometimes useful in `position_dodge2`, it could be useful at times in `position_dodge`

It would also be a way to have borders around dodged bars, and resolve issues with positioning noted in https://github.com/tidyverse/ggplot2/issues/5997

**Comment by teunbrand** [comment]
I think you can already specify padding using the `width` aesthetic and the `position_dodge(width)` parameter. Is there an example that is inconvenient where `padding` would alleviate some gnarlyness?

**Comment by davidhodge931** [comment]
Ah I see, I didn't think of this! No, I can't think of an example that could not be achieved by using that method.  

Still though, conceptually, if `position_dodge` and `position_dodge2` are intended to be the same other than the grouping variable thing, then they should have the same arguments? So, either add `padding` to `position_dodge` or deprecate it from `position_dodge2` if not needed. Likewise for `reverse`.

Feel free to close

**Comment by teunbrand** [comment]
So `position_dodge2()` needs a `padding` argument because it deals with variable-width data structures, whereas `position_dodge()` does not. For this reason, using `width` fixes the issue for `position_dodge()` but not `position_dodge2()`.
The `reverse` argument has been added in #5932. 

> Feel free to close

Let's do this
