### ISSUE TITLE
`coord_polar()` and `coord_radial()` break normal conventions about measuring angles

### ISSUE THREAD

**Issue by jdonland** [tidyverse/ggplot2#6125]
Currently, `coord_polar()` and `coord_radial()` count angles in radians, but start from north instead of east, and `direction = -1` means the positive direction. Is there a reason for this idiosyncratic approach?

**Comment by teunbrand** [comment]
Not that I know of. As far as I can tell the transformation has had its current form since inception. However, this issue tracker is used to track bugs and feature requests; discussion is best facilitated elsewhere, like the [posit community](https://forum.posit.co/). For this reason, I'll close this issue here.
