### ISSUE TITLE
Can `ggplot2` adopt orphaned `ggtern` package?

### ISSUE THREAD

**Issue by kevinwolz** [tidyverse/ggplot2#6197]
[`ggtern`](https://github.com/nicholasehamilton/ggtern) is a great package that builds onto `ggplot2` by adding ternary plot functionality. Unfortunately, the package has not been updated in over 9 years and officially ceased to work with `ggplot2` after the recent upgrade to version `3.5`. See https://github.com/nicholasehamilton/ggtern/issues/57. 

Is `ggplot2` interested in adopting `ggtern` in some way? 

Or is someone in the community interested in forking it and make the (likely small) tweaks to get it compatible with `ggplot2 3.5`?

**Comment by teunbrand** [comment]
I don't have any problem rendering a ggtern plot.

``` r
library(ggtern)
#> Loading required package: ggplot2
#> Registered S3 methods overwritten by 'ggtern':
#>   method           from   
#>   grid.draw.ggplot ggplot2
#>   plot.ggplot      ggplot2
#>   print.ggplot     ggplot2
#> --
#> Remember to cite, run citation(package = 'ggtern') for further info.
#> --
#> 
#> Attaching package: 'ggtern'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     aes, annotate, ggplot, ggplot_build, ggplot_gtable, ggplotGrob,
#>     ggsave, layer_data, theme_bw, theme_classic, theme_dark,
#>     theme_gray, theme_light, theme_linedraw, theme_minimal, theme_void
packageVersion("ggplot2")
#> [1] '3.5.1'

data("Feldspar")
ggtern(Feldspar, aes(Ab, An, Or)) +
  geom_point()
```

![](https://i.imgur.com/g8JLybk.png)

<sup>Created on 2024-11-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

> the package has not been updated in over 9 years

The latest CRAN release dates to 2024-03-24. I think the author prefers development on bitbucket rather than github: https://bitbucket.org/nicholasehamilton/ggtern/src/master/.

> Is ggplot2 interested in adopting ggtern in some way?

It is ggplot2's policy to limit new features to either easy to maintain features or widely useful improvements. Ternary plots are rather specialised and, I imagine, hard to maintain. For these reasons, I'd say it is unlikely that ggplot2 will adopt ggtern.
