### ISSUE TITLE
Feature request: Make `%+%` into an S3 generic

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#6221]
In situations when I'm using the `ggtibble` package, I want to be able to use any operations that can occur on a `gg` object on a `ggtibble` and `gglist` object.

I would like to be able to use `%+%` on a `ggtibble` object, but it is not generic, so I can't easily use it. If package load order is `ggtibble` then `ggplot2`, the `ggplot2 `%+%` function will be used instead of a generic from `ggtibble`.

**Comment by teunbrand** [comment]
Hi there, thanks for the suggestion! This has been suggested before in https://github.com/tidyverse/ggplot2/issues/5536#issuecomment-1823596233. The larger issue of encoding custom behaviour for custom classes of ggplot2-like object has been discusssed in #3815. The reasoning at the time was that we don't want to export `%+%` as a generic, as we should solve this problem with proper double dispatch. S4 was excluded due to its rigity and S7 was entertained for a while. A proof of concept was coined in #5537, but we felt S7 wasn't ready yet. In any case, to keep all related discussion in one place, I'm going to close this issue in favour of #5536.

**Comment by billdenney** [comment]
Thanks!
