### ISSUE TITLE
Strange scale_x_datetime offset

### ISSUE THREAD

**Issue by bharris-fs** [tidyverse/ggplot2#824]
I often plot data from a data frame that has both a POSIXct and a
numeric column.  The following code creates such a data frame and plots
the data:

```
require(ggplot2)
require(scales)
require(lubridate)
timelist <- ymd_hm(c("2013-05-01 12:00","2013-05-02 18:00","2013-05-03 06:00"),tz="America/Los_Angeles")
sampleDF <- data.frame(time = timelist, values = c(3,4,2))
qplot(time, values, data = sampleDF)+scale_x_datetime(minor_breaks=date_breaks("6 hour"))
```

When I run the code above, I get a plot with the three points at the
right times, but the minor break lines are offset apparently by 3 hours
from the axis.  I expected the minor breaks to coincide with the major
breaks.  That is, I expected minor breaks at 0:00, 6:00, 12:00, 18:00,
..., with major breaks as scales chose, but I get minor breaks at 3:00,
9:00, ....

My time zone is "America/Los_Angeles", but I get the same result when I
use "UTC" for the data instead.  

There was a discussion about this at https://groups.google.com/forum/#!topic/ggplot2/Kvdx70hF51A.  While Brian Waismeyer's solution seems to work, it seems more than a bit unintuitive and thus out of character for ggplot2 and a bit fidgety.

**Comment by sheriferson** [comment]
@bharris-fs I had been struggling with this problem for hours, and I found a solution that might help.

For many months the time series plots I was creating using ggplot2 and `scale_x_datetime` were as I expected, and then sometime over the last weeks or months (the plots are created with a script and I don't look at them every day) I realized that I was getting a similar offset to the one you describe.

What helped me is setting `tz` in the `date_format` function that `scale_x_datetime` accepts for its `labels` parameter.

So, this used to work for months but then stopped working:
```
   ...
    scale_y_datetime(breaks=date_breaks("1 hour"),
                     labels = date_format("%H:%M"),
                     limits = range(keys7$ytime),
                     expand = c(0,60)) +
   ...
```

And changing it to this made the plot make sense again (given the data I was feeding ggplot):

```
   ...
    scale_y_datetime(breaks=date_breaks("1 hour"),
                     labels = date_format("%H:%M", tz="America/Toronto"), # <======
                     limits = range(keys7$ytime),
                     expand = c(0,60)) +  
    ...
```

You can replace `tz` with what `Sys.timezone()` gives you in the R console when run in your home timezone.

Apologies for re-opening an issue that was closed over a year ago, but this issue was hitting me now and the solution might help some people out there.

**Comment by nicornk** [comment]
@bharris-fs 
Same as you, I was struggling for hours with this issue. Almost the whole day wasted.

Thanks to you it works now as expected. Thanks for the provided workaround!

**Comment by Sylvain-Frey** [comment]
Horrific/fascinating bug. Almost worth the headache and lost time :) 

Sys.timezone() workaround solved it for me as well, it had to be added to every use of as.POSIXct() in data manipulation though.
